### ISSUE TITLE
全量同步问题，求助

### ISSUE THREAD

**Issue by sieger2001** [alibaba/otter#100]
群主，你好。按照下述操作：
1、主库、从库新建空库。
2、启动channel。这时候主库做ddl、dml从库做dml操作无报错，同步正常。
3、在主库上执行由生产库mysqldump备份的数据。
4、发现channel挂起，出现find table .. error的错误提示。

求指点迷津。

**Comment by dingding2015** [comment]
全量同步是如何实现的？可否留下联系方式，指点一下？

**Comment by agapple** [comment]
find table error主要为源库执行了表删除操作，具体约束可以看下otter faq
