### ISSUE TITLE
疑问：我有一个双向的channel，里面有两个pipeline,我在主库上新增一条记录，观察主库的pipeline的InsertCount增加1，但是奇怪的是我发现pipeline 的InsertCount也增加1

### ISSUE THREAD

**Issue by Bruce2jiang** [alibaba/otter#101]
疑问：我有一个双向的channel，里面有两个pipeline,我在主库上新增一条记录，观察主库的pipeline的InsertCount增加1，但是奇怪的是我发现pipeline 的InsertCount也增加1

**Comment by Bruce2jiang** [comment]
疑问：我有一个双向的channel，里面有两个pipeline,我在主库上新增一条记录，观察主库-->从库的pipeline的InsertCount增加1，但是奇怪的是我发现从库-->主库pipeline 的InsertCount也增加1

**Comment by Bruce2jiang** [comment]
这个现象正常吗

**Comment by agapple** [comment]
不正常，应该出现循环复制了，看不到现场无法定位

**Comment by Bruce2jiang** [comment]
群主，能不能说下 都哪些操作或者配置可能会导致 循环复制
