### ISSUE TITLE
Otter支不支持代理

### ISSUE THREAD

**Issue by zhangkou** [alibaba/otter#104]
我们现在有两个mysql 数据库:
一个在公司内网mysql 数据库
另外一个使用的是ali RDS mysql云数据库。

otter是否支持代理，我需要公司内网的mysql和ali 云的mysql同步数据，不知道otter是否支持我们的需求，如何配置？

**Comment by agapple** [comment]
otter自身不提供代理功能，依赖系统本身的饿网络，可以将代理模式设置为全局性，比如VPN.
