### ISSUE TITLE
主库出现大量的未关闭句柄，对应linux命令 ： lsof -p 28314|grep CLOSE_WAIT

### ISSUE THREAD

**Issue by Bruce2jiang** [alibaba/otter#105]
你好，我的问题是这样的，我使用otter同步A库（主）和B库数据（从），主库最近一周每天都会出现
大量的未关闭句柄，第二天早上只能重启数据库A,    后来我把B库改为主数据库，A库为从数据库，这时候A库好了，没有出现未关闭句柄，但是B库很快就出现大量未关闭的句柄，请帮忙分析一下 ：

mysqld  28314 mysql 2640u  IPv6           18315102       0t0      TCP linux:mysql->10.17.82.17:58290 (CLOSE_WAIT)
mysqld  28314 mysql 2642u  IPv6           18315130       0t0      TCP linux:mysql->10.17.82.17:58293 (CLOSE_WAIT)
mysqld  28314 mysql 2644u  IPv6           18315137       0t0      TCP linux:mysql->10.17.82.17:58296 (CLOSE_WAIT)
mysqld  28314 mysql 2646u  IPv6           18315143       0t0      TCP linux:mysql->10.17.82.17:58299 (CLOSE_WAIT)
mysqld  28314 mysql 2648u  IPv6           18315149       0t0      TCP linux:mysql->10.17.82.17:58302 (CLOSE_WAIT)
mysqld  28314 mysql 2650u  IPv6           18315155       0t0      TCP linux:mysql->10.17.82.17:58305 (CLOSE_WAIT)
mysqld  28314 mysql 2652u  IPv6           18315542       0t0      TCP linux:mysql->10.17.82.12:35888 (CLOSE_WAIT)
mysqld  28314 mysql 2654u  IPv6           18315567       0t0      TCP linux:mysql->10.17.82.12:35891 (CLOSE_WAIT)
mysqld  28314 mysql 2656u  IPv6           18315570       0t0      TCP linux:mysql->10.17.82.12:35894 (CLOSE_WAIT)
mysqld  28314 mysql 2658u  IPv6           18315576       0t0      TCP linux:mysql->10.17.82.12:35897 (CLOSE_WAIT)
mysqld  28314 mysql 2660u  IPv6           18315580       0t0      TCP linux:mysql->10.17.82.12:35900 (CLOSE_WAIT)
mysqld  28314 mysql 2662u  IPv6           18315594       0t0      TCP linux:mysql->10.17.82.12:35903 (CLOSE_WAIT)
mysqld  28314 mysql 2664u  IPv6           18315597       0t0      TCP linux:mysql->10.17.82.12:35906 (CLOSE_WAIT)

**Comment by agapple** [comment]
没处理过类似问题，最好需要描述下现场以及是否可稳定重现

**Comment by agapple** [comment]
canal:https://github.com/alibaba/canal/issues/139，估计是这一个问题，请升级使用1.0.22 canal版本
