### ISSUE TITLE
otter不是严格安装事务为单位同步的，应该就会存在部分数据不一致（本身是一个事务的操作），从而导致业务问题。不知道自己是否理解正确，如果是这种情况怎么解决？

### ISSUE THREAD

**Issue by CliffYuan** [alibaba/otter#106]

**Comment by agapple** [comment]
https://github.com/alibaba/otter/wiki/Otter%E6%95%B0%E6%8D%AE%E5%85%A5%E5%BA%93%E7%AE%97%E6%B3%95

看下数据入库算法

**Comment by CliffYuan** [comment]
意思是通过表权重控制一个批次(batchId)中的执行顺序，从而达到表面上看到的事务可见性。
这并不能控制吧，比方说一个事务分成在两个不同的batch中。

**Comment by agapple** [comment]
当然没有严格意义上的事务可见性，性能和功能的取舍
