### ISSUE TITLE
同步报错 Caused by: java.lang.NoSuchFieldError: MYSQL

### ISSUE THREAD

**Issue by crazypaving** [alibaba/otter#1068]
pid:2 nid:1 exception:canal:canal4:com.alibaba.otter.canal.parse.exception.CanalParseException: java.lang.NoSuchFieldError: MYSQL
Caused by: java.lang.NoSuchFieldError: MYSQL
at com.alibaba.otter.canal.parse.inbound.mysql.ddl.DruidDdlParser.parse(DruidDdlParser.java:51)
at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseQueryEvent(LogEventConvert.java:258)
at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:120)
at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:71)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser.parseAndProfilingIfNecessary(AbstractEventParser.java:414)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1$1.sink(AbstractEventParser.java:214)
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:185)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:276)
at java.lang.Thread.run(Thread.java:748)

**Comment by hope-courage** [comment]
请问解决了吗？

**Comment by whhe** [comment]
提供下版本信息

**Comment by Lq-sin** [comment]
druid版本问题，canal 1.1.5中druid版本为1.2.6，otter中被改为了1.1.9导致的问题
个人处理：把版本改为1.2.6，otter中node.etl保留1.1.9

**Comment by Lq-sin** [comment]
druid版本问题，canal 1.1.5中druid版本为1.2.6，otter中被改为了1.1.9导致的问题
个人处理：把版本改为1.2.6，otter中node.etl保留1.1.9

**Comment by hope-courage** [comment]
非常感谢，多谢大佬帮助



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月22日(星期五) 上午9:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/otter] 同步报错 Caused by: java.lang.NoSuchFieldError: MYSQL (Issue #1068)





 
druid版本问题，canal 1.1.5中druid版本为1.2.6，otter中被改为了1.1.9导致的问题
 个人处理：把版本改为1.2.6，otter中node.etl保留1.1.9

**Comment by redgreat** [comment]
> druid版本问题，canal 1.1.5中druid版本为1.2.6，otter中被改为了1.1.9导致的问题 个人处理：把版本改为1.2.6，otter中node.etl保留1.1.9

我换了好多druid版本，没想到是canal的对不上

**Comment by xdkaka** [comment]
> druid版本问题，canal 1.1.5中druid版本为1.2.6，otter中被改为了1.1.9导致的问题 个人处理：把版本改为1.2.6，otter中node.etl保留1.1.9

求助大佬要怎么改呢？
不会JAVA，直接改的pom.xml 里的版本号，打包的时候报错：
````
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project node.etl: Compilation failure: Compilation failure:
[ERROR] /weiqu/otter-master/node/etl/src/main/java/com/alibaba/otter/node/etl/common/db/utils/DdlUtils.java:[130,18] cannot find symbol
[ERROR]   symbol:   method isIfNotExiists()
[ERROR]   location: variable x of type com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlCreateTableStatement
[ERROR] /weiqu/otter-master/node/etl/src/main/java/com/alibaba/otter/node/etl/common/db/utils/DdlUtils.java:[158,75] cannot find symbol
[ERROR]   symbol:   method entrySet()
[ERROR]   location: interface java.util.List<com.alibaba.druid.sql.ast.statement.SQLAssignItem>
[ERROR] /weiqu/otter-master/node/etl/src/main/java/com/alibaba/otter/node/etl/common/db/utils/DdlUtils.java:[239,75] cannot find symbol
[ERROR]   symbol:   method entrySet()
[ERROR]   location: interface java.util.List<com.alibaba.druid.sql.ast.statement.SQLAssignItem>
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :node.etl
````

**Comment by xdkaka** [comment]
> > druid版本问题，canal 1.1.5中druid版本为1.2.6，otter中被改为了1.1.9导致的问题 个人处理：把版本改为1.2.6，otter中node.etl保留1.1.9
> 
> 我换了好多druid版本，没想到是canal的对不上


求助大佬要怎么改呢？
不会JAVA，直接改的pom.xml 里的版本号，打包的时候报错：
````
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project node.etl: Compilation failure: Compilation failure:
[ERROR] /weiqu/otter-master/node/etl/src/main/java/com/alibaba/otter/node/etl/common/db/utils/DdlUtils.java:[130,18] cannot find symbol
[ERROR]   symbol:   method isIfNotExiists()
[ERROR]   location: variable x of type com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlCreateTableStatement
[ERROR] /weiqu/otter-master/node/etl/src/main/java/com/alibaba/otter/node/etl/common/db/utils/DdlUtils.java:[158,75] cannot find symbol
[ERROR]   symbol:   method entrySet()
[ERROR]   location: interface java.util.List<com.alibaba.druid.sql.ast.statement.SQLAssignItem>
[ERROR] /weiqu/otter-master/node/etl/src/main/java/com/alibaba/otter/node/etl/common/db/utils/DdlUtils.java:[239,75] cannot find symbol
[ERROR]   symbol:   method entrySet()
[ERROR]   location: interface java.util.List<com.alibaba.druid.sql.ast.statement.SQLAssignItem>
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :node.etl
````

**Comment by whhe** [comment]
> druid版本问题，canal 1.1.5中druid版本为1.2.6，otter中被改为了1.1.9导致的问题
> 
> 个人处理：把版本改为1.2.6，otter中node.etl保留1.1.9

对于这个修复可否提一个pull request？

**Comment by Yangself666** [comment]
> 

这里是druid修改了方法，需要改这些

```java
// 130行
if (x.isIfNotExiists()) {
                print0(ucase ? "IF NOT EXISTS " : "if not exists ");
}
// 改成（拼写错误）
if (x.isIfNotExists()) {
            print0(ucase ? "IF NOT EXISTS " : "if not exists ");
}
```

```java
// 158行 239行
            for (Map.Entry<String, SQLObject> option : x.getTableOptions().entrySet()) {
                String key = option.getKey();
// 改成（方法改变）
 for (SQLAssignItem option : x.getTableOptions()) {
                String key = ((SQLIdentifierExpr) option.getTarget()).getName();
```

**Comment by guilinonline** [comment]
最新的代码还是有这个问题，我试了一下，解决不了，哪位大侠给讲讲具体要咋弄才能解决这个问题

**Comment by lee-cq** [comment]
> > @xdkaka
> 
> 这里是druid修改了方法，需要改这些
> 
> ```java
> // 130行
> if (x.isIfNotExiists()) {
>             print0(ucase ? "IF NOT EXISTS " : "if not exists ");
> }
> // 改成（拼写错误）
> if (x.isIfNotExists()) {
>             print0(ucase ? "IF NOT EXISTS " : "if not exists ");
> }
> ```
> 
> ```java
> // 158行 239行
> for (Map.Entry<String, SQLObject> option : x.getTableOptions().entrySet()) {
>                 String key = option.getKey();
> ...
> // 改成（方法改变）
>  for (SQLAssignItem option : x.getTableOptions()) {
>                 String key = ((SQLIdentifierExpr) option.getTarget()).getName();
> ...
> ```

使用大佬的方法需要注意两点：
1. 文件位置： node/etl/src/main/java/com/alibaba/otter/node/etl/common/db/utils/DdlUtils.java
2. 需要 import com.alibaba.druid.sql.ast.statement.SQLAssignItem;

**Comment by quanllong** [comment]
总结一下2个步骤，亲测有效：
1、修改druid版本
otter项目最外层的pom文件，194行
`<version>1.1.9</version>` 改成 `<version>1.2.6</version>`
2、修改代码
楼上已经列出文件位置和改动点

**Comment by quanllong** [comment]
> > druid版本问题，canal 1.1.5中druid版本为1.2.6，otter中被改为了1.1.9导致的问题
> > 个人处理：把版本改为1.2.6，otter中node.etl保留1.1.9
> 
> 对于这个修复可否提一个pull request？

提了一个pull request，麻烦review下
