### ISSUE TITLE
doTwoPhase代码问题

### ISSUE THREAD

**Issue by ehomeshasha** [alibaba/otter#107]
请教一个问题，
doTwoPhase这个方法里面results.size()和totalRows.size()不一定完全相等，因为逻辑中会过滤空记录，这样可能会造成通知加载完成的位置窜位，代码位置在com.alibaba.otter.node.etl.load.loader.db.DbLoadAction 395和407行，谢谢

**Comment by agapple** [comment]
目前407行为空方法
