### ISSUE TITLE
官方的otter-all镜像貌似无法使用mysql8

### ISSUE THREAD

**Issue by navist2020** [alibaba/otter#1078]
我想在kubernetes中使用部署otter，目前在使用 canal/otter-all 这个镜像，对于mysql 5.7.35 来说，一切看起来并没有什么问题，但是mysql8不能正常同步数据。

在验证库连接，验证表的时候都正常，但是启动任务之后，并不能正常同步数据。

**Comment by whhe** [comment]
dockerhub 上的版本太老了，里面依赖的 canal 也比较老旧，没有支持 8.0。

**Comment by navist2020** [comment]
> dockerhub 上的版本太老了，里面依赖的 canal 也比较老旧，没有支持 8.0。

@whhe 感谢您的回复，使用现在最新的代码然后按照docker目录下面的方式打包出来的是否能支持mysql8呢？

**Comment by navist2020** [comment]
dockerhub上面的镜像好像已经是最新版本的代码版本了，自己编译好像也没用。
