### ISSUE TITLE
manager里node管理，节点（和manager不在一个机器上）启动后查看node信息报错

### ISSUE THREAD

**Issue by wilsonwsong** [alibaba/otter#108]
com.alibaba.otter.manager.biz.common.exceptions.ManagerException: java.rmi.NoSuchObjectException: no such object in table

**Comment by HashZhang** [comment]
你看看ZK是否配置正常，重新加载ZK参数

**Comment by agapple** [comment]
看起来是manager调用node的RMI接口报错，尝试重启一次manager再试试
