### ISSUE TITLE
sql语义合并的潜在风险

### ISSUE THREAD

**Issue by melonboy312** [alibaba/otter#109]
我们在项目中使用了DbLoadAction.java和相关代码，主要是用于入库的sql语义合并。测试时发现这样一个case出现问题：
1.insert一条记录
2.delete这条记录并立刻再insert同一id的记录

这样操作后，从库中的记录还是第一次insert的记录。原因是第二步操作的delete和insert被合并了，因此直接执行了insert，但因为id冲突，所以没有执行成功。

当然，线上一般没有这样的sql，不过这是个潜在的风险。

**Comment by agapple** [comment]
otter针对insert，默认会执行merge sql，针对有pk约束冲突的，第二次的insert会变为update，将当前insert的最新值更新到db中，结果最终还是一致的.

主要考虑原始表中有A,B两条记录，其中有唯一约束a,b两列，现在想交换一下两者位置，一般做法是：update a -> c , update b->a , update c-> b, 因为并行导入顺序不确定性，update会出现乱序，出现约束冲突，规避的办法： delete a ,  delete b , insert b , insert a.  otter会优先确保delete优先于insert执行，insert优先于update执行
