### ISSUE TITLE
update+insert合并在pk被update时存在语义问题？

### ISSUE THREAD

**Issue by melonboy312** [alibaba/otter#110]
主库执行：insert into person values(1, 'houlei', 'test3', '2005-09-09', 'false'); 

数据同步完成后，执行： 
UPDATE person set id=2 where id=1; 
insert into person values(1, '2222', 'test3', '2005-09-09', 'false'); 

主库数据为： 
1	2222	test3	2005-09-09	false 
2	houlei	test3	2005-09-09	false 

从库数据为： 
2	houlei	test3	2005-09-09	false

**Comment by agapple** [comment]
类似主键或者唯一键约束变更，update请直接变更为delete+insert.  因为同一记录并发的特性，顺序问题会导致这样的结果不保证.
