### ISSUE TITLE
EventData的clone方法永远返回null？

### ISSUE THREAD

**Issue by melonboy312** [alibaba/otter#111]
代码如下：
   public EventData clone() {
        EventData data = new EventData();
        data.setTableId(tableId);
        data.setTableName(tableName);
        data.setSchemaName(schemaName);
        data.setDdlSchemaName(ddlSchemaName);
        data.setEventType(eventType);
        data.setExecuteTime(executeTime);
        data.setKeys(cloneColumn(keys));
        data.setColumns(cloneColumn(columns));
        data.setOldKeys(cloneColumn(oldKeys));
        data.setSize(size);
        data.setPairId(pairId);
        data.setSql(sql);
        data.setSyncMode(syncMode);
        data.setSyncConsistency(syncConsistency);
        data.setRemedy(remedy);
        data.setHint(hint);
        data.setWithoutSchema(withoutSchema);
        return null;
    }

**Comment by agapple** [comment]
clone方法一直未使用，已修复
