### ISSUE TITLE
otter能支持XA事务吗

### ISSUE THREAD

**Issue by cht19463** [alibaba/otter#1120]
![图片](https://github.com/alibaba/otter/assets/58391896/c7cf3b91-a1fb-48e1-8750-b85587718afb)

**Comment by zhangever** [comment]
应该说是否支持xa，是canal的职责而不是otter的职责，可以参考下:
https://github.com/zhangever/canal/tree/v1.1.4-xa-rollback-support

**Comment by l-s-c** [comment]
其实是不支持的，binlog内会有这样的语句，导致无法处理；
需要改一下报错处的源码，忽略 xa_commit ，xa_rollback

**Comment by czxin788** [comment]
> 其实是不支持的，binlog内会有这样的语句，导致无法处理； 需要改一下报错处的源码，忽略 xa_commit ，xa_rollback

请问怎么改，不懂java
