### ISSUE TITLE
删除主键上的唯一键，报错

### ISSUE THREAD

**Issue by xiejiaguang** [alibaba/otter#113]
otter 版本：V4.2.12
问个问题： 列 id 上，有主键：primary key (id)   ,又有一个唯一键 ：unique key id (id)，我删了唯一键 alter table 表  drop index id，然后 channel就挂起了，我在管道pipline处，更改高级特性 跳过 ddl 异常， 但还是挂起，该怎么改呢? 
错误信息：
pid:4 nid:2 exception:setl:com.alibaba.otter.node.etl.transform.exception.TransformException: no support ddl for

**Comment by agapple** [comment]
可以关闭ddl同步
