### ISSUE TITLE
NoSQL 分布式数据库集群扩展问题

### ISSUE THREAD

**Issue by FS1360472174** [alibaba/otter#119]
你好，有个分布式数据库问题想请教下。

业务背景：
为多个组织提供服务，组织间业务独立。单个组织用户，业务量可预见。
组织数目在不断增长。

目前想法是：
多个custer 来解决，组织数量增长，目前custer 不能满足，就扩展custer，而不是去扩展Node.
之所以选择不去扩展Node，是单集群，多个Node难以管理。以及增加node存在上限问题。

但目前面临着问题
1.应用程序如何来确定需要访问哪个Cluster,multi-cluster 的环境如何配置

单个Cluster 配置是1个Load balance Server,4 DB Node Server。
有没有在集群层配置一个Load Server,来根据请求分发到具体的Cluster，然后Cluster 的Load Balance 将请求分发给具体的DB Node。
或者应用程序有这个请求映射解决方案。

目前使用的是NOSQL 数据库Cloudant.
想请教下你对此有没有相关的经验，能够分享下。

非常感谢！

**Comment by agapple** [comment]
抱歉，不了解Cloudant，无法给出评价
