### ISSUE TITLE
AbstractEventProcessor 继承类里，自定义一个数据库连接，Statement.close()函数报错

### ISSUE THREAD

**Issue by MarkHsiu** [alibaba/otter#120]
自定义一个继承
com.alibaba.otter.node.extend.processor.AbstractEventProcessor
类的子类，在子类中新建了一个自己的数据库连接，在系统运行过程中
Statement.close()所在行，报空指针异常。去掉这行代码后，自定义数据库连接执行的sql插入没有效果。
why happen?

**Comment by agapple** [comment]
自己已解决了？

**Comment by MarkHsiu** [comment]
哈，我代码写错了。

2016-03-05 18:51 GMT+08:00, agapple <notifications@github.com>:
