### ISSUE TITLE
node log 提示  no support ddl for  drop table

### ISSUE THREAD

**Issue by MarkHsiu** [alibaba/otter#124]
表创建方式： sql执行语句创建，包含 drop table
操作时间：创建表后执行Channel任务，过很长时间后还是这样
问题：cannal还读取表的创建操作吗？还是说我的配置有问题？
 thinks the answer for someone

**Comment by agapple** [comment]
otter ddl同步不支持异构处理，库名、表名都要求一致

**Comment by MarkHsiu** [comment]
thinks
