### ISSUE TITLE
pipeline一直显示定位中

### ISSUE THREAD

**Issue by mrubbish** [alibaba/otter#126]
pipeline一直显示定位中，查看position 发现有乱码，其中的journalName 显示乱码，数据库用提是mariadb 10.1.10
{"@type":"com.alibaba.otter.canal.protocol.position.LogPosition","identity":{"slaveId":-1,"sourceAddress":{"address":"10.5.5.140","port":3306}},"postion":{"included":false,"journalName":"mysql-bin.000005(sÇ","position":28020,"timestamp":1458801931000}}

**Comment by agapple** [comment]
数据库binlog文件名建议修改为默认值，别用中文

**Comment by mrubbish** [comment]
binglog都是英文的，没有用到中文
-rw-rw---- 1 mysql mysql      25141 3月  17 11:06 mysql-bin.000001
-rw-rw---- 1 mysql mysql        346 3月  17 11:06 mysql-bin.000002
-rw-rw---- 1 mysql mysql       1474 3月  17 11:06 mysql-bin.000003
-rw-rw---- 1 mysql mysql        346 3月  17 11:06 mysql-bin.000004
-rw-rw---- 1 mysql mysql        346 3月  17 11:27 mysql-bin.000005
-rw-rw---- 1 mysql mysql     470570 3月  18 08:48 mysql-bin.000006
-rw-rw---- 1 mysql mysql        837 3月  18 09:46 mysql-bin.000007
-rw-rw---- 1 mysql mysql        346 3月  18 09:47 mysql-bin.000008
-rw-rw---- 1 mysql mysql        346 3月  18 09:48 mysql-bin.000009
-rw-rw---- 1 mysql mysql        346 3月  18 09:52 mysql-bin.000010
-rw-rw---- 1 mysql mysql        346 3月  18 09:52 mysql-bin.000011
-rw-rw---- 1 mysql mysql        346 3月  18 11:20 mysql-bin.000012
-rw-rw---- 1 mysql mysql        346 3月  18 11:20 mysql-bin.000013
-rw-rw---- 1 mysql mysql        370 3月  18 11:23 mysql-bin.000014
-rw-rw---- 1 mysql mysql        385 3月  18 12:36 mysql-bin.000015
-rw-rw---- 1 mysql mysql        346 3月  18 12:38 mysql-bin.000016
-rw-rw---- 1 mysql mysql        370 3月  18 12:40 mysql-bin.000017
-rw-rw---- 1 mysql mysql        385 3月  18 12:48 mysql-bin.000018
-rw-rw---- 1 mysql mysql        346 3月  18 12:50 mysql-bin.000019
-rw-rw---- 1 mysql mysql        370 3月  18 13:10 mysql-bin.000020
-rw-rw---- 1 mysql mysql        385 3月  18 13:28 mysql-bin.000021
-rw-rw---- 1 mysql mysql        346 3月  18 15:28 mysql-bin.000022
-rw-rw---- 1 mysql mysql        346 3月  18 15:31 mysql-bin.000023
-rw-rw---- 1 mysql mysql        346 3月  18 15:32 mysql-bin.000024
-rw-rw---- 1 mysql mysql        346 3月  24 09:21 mysql-bin.000025
-rw-rw---- 1 mysql mysql    7273550 3月  25 09:57 mysql-bin.000026
-rw-rw---- 1 mysql mysql        494 3月  24 09:22 mysql-bin.index

**Comment by agapple** [comment]
对应报错的binlog源文件
