### ISSUE TITLE
哪个大哥做了otter的docker哟？

### ISSUE THREAD

**Issue by wanjochan** [alibaba/otter#130]
共享下呗！

**Comment by sadk** [comment]
@wanjochan 找到了没？同求!

**Comment by wanjochan** [comment]
@sadk   还没呢，如果后面有收集到我就发上来，我只会做些简单镜像，otter还没研究好，所以还没资历自己制作。。。

**Comment by agapple** [comment]
制作了之后麻烦共享下吧

**Comment by dannyge** [comment]
https://github.com/dearplain/otter_manager/
https://github.com/dearplain/otter_node

**Comment by agapple** [comment]
https://github.com/alibaba/otter/wiki/Docker_QuickStart
