### ISSUE TITLE
node提取数据

### ISSUE THREAD

**Issue by szlaigithub** [alibaba/otter#131]
大拿，可以直接从node提出数据；注入三方库？

**Comment by agapple** [comment]
如果只是单纯提取数据请使用canal

**Comment by szlaigithub** [comment]
我们的案例是这样的，我们从异地将数据同步到本地的数据库；但是我们做了一个hbase，想用hbase从这个架构中的node直接取数据。其实本地可以是canal，只是我们想跳过这一步。直接从已有的架构中取得数据

**Comment by agapple** [comment]
暂时没有好的办法

**Comment by szlaigithub** [comment]
好的谢谢
