### ISSUE TITLE
otter编译报错，缺少jar

### ISSUE THREAD

**Issue by rongxuanhub** [alibaba/otter#133]
缺少如下几个jar文件，请问是什么原因，怎么解决啊？
fitnesse-20100211.jar

canal.inatance.manager-1.0.22-SNAPSHOT.jar
canal.parse.manager-1.0.22-SNAPSHOT.jar
canal.server.manager-1.0.22-SNAPSHOT.jar

**Comment by agapple** [comment]
优先编译canal项目：https://github.com/alibaba/canal

**Comment by rongxuanhub** [comment]
已经编译了，fitnesse-20100211.jar一直缺少

**Comment by agapple** [comment]
http://jtester.googlecode.com/svn/m2/ 这个仓库在墙外，可以使用otter/lib/ 下的install脚本安装到本地仓库
