### ISSUE TITLE
fitnesse-20100211.jar一直缺少

### ISSUE THREAD

**Issue by rongxuanhub** [alibaba/otter#134]

**Comment by agapple** [comment]
https://repo1.maven.org/maven2/org/fitnesse/fitnesse/20151230/fitnesse-20151230.pom， maven仓库有对应代码

**Comment by rongxuanhub** [comment]
没有找到2010的，我用的2011的代替，但是项目还是报错：
Failed to execute goal on project shared.common: Could not resolve dependencies for project com.alibaba.otter:shared.common:jar:4.2.13-SNAPSHOT: Failed to collect dependencies at org.jtester:jtester:jar:1.1.8 -> mockit:jmockit:jar:0.999.10: Failed to read artifact descriptor for mockit:jmockit:jar:0.999.10: Failure to find mockit:mockit:pom:0.999.10 in http://repo.bidlink.cn/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of bidlink has elapsed or updates are forced -> [Help 1]

**Comment by NishikinoMaki** [comment]
http://jtester.googlecode.com/svn/m2/ 这个仓库在墙外，可以使用otter/lib/ 下的install脚本安装到本地仓库

**Comment by Leviathans** [comment]
@rongxuanhub  请问你的问题解决了么？我这里一直提示jar缺少，无语了！

**Comment by rongxuanhub** [comment]
解决了，你是缺少什么jar？邮箱：641808979@qq.com

**Comment by Leviathans** [comment]
没有找到2010的，我用的2011的代替，但是项目还是报错：
Failed to execute goal on project shared.common: Could not resolve dependencies for project com.alibaba.otter:shared.common:jar:4.2.13-SNAPSHOT: Failed to collect dependencies at org.jtester:jtester:jar:1.1.8 -> mockit:jmockit:jar:0.999.10: Failed to read artifact descriptor for mockit:jmockit:jar:0.999.10: Failure to find mockit:mockit:pom:0.999.10 in http://repo.bidlink.cn/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of bidlink has elapsed or updates are forced -> [Help 1]

@rongxuanhub  请问这个问题你是怎么解决的？

**Comment by agapple** [comment]
我记得这些在otter/lib下都有的jar啊，使用install.sh插入到你本地maven仓库

**Comment by Leviathans** [comment]
执行过了，但是仍然报这个错误，崩溃，现在的情况貌似是源代码下载后 执行install脚本 网络也翻墙了，但是貌似没发编译成功！

**Comment by agapple** [comment]
mvn -o

**Comment by LinGoWei** [comment]
@Leviathans 我也遇到同样的问题，已经执行了/lib/install.sh，mockit/jmockit/0.999.10/jmockit-0.999.10.jar

**Comment by LinGoWei** [comment]
@agapple 
我也遇到同样的问题，
1、执行了/lib/install.sh
2、检查文件<mvn repository path>/mockit/jmockit/0.999.10/jmockit-0.999.10.jar存在
3、执行命令：mvn -o clean install -Dmaven.test.skip -Denv=release
4、报错：
Failed to execute goal on project shared.common: Could not resolve dependencies for project com.alibaba.otter:shared.common:jar:4.2.13-SNAPSHOT: Failed to collect dependencies at org.jtester:jtester:jar:1.1.8 -> mockit:jmockit:jar:0.999.10: Failed to read artifact descriptor for mockit:jmockit:jar:0.999.10: Cannot access hangzhou (http://mvn.vdian.net:8080/nexus/content/groups/public/) in offline mode and the artifact mockit:mockit:pom:0.999.10 has not been downloaded from it before. -> [Help 1]

**Comment by LinGoWei** [comment]
问题已排除，我的解决方法是：
1、打开org/jtester/jtester/1.1.8/jtester-1.1.8.pom
2、修改 jmockit 的依赖，把
`		<dependency>
			<groupId>mockit</groupId>
			<artifactId>jmockit</artifactId>
			<version>0.999.10</version>
		</dependency>
`
修改为：
`
		<dependency>
			<groupId>com.googlecode.jmockit</groupId>
			<artifactId>jmockit</artifactId>
			<version>0.999.11</version>
		</dependency>
`

**Comment by sumpan** [comment]
http://download.csdn.net/download/mlw519/8468087
这个地方有jtester，下载之后，直接放到.m2/repository/org/jtester/jtester/1.1.8/目录下面，然后重新编译。

**Comment by chenchangqun** [comment]
已经解决,原因是fitnesse-20100211.jar和jmockit依赖的mock-0.999.10.jar无法下载
1.otter/lib下有jar，使用install.sh插入到你本地maven仓库
2,修改本地maven资源库中的jtester pom依赖配置，路径为\org\jtester\jtester\1.1.8\jtester-1.1.8.pom


`<dependency>
<groupId>org.fitnesse</groupId>
<artifactId>fitnesse</artifactId>
<version>20130530</version>
</dependency>
<dependency>
<groupId>mockit</groupId>
<artifactId>jmockit</artifactId>
<version>0.999.1</version>
</dependency>`

**Comment by zvrr** [comment]
依赖配置修改成什么？

**Comment by 80port** [comment]
晕死，jtester 1.1.8 依赖 jmockit  0.999.10，这个又依赖mockit  0.999.10（注意是**mockit**），lib目录给了jmockit  0.999.10但是没有给mockit  0.999.10，一个测试用的基本过时的包使整个项目都编译不了，醉了，同意楼上chenchangqun 的方案是可行

**Comment by Saintchi** [comment]
我的问题是fitnesse
```XML
<version>20111025</version>
```
修改为：20190224，因为我本地maven仓库只有20190224这个版本号。
