### ISSUE TITLE
otter canal yugong三者选取问题

### ISSUE THREAD

**Issue by willin** [alibaba/otter#136]
使用场景：

多个异地服务器，包括中国、美国、新加坡、法兰克福等，部分用的是阿里云RDS。为了保证服务的全球化可用，之前做法是触发器、增量同步。

缺点：
1. 实时性比较差
2. 主键冲突导致的数据一致性得不到保证，而且还可能会导致同步失效

目标：
1. 双向同步
2. 实时

感觉canal就目前而言似乎是可以满足需求，但是想深入了解一下这三者的区别，以及有这么几个疑问：
1. 部署的时候，是每个区域都需要，还是只要在一个区域即可？
2. 我看在yugong的介绍目标是支持MySQL和DRDS，那么RDS是不能支持的吗？
3. 实时性怎么样，是否依赖网络环境？
4. 数据库之间的数据冲突（如主键）怎么解决？

最后，求推荐。

**Comment by agapple** [comment]
https://github.com/alibaba/otter/wiki/Faq , 先把wiki看一遍

**Comment by willin** [comment]
看过的，下面这张图上的node是数据库的意思？
![image](https://cloud.githubusercontent.com/assets/1890238/14840117/8406a636-0c63-11e6-8867-4b01a983a2aa.png)

描述一下刚才的问题
1. 上图也有部署美国、杭州两个区域，这是一对一同步的部署，如果是多个区域，每个区域都需要部署？
2. 我提交了工单问过，答复为RDS的binlog日志不支持订阅，是不是意味着canal、otter都不可以同步RDS数据库
3和4无补充

**Comment by agapple** [comment]
canal目前对RDS支持不够友好

**Comment by shopshow** [comment]
实际上RDS支持度还是不错的，我们现在就是中美双A，阿里云RDS，部署半个月来，没有出过问题

**Comment by agapple** [comment]
现在的版本对于RDS支持有优化
