### ISSUE TITLE
自己打包的没有上传canal同步位点信息，急求解决

### ISSUE THREAD

**Issue by fei348926326** [alibaba/otter#137]
自己下载了4.2.13和4.2.12版本的源码，用以下命令打包
mvn clean install -Dmaven.test.skip -Denv=release
之后发布的程序，没有上传同步位点信息到zookeeper。
如果把包换成提供的包则正常。
position 状态 :   无信息

**Comment by agapple** [comment]
客户端环境问题，没有拿到符合条件的binlog

**Comment by dcdebug** [comment]
那个这个问题如何解决呢？我的也是显示这个情况，而且对于客户端的设置也是Row 格式，但是就是一直显示为：mainstem 状态为工作中， position状态为无信息;

**Comment by fei348926326** [comment]
首先检查你的配置，其次检查你的程序，再次检查是否有包冲突
