### ISSUE TITLE
日志解析出错：CanalParseException: Unsupported BinlogFormat STATEMENT

### ISSUE THREAD

**Issue by Hinsteny** [alibaba/otter#139]
`pid:1 nid:1 exception:canal:canalTest:com.alibaba.otter.canal.parse.exception.CanalParseException: Unsupported BinlogFormat STATEMENT`

![qq 20160502151427](https://cloud.githubusercontent.com/assets/5526657/14949018/d12bad94-1078-11e6-96f1-ab6e468584dd.png)

**Comment by agapple** [comment]
otter要求binlog模式一定为ROW模式

**Comment by Hinsteny** [comment]
我设置的源数据库是位于windows上的，对于开启它的bin-log，是在安装的过程中选中设置的，没有找到具体模式设置的位置。
有个问题就是，如果只是从源到目标的同步任务，不开启的目标数据源的bin-log，是否也会出现这个异常信息呢？因为我的目标数据库是出于linux系统，但是没开启bin-log。

**Comment by agapple** [comment]
要求源库开启binlog，并且设置binlog-format为ROW模式，windows机器请自行搜索下如何配置吧

**Comment by Hinsteny** [comment]
嗯，找到了
位于：ProgramData\MySQL\MySQL Server 5.5
同样添加
`log-bin=mysql-bin

binlog-format=ROW`
