### ISSUE TITLE
陷入死循环

### ISSUE THREAD

**Issue by chengyoucai** [alibaba/otter#141]
一次性插入100w的数据，一个select node，一个load node。
发现select node的节点没有停止，同时日志不停地循环打印，两个日志文件row_select.log和3.log
row_select.log：
下面5组相同的数据不停的取出。
****************************************************
* Batch Id: [569] ,total : [759] , normal : [25,319] , filter :[-24,560] , Time : 2016-05-11 20:13:34:165
* Start : [mysql-bin.000055:466211829:1462959916000(2016-05-11 17:45:16)]
* End : [mysql-bin.000055:472353902:1462959916000(2016-05-11 17:45:16)]
****************************************************

****************************************************
* Batch Id: [570] ,total : [761] , normal : [23,538] , filter :[-22,777] , Time : 2016-05-11 20:14:16:506
* Start : [mysql-bin.000055:441613948:1462959916000(2016-05-11 17:45:16)]
* End : [mysql-bin.000055:447756963:1462959916000(2016-05-11 17:45:16)]
****************************************************

****************************************************
* Batch Id: [571] ,total : [761] , normal : [23,305] , filter :[-22,544] , Time : 2016-05-11 20:14:18:806
* Start : [mysql-bin.000055:447764986:1462959916000(2016-05-11 17:45:16)]
* End : [mysql-bin.000055:453907662:1462959916000(2016-05-11 17:45:16)]
****************************************************

****************************************************
* Batch Id: [572] ,total : [760] , normal : [24,230] , filter :[-23,470] , Time : 2016-05-11 20:14:21:138
* Start : [mysql-bin.000055:453915663:1462959916000(2016-05-11 17:45:16)]
* End : [mysql-bin.000055:460053042:1462959916000(2016-05-11 17:45:16)]
****************************************************

****************************************************
* Batch Id: [573] ,total : [759] , normal : [25,569] , filter :[-24,810] , Time : 2016-05-11 20:14:32:864
* Start : [mysql-bin.000055:460061071:1462959916000(2016-05-11 17:45:16)]
* End : [mysql-bin.000055:466203680:1462959916000(2016-05-11 17:45:16)]
****************************************************

3.log的日志。
不停的抛出警告：
2016-05-11 20:11:15.208 [pipelineId = 3,taskName = ProcessSelect] WARN  com.alibaba.otter.node.etl.select.SelectTask - rollback happend , should skip this data and get new message.

似乎陷入了死循环。

**Comment by agapple** [comment]
看下wiki，是否为监控导致重启任务

**Comment by chengyoucai** [comment]
未进行任何干预，花费了3-4个小时数据全部完成。只要数据量一大，就很大机会出现相似问题。
如果将100w数据分成10个10w的事务，没再出现同样问题。
对比wiki，并没有设置Position超时监控，错误日志也没有Position超时错误，但错误现象比较像，这个监控是有默认的吗？

**Comment by chengyoucai** [comment]
重试多次后，没有复现。暂时关闭。
