### ISSUE TITLE
请教：跨机房节点同步问题（NAT方式）

### ISSUE THREAD

**Issue by wing731** [alibaba/otter#145]
跨机房节点同步问题（NAT方式）

网络结构：
- A机房：
         主DB：10.0.0.1:3306
         node1(S+E）: 10.0.0.2/123.123.123.1: 2088-2090

- B机房：
         从DB: 192.0.0.2:3306
         manager: 192.0.0.3:1099
         node2(T+L): 192.0.0.4:2088-2090
         防火墙:  192.0.0.1/111.111.111.111
                   NAT策略：
                           111.111.111.111:3306-->192.0.0.2:3306（从DB）
                           111.111.111.111:1099->192.0.0.3:1099（manager）
                           111.111.111.111:2088-2090->192.0.0.4:2088-2090（node2）

在这个网络结构下，遇到2个问题：
- node2的ip不知道如何配置？
    如果node2配置启用外网IP 111.111.111.111，node1能正常访问node2的2088-2090，但manager也同样变成通过111.111.111.111访问node2的2088-2090，但因为在同一个nat下，结果manager无法访问node2，channel无法启动。
    如果node2配置不启用外网IP，则mananger能访问node2，但node1却不能访问，因为node1会以192.0.0.4:2088去访问node2。

- 如何配置能实现在数据同步过程中避免跨机房访问DB？
    我希望能实现各个机房的DB都隐藏在node背后，node不需要跨机房访问DB。例如：node1为select，S和E步骤由node1访问同机房的主DB，然后node1将数据同步到node2，node2为load，T和L步骤由node2进行，由node2将数据同步到同机房的从DB。
     目前我按照node1为selete，node2为load设置，node1仍然会去访问从DB，这个要怎么设置才可以呢？

**Comment by wing731** [comment]
@agapple 不知道我这2个问题，有方案解决吗？

**Comment by agapple** [comment]
我不太懂网络nat问题，建议找下网络管理同学

**Comment by wing731** [comment]
这个不是网络nat的问题。。。。

2016-05-19 10:10 GMT+08:00 agapple <notifications@github.com>:

**Comment by wing731** [comment]
这个不是网络nat的问题，是如何获取指定ip的问题。即同一机房节点使用内网ip访问，跨机房的节点使用外网ip范围。而不是单选，不管是同一个机房还是跨机房，只要选了使用外网IP，就全部连外网IP
或者是否可以支持，如果node同时配了内网ip和外网ip，当尝试内网ip无法连的时候，去尝试使用外网ip进行连接。

**Comment by agapple** [comment]
两者只能选其一
