### ISSUE TITLE
no support ddl

### ISSUE THREAD

**Issue by qingcaoyushui** [alibaba/otter#148]
pid:3 nid:7 exception:setl:com.alibaba.otter.node.etl.transform.exception.TransformException: no support ddl for [mysql_src.t_s] to [mysql_des.t_s] , sql :CREATE TABLE `t_s` ( 
`sid` varchar(50) NOT NULL , 
`sname` varchar(100) NULL , 
PRIMARY KEY (`sid`) 
) 

这个异常怎么解决， 源数据库创建一张表后就挂了

**Comment by agapple** [comment]
翻一下历史issue和wiki，DDL只支持源和目标完全一致，包括库名和表名

**Comment by qingcaoyushui** [comment]
哦，明白了， 谢谢
