### ISSUE TITLE
批量添加映射关系表单中的sourceId1,sourceId2到底是数据源的名称还是数据源的名称还是其他什么意思？

### ISSUE THREAD

**Issue by nickfan** [alibaba/otter#149]
批量添加映射关系表单中的sourceId1,sourceId2到底是数据源的名称还是数据源的名称还是其他什么意思？

我用：
```
multichannel,MYTABLE,mysrc0,mydst0,loadWeight
```
系统老是报：
***批量导入失败，请检查配置文档，可能原因:文档字段缺失或者sourceId不存在***

或者序号尝试都不成功：
```
multichannel,MYTABLE,1,2,loadWeight
```
不知道该如何填写？
sourceId1,sourceId2 这个在文档里貌似也找不到说明。

**Comment by agapple** [comment]
这是一个数据源的id序号
