### ISSUE TITLE
otter报警支持下邮件通知

### ISSUE THREAD

**Issue by agapple** [alibaba/otter#15]
支持下邮件报警.  

可通过设置otter.properties进行邮件发送：
otter.manager.monitor.email.host = smtp.gmail.com
otter.manager.monitor.email.username =  xxxx
otter.manager.monitor.email.password =   xxxx
otter.manager.monitor.email.stmp.port = 465

**Comment by qq297110281** [comment]
为啥节点挂了都没发告警邮件呢？？？？？位点超时倒是发了，但是节点挂了都没告警。。。。。。。。。
