### ISSUE TITLE
pid:-1 nid:null exception:cid:1 restart recovery successful for rid:-1

### ISSUE THREAD

**Issue by nickfan** [alibaba/otter#150]
刚启动服务的时候，后台manager日志会报这个异常：

```
pid:-1 nid:null exception:cid:1 restart recovery successful for rid:-1
```

**正常现象么？还是说需要做些什么？**

**Comment by KaimingWan** [comment]
我也碰到这样的情况，作者 wiki里面说：该异常代表channelId = 2，成功发起了一次restart同步任务的操作。 不知道算不算正常~

**Comment by agapple** [comment]
看下FAQ，自动恢复是针对出现node节点不可用，监控发现问题等做的一个自我恢复的尝试，如果是偶发触发一次可以忽略，如果是频繁出现，得找找系统上是否存在一些问题，导致频繁同步失败

**Comment by fg-meizhi** [comment]
我的日志是
`pid:-1 nid:null exception:cid:1 stop recovery successful for rid:2`
和
`pid:-1 nid:null exception:cid:1 restart recovery successful for rid:-1`
交替出现的，间隔几分钟出现一次

**Comment by agapple** [comment]
看我LS的回复

**Comment by fg-meizhi** [comment]
我的两台 node 机器分别在北京和广州，普通办公网络，北京联通，广州电信（网络确实很差，速度最大100k）， Manager 和 zookeeper 在阿里云，load  node 在接收数据 batchdata***.gzip，一个批次几个数据包大小不同，从3M 到15M，大一点的数据包通过 aria2c 接收有时还没有下载完就超时了。
是否一个批次的数据包，有一个下载失败会导致整个任务失败？

**Comment by agapple** [comment]
调大下process超时监控的阀值

在 2016年7月11日 下午3:54，fg-meizhi <notifications@github.com>写道：
