### ISSUE TITLE
用otter同步AWS上的RDS库到阿里云的RDS的问题。

### ISSUE THREAD

**Issue by jsrgqinbin** [alibaba/otter#153]
![image](https://cloud.githubusercontent.com/assets/234215/16108763/c00b03c0-33d7-11e6-882e-6881189f0b93.png)

如上图，同步的延迟都是半小时左右。。。。

有人在这样操作？也是这样的问题？或者怎么解决？

**Comment by jsrgqinbin** [comment]
pid:1 position 705 seconds no update


日志里报这个


到库上去看bin-log日志是一直在添加

| mysql-bin-changelog.089001 | 282311021 |
| mysql-bin-changelog.089002 |    194045 |
| mysql-bin-changelog.089003 |  11817069 |
| mysql-bin-changelog.089004 |  13926151 |
| mysql-bin-changelog.089005 |   9343768 |
| mysql-bin-changelog.089006 |   5194620 |
| mysql-bin-changelog.089007 |   2790886 |
| mysql-bin-changelog.089008 |   5988335 |
| mysql-bin-changelog.089009 |   3446306 |
| mysql-bin-changelog.089010 |   2579138 |
| mysql-bin-changelog.089011 |   3666665 |
| mysql-bin-changelog.089012 |   3183284 |
| mysql-bin-changelog.089013 |   4434845 |
| mysql-bin-changelog.089014 |   3513325 |
| mysql-bin-changelog.089015 |   9457217 |
| mysql-bin-changelog.089016 |   9538761 |
| mysql-bin-changelog.089017 |   4961103 |
| mysql-bin-changelog.089018 |   4779892 |
| mysql-bin-changelog.089019 |   3231432 |
| mysql-bin-changelog.089020 |   5687928 |
| mysql-bin-changelog.089021 |   4058870 |
| mysql-bin-changelog.089022 |  11367294 |
| mysql-bin-changelog.089023 |   3489280 |
| mysql-bin-changelog.089024 | 283975749 |
| mysql-bin-changelog.089025 |   1269484 |
| mysql-bin-changelog.089026 |   1577535 |
| mysql-bin-changelog.089027 |   3174393 |
| mysql-bin-changelog.089028 |   1682512 |
| mysql-bin-changelog.089029 |   1660095 |
| mysql-bin-changelog.089030 |   2786541 |
| mysql-bin-changelog.089031 |   1202892 |
| mysql-bin-changelog.089032 |   1465097 |
| mysql-bin-changelog.089033 |   1583438 |
+----------------------------+-----------+

Position的位置如下：

{"@type":"com.alibaba.otter.canal.protocol.position.LogPosition","identity":{"slaveId":-1,"sourceAddress":{"address":"52.68.25.216","port":3306}},"postion":{"included":false,"journalName":"mysql-bin-changelog.089024","position":1872658,"timestamp":1466059690000}}

**Comment by jsrgqinbin** [comment]
主库上的bin-log位置的具体信息如下

mysql> SHOW BINLOG EVENTS in 'mysql-bin-changelog.089024' from 1872658 limit 100;
+----------------------------+---------+-------------+-----------+-------------+------------------------------------------------------+
| Log_name                   | Pos     | Event_type  | Server_id | End_log_pos | Info                                                 |
+----------------------------+---------+-------------+-----------+-------------+------------------------------------------------------+
| mysql-bin-changelog.089024 | 1872658 | Xid         | 401518573 |     1872689 | COMMIT /* xid=41141968 */                            |
| mysql-bin-changelog.089024 | 1872689 | Query       | 401518573 |     1872769 | BEGIN                                                |
| mysql-bin-changelog.089024 | 1872769 | Table_map   | 401518573 |     1872865 | table_id: 108 (multichannel.AMAZON_PRODUCT_CATEGORY) |
| mysql-bin-changelog.089024 | 1872865 | Update_rows | 401518573 |     1873195 | table_id: 108 flags: STMT_END_F                      |
| mysql-bin-changelog.089024 | 1873195 | Xid         | 401518573 |     1873226 | COMMIT /* xid=41141964 */                            |

**Comment by jsrgqinbin** [comment]
![image](https://cloud.githubusercontent.com/assets/234215/16112536/52c6f3c4-33ea-11e6-923f-e08bff0a6823.png)

上图是日志的内容

**Comment by KaimingWan** [comment]
首先这个manager的日志信息出现是正常的，因为长时间没有捕获到日志变更，默认是10分钟吧。所以会有这个日志信息，你也可以关闭该功能。你现在的情况就是有数据变更 但是没有捕获到，你看看表映射是不是都配好了，相关的表是否都能访问，用户是否有访问表的权限。这是我的理解，你试试看哈~

**Comment by agapple** [comment]
LS同学理解正确

**Comment by emperorente** [comment]
请问aws的rds和aliyun的rds走的公网么？

**Comment by agapple** [comment]
可以使用最新版otter来解决，升级了canal
