### ISSUE TITLE
延迟时间一直上升，但是同步进度并没有滞后

### ISSUE THREAD

**Issue by imlazyone** [alibaba/otter#154]
在 Channel 的 **同步进度** 菜单里，同步一直在进行中，binlog 并没有出现滞后的现象，一直是在最新的 binlog 上。但是 **延迟时间** 菜单却一直上升，已经超过一天时间了。

Channel 信息：
![image](https://cloud.githubusercontent.com/assets/1668944/16182058/7e650268-36d4-11e6-96fe-6b7e708e146b.png)

延迟时间 截图：
![image](https://cloud.githubusercontent.com/assets/1668944/16182007/2b608f9c-36d4-11e6-829b-d500d1edcca4.png)

请问可能的原因是？

**Comment by agapple** [comment]
同步出现异常了吧，同步位点关注下是否有前进

**Comment by imlazyone** [comment]
找到原因了，因为设置的源站是一个 MySQL Slave，数组走向是：
```
Master A -> Slave A ---> otter ---> Master B
```

Slave A 上一直有长时间的 replication delay，Otter 应该是根据 node 机器上的本地时间和最后同步的 binlog 时间比对来显示延迟时间的，所以会有此问题。
