### ISSUE TITLE
监控管理报警不触发以及TPS统计信息不准确问题

### ISSUE THREAD

**Issue by KaimingWan** [alibaba/otter#155]
1.吞吐量统计异常
首先我不是很理解这个吞吐量的统计如何理解。这应该是实时的统计吧？TPS（1分钟）这一列的选项在我的实验中没有超过100。而实际上我根据历史吞吐量的统计信息手动计算记录数除以时间可以得到TPS都在3000左右

![temp1](https://cloud.githubusercontent.com/assets/4374015/16225667/6ad7e63c-37da-11e6-8c7a-0478a99e11bf.png)

2.报警系统不触发
设定了相关的报警监控，但是那个超时监控从来没触发。我在延迟时间那个统计信息看到的平均延迟有时候会在秒级，但是超时的报警里面的内容一直是空的

![temp2](https://cloud.githubusercontent.com/assets/4374015/16225760/d336a790-37da-11e6-9c76-a4b497dc6af4.png)

**Comment by agapple** [comment]
1. tps监控是1分钟的量，你按平均数计算应该是会有高峰和低峰吧
2. 超时监控你设置的是600秒呢

**Comment by KaimingWan** [comment]
1分钟的TPS量，是否指的是在这一分钟平均的TPS值为多少？如果该值为50，也就是说平均在一分钟有50条事务？我看历史吞吐量，把每条记录当做一个事务，插入100万条记录的话，整个平均的TPS应该有3000左右，但是那个每分钟统计的TPS从来不超过100。是不是该值还要乘以60啊？这样才是真正每分钟的TPS？

**Comment by agapple** [comment]
看下历史流量统计吧，那是以分钟为单位的
