### ISSUE TITLE
otter做同步时吞吐量如何提升？

### ISSUE THREAD

**Issue by KaimingWan** [alibaba/otter#156]
针对同机房的单个channel的同步任务，我采用了如下配置。由于对实时性要求不是很高，延迟在60s以内都可以接受，我采用了较大的batch size。对canal也配置了较大的buffer size来提升TPS。主要配置如下：

channel:
Channel序号：	1
Channel名字：	sync-student-table
同步方向：	单向
运行状态：	运行
同步一致性：	基于当前日志变更
同步模式：	行记录同步
是否开启数据一致性：	关闭

canal:
存储机制：	MEMORY
内存存储batch获取模式：	MEMSIZE
内存存储buffer记录数：	262144
内存存储buffer记录单元大小：	1024
HA机制：	HEARTBEAT
是否开启心跳：	false
meta机制：	MIXED
索引机制：	MEMORY_META_FAILBACK
服务端口：	11111
默认连接超时：	
接收BufferSize：	16384
发送BufferSize：	16384
切换回退时间：	60
过滤表达式：	

pipeline:
并行度：	5
数据反查线程数：	10
数据载入线程数：	15
文件载入线程数：	15
主站点：	false
同步数据来源：	Canal
Canal名字：	test-canal
主道消费批次大小：	90000
获取批次数据超时时间：	10000
描述信息：	
是否显示高级设置：	
使用batch：	true
跳过Select异常：	关闭
跳过Load异常：	关闭
仲裁器调度模式：	MEMORY
负载均衡算法：	Stick
传输模式：	自动选择
记录selector日志：	开启
记录selector详细日志：	开启
记录load日志：	开启
dryRun模式：	关闭
支持ddl同步：	开启
跳过ddl异常：	开启
文件重复同步对比：	关闭
文件传输加密：	关闭
启用公网同步：	关闭
跳过自由门数据：	关闭
跳过反查无记录数据：	关闭
启用数据表类型转化：	开启
兼容字段新增同步：	开启
自定义同步标记：	

当mysql采用1个connection的时候，mysql的TPS在3000左右，otter的同步的TPS也在3000左右，瓶颈在MYSQL；但是当mysql采用上百个连接访问时，mysql的TPS能破万了，但是otter同步的TPS仍然在3000左右；请问瓶颈在哪？如何提升？

**Comment by agapple** [comment]
同步模式： 行记录同步，换成字段同步
检查下目标mysql是否存在性能瓶颈

**Comment by KaimingWan** [comment]
看过了，确实是目标端的MYSQL 存在LOAD瓶颈，3Q~可以close了^_^

**Comment by zhangxn51** [comment]
求问，同步效率怎么调也上不去，由于搭建的环境有点复杂。
请教如何定位性能瓶颈
