### ISSUE TITLE
配置同步的时候，需要MYSQL的权限

### ISSUE THREAD

**Issue by fanchao916** [alibaba/otter#159]
配置同步的时候，需要MYSQL的权限是什么？看很多文档上 GRANT SELECT, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'canal'@'%';这样的权限就够了吗？

**Comment by agapple** [comment]
你这是canal的权限需求，如果是otter同步，需要对所需表的写入权限

**Comment by fanchao916** [comment]
那就是使用OTTER同步的时候，目的数据库的权限需要select,create,delete,insert.alter,create等等权限了啊？因为有数据的同步和表结构的修改，对吗？

**Comment by agapple** [comment]
是的
