### ISSUE TITLE
大量Binlog Dump线程堆积是什么问题

### ISSUE THREAD

**Issue by ninglianjie** [alibaba/otter#161]
![image](https://cloud.githubusercontent.com/assets/1515239/16408384/0d1c00b6-3d4b-11e6-8c32-74d439b936d7.png)

**Comment by agapple** [comment]
检查下对应的机器的tcp链接状态，是close_wait还是estblish状态？

**Comment by ninglianjie** [comment]
用alter改表时报错了，没有设置自动跳过异常DDL，设置后就正常了。
