### ISSUE TITLE
otter 同步异常- exception:setl:transform miss data with keys

### ISSUE THREAD

**Issue by EternalSpring** [alibaba/otter#164]
pid:3 nid:2 exception:setl:transform miss data with keys:[RpcPipeKey[nid=1,identity=Identity[channelId=2,pipelineId=3,processId=16063],time=1467618471020,dataType=DB_BATCH]] 

想请教下，这个bug是因为什么导致的？传输丢包？

**Comment by agapple** [comment]
翻一下https://github.com/alibaba/otter/wiki/Faq
