### ISSUE TITLE
双向同步过程中出现的问题

### ISSUE THREAD

**Issue by ch-lgs** [alibaba/otter#166]
配置A机房和B机房双向同步（B机房少量数据写入），A为trust source,出现A机房到B机房较为严重的超时，在延时降低的过程中A数据出现回归到已更新成功之前旧数据？请问这有可能是什么原因造成的呢？

**Comment by ch-lgs** [comment]
pid:2 nid:3 exception:setl:load miss data with keys:[MemoryPipeKey[identity=Identity[channelId=2,pipelineId=2,processId=14281213],time=1467701523657,dataType=DB_BATCH]]
pid:3 nid:4 exception:mainstem:pid:3 canal elapsed 174050 seconds no data

这几个exception比较频繁

**Comment by ch-lgs** [comment]
是否是因为A机房node频繁GC，导致B机房重新定位到老的日志点，将老数据同步到杭州机房造成的

**Comment by agapple** [comment]
从异常来看是因为GC导致临时内存对象数据丢弃，降低同步任务并行量试试
