### ISSUE TITLE
一致性的疑问

### ISSUE THREAD

**Issue by ch-lgs** [alibaba/otter#167]
请问在wiki中提到同步程序能保证数据的最终一致性，但是对于mysql ROW模式下双A模式下update语句（update set column＝column＋value或者update set column＝value）能否保证在有延时的情况下保证双机房数据操作的原子性，如A机房数据操作a-3，B机房数据操作a-3,otter能否保证两边数据最后一致保持a-6,而不是在最终一致性保证下使得两边数据保持a-3的最终一致性？

**Comment by agapple** [comment]
目前没有做a-6的一致性方案，这个要区分不同业务字段对于合并的处理
