### ISSUE TITLE
首次全量同步自由门相关问题

### ISSUE THREAD

**Issue by weikuo0506** [alibaba/otter#168]
线上的业务表和otter的系统表部署在不同的机器上（不同的数据库连接url），我往otter的系统表retl.retl_buffer中写入了需要同步的业务表数据，发现没有触发自由门全量同步。
请教下：是不是必须要求业务表和otter系统表在同一个机器上（同一个DB连接url）才能触发自由门？
开发环境我已经测试ok，唯一的不同就是线上的业务表和retl表在不同机器上而已。谢谢！

**Comment by agapple** [comment]
必须要在同一个机器上

在 2016年7月6日 下午5:12，weikuo0506 <notifications@github.com>写道：

**Comment by weikuo0506** [comment]
ok 多谢！
