### ISSUE TITLE
首次全量同步（自由门）优化问题

### ISSUE THREAD

**Issue by weikuo0506** [alibaba/otter#170]
根据之前问题：https://github.com/alibaba/otter/issues/168
目前首次触发全量同步，要求待同步的业务表和otter系统表必须在同一台机器上才可以，因为”需要从同一个db源上解析到binlog，然后回查对应的数据库“（引自jianghang115邮件回复）。然而实际情况是，业务表一般分散在多个机器上，这样的话就导致无法触发全量同步。
请问：有没有更改或优化的办法？比如，是否可以在retl_buffer表中增加DB连接URL字段，如DBURL，用于标识对应库名表名和主键所在的机器的DB连接；这种方案是否可行？修改难度如何？是否还有其他优化方案？或者其他用于触发首次全量同步的方案？
谢谢！

**Comment by agapple** [comment]
你可以按照你的理解，提交一个PR给我

**Comment by pan289091315** [comment]
@agapple 问一下，

- retl库中，全量同步自由门会使用到retl.retl_buffer，还有我看双向同步的双向回环算法也会用到retl.retl_mark。

- 我们现在想把这个retl的库单独部署到一个实例上，不和业务的同一个实例，所有业务共享一份retl库,能否实现？这样在实践中会不会有坑？

- 之前retl在某些同步场景（如，全量同步，双向同步）下必须在每个业务库中冗余的设计的初衷是为了什么？

**Comment by agapple** [comment]
不能单独部署retl库，因为retl库数据的获取是通过binlog增量，如果单独部署就需要拉两份增量数据了

**Comment by pan289091315** [comment]
@agapple ，这一块的实现具体在工程哪个地方能否指一下？我去看看?

**Comment by agapple** [comment]
FreedomExtractor类
