### ISSUE TITLE
pid:2 nid:1 exception:mainstem:pid:2 canal elapsed 115200 seconds no data

### ISSUE THREAD

**Issue by ch-lgs** [alibaba/otter#171]
请问这个异常的原因是什么，每隔一个多小时会报一次，似乎同步实际排查下来并没有什么问题

**Comment by ch-lgs** [comment]
pipline进行node1切换node2，已经切换成功但是node1间断性产生该报警

**Comment by agapple** [comment]
一段时间没有收到binlog，可以开启心跳检查SQL

**Comment by angelmm126** [comment]
pid:2 nid:1 exception:mainstem:pid:2 canal elapsed 115200 seconds no data，单向同步报此异常，求大神指点解决办法。
select与load  node是同一个，单向同步，偶尔会把报canal elapsed 50 seconds no data
