### ISSUE TITLE
canel自动把域名换成IP了

### ISSUE THREAD

**Issue by jsrgqinbin** [alibaba/otter#172]
![image](https://cloud.githubusercontent.com/assets/234215/16717436/c73199d2-4748-11e6-9097-510db0950858.png)

因为用的是AWS的RDS，所以给的连接地址是域名，添加到canel里自动转换为IP了，今天发现AWS的RDS域名对应的IP会变换，所以问下canel里能不能设置成域名啊。。。

求解救办法

**Comment by zhuer0632** [comment]
写域名会变成私有IP吧, 私有IP跟机器绑定的,重启不变.

**Comment by agapple** [comment]
这个应该是otter保存对象时自动转换为了ip

**Comment by tangcongzhen** [comment]
我也面临这个问题
