### ISSUE TITLE
otter目前存在的同步限制

### ISSUE THREAD

**Issue by szlaigithub** [alibaba/otter#173]
大大们，在otter目前存在的同步限制中能同步视图？

**Comment by dusonchen** [comment]
所有的Channel中的Pipeline配置中Select机器可以是同一个机器吗？按道理Load机器因为是具体执行的，所以要不同。但Select源的Bin-log应该所有都一样的。

**Comment by agapple** [comment]
1. otter的原理是基于数据库物理表binlog变更进行同步，视图是构建在物理表之上，理论上也是支持的
2. 没懂具体问题，机器可以随意选择，尽可能就近选择原则
