### ISSUE TITLE
请教个问题：不同Channel之间的Pipeline中的Select机器选择疑问

### ISSUE THREAD

**Issue by dusonchen** [alibaba/otter#181]
所有的Channel中的Pipeline配置中Select机器可以是同一个机器吗？按道理Load机器因为是具体执行的，所以要不同。但Select源的Bin-log应该所有都一样的。

**Comment by agapple** [comment]
select机器会只有一个node处于工作中

**Comment by dusonchen** [comment]
不同Channel的Pipeline中的Select机器可以是同一台机器吗？

**Comment by agapple** [comment]
可以的

**Comment by dusonchen** [comment]
答案是不行的：如果Event Processor：	为SOURCE时，会报错说相关的类找不到
