### ISSUE TITLE
WiKi上关于node高可用的实现思路

### ISSUE THREAD

**Issue by EternalSpring** [alibaba/otter#185]
群主，你好，想向您咨询下WiKi上关于“3. node节点监控原理”这一块的描述，在部署上是否为在同一个Master00库与Master01库双主之间需要部署两条并行的Channel，当其中一条Channel中的某个主机node宕机之后，可以通过仲裁将当前已停止Channel上的同步任务切换到另外一条Channel上呢？这种在开源版本中，数据一致性是否能得到保障？

**Comment by agapple** [comment]
可以在一个channel中，选择多个node保证高可用，一个node挂了可以漂移到另一个node上

**Comment by EternalSpring** [comment]
明白，Select机器与Load机器多选。

**Comment by EternalSpring** [comment]
群主，还有一点想请教下，关于manager的高可用，wiki上介绍“需要考虑manager failover(一台manager挂了，需要链接到另一台).” ，关于这点描述，想咨询下，如果不借助VIP、HA这种，仅仅靠配置otter能否实现manager的漂移呢？可以的话具体怎样实现？

**Comment by agapple** [comment]
node的配置文件里添加多个manager地址，一个挂了自动请求下一个manager

在 2016年8月10日 下午5:12，EternalSpring <notifications@github.com>写道：

**Comment by EternalSpring** [comment]
嗯嗯，看了代码，是通过建立连接来判断当前manager的可用性，如果部署两套manager+manager的mysql，中间搭建数据同步，mysql实例宕了以后，manager应该是可以建立连接的，但是服务不可用，node是否还有办法实现manager的切换？或者manager的数据源只连一套，在故障时才切换？

**Comment by agapple** [comment]
不是太理解你的问题，按照之前的考虑manager可以部署两个，但是链接的DB应该是一组主备实例，mysql的主备可以有多种策略来保证，当然你也可以利用otter来做同步，但是主备库的切换，manager用那个还是需要额外的控制来处理

**Comment by EternalSpring** [comment]
好的，可以manager01连MasterDB，manager02连MasterDB，另外搭一套SlaveDB，加个类似于MHA的高可用去漂，只不过想着有没办法manager01连MasterDB，manager02连SlaveDB，无论manager01主机宕还是MasterDB宕，node都可以顺利切换到manager02，以节省一些中间件架构。

**Comment by agapple** [comment]
那你这样会面临一个数据一致性问题，MasterDB和SlaveDB，解决好这个一致性问题就可以这么玩

**Comment by guanjunyou** [comment]
> 可以在一个channel中，选择多个node保证高可用，一个node挂了可以漂移到另一个node上

想请教一下，一个node挂了漂移到了一个node上，是不是会导致这个node上正在处理的 DbBatch 丢失？
