### ISSUE TITLE
Otter 可以设置跳过某些 DML 操作不进行同步吗?

### ISSUE THREAD

**Issue by theseusyang** [alibaba/otter#188]
Hi All:

目前 Otter 可以设置成跳过 DML 操作, 例如对 Delete or Update 不进行同步的设置吗？

谢谢!

**Comment by pan289091315** [comment]
@theseusyang  有的可以配置的，在pipeLine的可以配置对ddl是否处理，
![image](https://cloud.githubusercontent.com/assets/6639546/17962884/839da880-6ae5-11e6-83f7-9094c26a9496.png)，具体源代码的实现在MessageParse 里 internParse 方法，对EventType 进行和配置进行判断。

**Comment by theseusyang** [comment]
DDL 是对数据库、表、字段的增加和删除, 这个Option 也可以对具体 Delete or Update 的数据删除和更新进行支持么？

**Comment by theseusyang** [comment]
OK, 直接改源码, 控制 EventType 也是一个好办法

**Comment by pan289091315** [comment]
哦，那你可以写个扩展具体看otter wiki扩展那一章https://github.com/alibaba/otter/wiki/Otter%E6%89%A9%E5%B1%95%E6%80%A7，把不需要同步的语句返回false,就应该不会同步了。看源码好像是这样的，会加入removeDatas

**Comment by pan289091315** [comment]
哦，那你可以写个扩展具体看otter wiki扩展那一章，把不需要同步的语句返回false,就应该不会同步了。看源码好像是这样的，会加入removeDatas[扩展](https://github.com/alibaba/otter/wiki/Otter%E6%89%A9%E5%B1%95%E6%80%A7)

**Comment by theseusyang** [comment]
OK, 我试一下这个扩展功能
