### ISSUE TITLE
怎么添加源库数据表与目标库数据表的映射关系?

### ISSUE THREAD

**Issue by theseusyang** [alibaba/otter#189]
我在数据表配置中添加了很多源库的数据表与目标库的数据表, 但是Otter只有一个表做了映射, 很多其余的表都没有做映射.

在 Otter 平台上, 怎样添加源库数据表与目标库数据表的映射关系?
或者Otter 是自动进行映射的, 不需要人工修改?

谢谢!

**Comment by agapple** [comment]
看下wiki基本操作文档

**Comment by theseusyang** [comment]
嗯，多谢！看了一下，发现在 Otter pipeline 没启动时可以添加源数据表和目标数据表的映射关系，但pipeline启动之后不能够添加源数据表和目标数据表的映射关系，没有这个添加按钮。

**Comment by theseusyang** [comment]
也许可能 Otter 在 runtime 时禁止动态对表关系进行映射。

**Comment by agapple** [comment]
表映射需要任务停用启用才可以生效，所以做了运行中禁止变更
