### ISSUE TITLE
Otter 和 Cobar 可以无缝集成使用吗?

### ISSUE THREAD

**Issue by theseusyang** [alibaba/otter#192]
因为在具体业务中涉及到分库分表, 所以使用 Cobar 对 Mysql 进行分库分表.
Otter 同步数据到目标数据库(默认为 Mysql), 那么 Cobar 作为对端的数据库前端代理服务是否也可以?

谢谢!

**Comment by agapple** [comment]
目前支持不是很好，主要针对cobar这一类在同步update语句时需要带上拆分条件，目前otter只会带上主键

**Comment by theseusyang** [comment]
恩 我这边准备使用 sharding-jdbc 了, 貌似这东西做分库分表更好一些

2016-08-30 18:53 GMT+08:00 agapple <notifications@github.com>:
