### ISSUE TITLE
问题：Channel 的「启用」按钮变灰无法点击

### ISSUE THREAD

**Issue by imlazyone** [alibaba/otter#193]
<img width="1043" alt="screen shot 2016-08-30 at 2 37 32 pm" src="https://cloud.githubusercontent.com/assets/1668944/18079027/3f287ab0-6ec1-11e6-8fec-ccd25df4738a.png">

如图所示，今天在切换了传输模式 (HTTP/RPC) 之后保存，出现了这种情况：Channel 的「启用」按钮变成灰色无法点击了，用 Firebug 可以看到有文字提示：process里面还有同步数据

请问一下有没有人遇到过这种情况？应该如何处理？

**Comment by agapple** [comment]
点击推送，同步一下状态到各个机器

**Comment by imlazyone** [comment]
@agapple 谢谢。下午我 copy 了另外一个 Channel 的启用链接， 然后改了一下 channel ID，直接访问那个 URL，就启用成功了 😂  

类似这样：
```
http://xxx.com/?action=channelAction&channelId=1&status=start&pageIndex=1&searchKey=&eventSubmitDoStatus=true
```

虽然后来出现了几次挂起，但是最后 Channel 一直启用到了现在。

**Comment by JerryChin** [comment]
@imlazyone it works for me, but not sure if there are any pitfalls.
