### ISSUE TITLE
全量同步怎么配置啊？mysql-->oracle，单向同步。没成功过！谢谢

### ISSUE THREAD

**Issue by luoyaogui** [alibaba/otter#197]

**Comment by agapple** [comment]
描述具体的case

**Comment by luoyaogui** [comment]
比如
源库DB1.表T1，有a、b、c、d、e、f的数据，目标库DB2.表T2没有数据。现在想把所有的数据都旧数据、新增的数据都进行同步。这应该就是全量了吧。我按照文档中往retl.retl_buffer中插入了insert into retl.retl_buffer(TABLE_ID, FULL_NAME,TYPE,PK_DATA,GMT_CREATE,GMT_MODIFIED) (0,$DB1.T1$,'I',id,now(),now()); 或
insert into retl.retl_buffer(TABLE_ID, FULL_NAME,TYPE,PK_DATA,GMT_CREATE,GMT_MODIFIED) (0,DB1.T1,'I',id,now(),now());，开启同步也没有进行全量同步，只是执行了增量同步。谢谢解答~

**Comment by luoyaogui** [comment]
您在https://github.com/alibaba/otter/wiki/Manager%E9%85%8D%E7%BD%AE%E4%BB%8B%E7%BB%8D中的’全量同步操作示例‘描述，我有两个地方迷惑，一是insert into retl.retl_buffer(ID,TABLE_ID, FULL_NAME,TYPE,PK_DATA,GMT_CREATE,GMT_MODIFIED) (select null,0,'$schema.table$','I',id,now(),now() from $schema.table$);这个语句在源库中执行吧？二是$schema.table$这个是源库.源表还是目标库.目标表？谢谢解答~

**Comment by agapple** [comment]
源库的表

**Comment by luoyaogui** [comment]
哦，那我再试一试，谢谢

**Comment by luoyaogui** [comment]
谢谢，解决了！
