### ISSUE TITLE
如何在 manager 界面配置全量数据同步(自由门)的设置?

### ISSUE THREAD

**Issue by theseusyang** [alibaba/otter#198]
Hi,
如何在 manager 界面配置全量数据同步(自由门)的设置?
在文档中没看到详细的配置步骤.

谢谢

**Comment by agapple** [comment]
没有对应的页面操作，是操作业务db，产生数据变更binlog，触发otter处理数据同步

**Comment by theseusyang** [comment]
OK, 怎么个操作法, 具体是把业务 DB中所有的数据都update 一下?

**Comment by agapple** [comment]
具体可以wiki上搜索一下

**Comment by tengjh** [comment]
@theseusyang 解决了吗，@agapple wiki上没有找到相关说明呢？

**Comment by tengjh** [comment]
不好意思，知道了！下面有相关issue提示，没有看到后面！！
