### ISSUE TITLE
Otter 现在是否能够把 MySQL 数据同步到 Postgres数据库中?

### ISSUE THREAD

**Issue by theseusyang** [alibaba/otter#199]
Hi @agapple : 

Otter 现在是否能够把 MySQL 数据同步到 Postgres数据库中,或者说可以指定Postgres为目标数据源?

谢谢!

**Comment by agapple** [comment]
目前不支持，默认只有mysql/oracle，可以对接canal直接写目标库

**Comment by theseusyang** [comment]
好的, 我研究一下
