### ISSUE TITLE
自由门全量数据同步, 在 retl_buffer表中插入数据的疑问?

### ISSUE THREAD

**Issue by theseusyang** [alibaba/otter#201]
我想问一下, retl_buffer表中table_id 是指的源表还是目标表, pk_data 是源表的 pk值还是目标表的 pk 值?
插入后的结果, 是像下面的样子?

1   5   target_table_name  I    15  2016-09-08 16:11:58 2016-09-08 16:11:58
2   5   target_table_name   I   16  2016-09-08 16:11:58 2016-09-08 16:11:58
3   5   target_table_name   I   17  2016-09-08 16:11:58 2016-09-08 16:11:58

**Comment by luoyaogui** [comment]
table_id为0，pk_data 是源表的 pk值

**Comment by theseusyang** [comment]
@luoyaogui 好的, 多谢

**Comment by theseusyang** [comment]
@luoyaogui table_id 为你要同步的源表在 Otter 中的序号.

**Comment by luoyaogui** [comment]
有两种方式：一指定table-id（就是manager中表配置的序号）而full-name置null、二使用full-name（schemaName.tableName）而table-id置0。这两种都可以实现。
注释：使用全量同步无需修改配置，要求是先启动channal，然后往retl_buffer中插入要同步的table-id、pk值 或者 full-name、pk值即可。

**Comment by agapple** [comment]
LS解释非常到位

**Comment by theseusyang** [comment]
恩，不管别人懂没懂, 反正我听懂了

2016-09-19 14:02 GMT+08:00 agapple <notifications@github.com>:

**Comment by chenxiaozhong** [comment]
@luoyaogui 大神，想问一下，自由门全量数据同步retl_buffer表应该是放在哪个库上？otter库还是retl库里？

**Comment by luoyaogui** [comment]
@chenxiaozhong   sorry，最近比较忙，刚看到你的问题。
一、jdbc:mysql://192.168.0.248:3306    检查是否有retl这个库，没有则执行source otter-system-ddl-mysql.sql
二、对source端的用户授与retl这个数据库的select权限
三、执行 insert into retl.retl_buffer(ID,TABLE_ID, FULL_NAME,TYPE,PK_DATA,GMT_CREATE,GMT_MODIFIED) (select null,0,'数据库名称.表名称','U',主键名称,now(),now() from 数据库名称.表名称);

**Comment by liumouwna** [comment]
@luoyaogui  三、执行 insert into retl.retl_buffer(ID,TABLE_ID, FULL_NAME,TYPE,PK_DATA,GMT_CREATE,GMT_MODIFIED) (select null,0,'数据库名称.表名称','U',主键名称,now(),now() from 数据库名称.表名称);
这样子插入的行都是一样的除了retl.retl_buffer的ID列呀。

**Comment by hylyLLL** [comment]
> 的



> @chenxiaozhong sorry，最近比较忙，刚看到你的问题。
> 一、源DB所在的mysql检查是否有retl这个库，没有则执行source otter-system-ddl-mysql.sql
> 二、对source端的用户授与retl这个数据库的select权限
> 三、执行 insert into retl.retl_buffer(ID,TABLE_ID, FULL_NAME,TYPE,PK_DATA,GMT_CREATE,GMT_MODIFIED) (select null,0,'数据库名称.表名称','U',主键名称,now(),now() from 数据库名称.表名称);

你好，插入到retl_buffer数据同步完之后，retl_buffer中的数据需要自己手动删除吗？
