### ISSUE TITLE
全量同步整个数据库经查挂起，无法全部完成

### ISSUE THREAD

**Issue by leegtang** [alibaba/otter#206]
源数据库src位于10.1 ，dbname: ott（共有36张表）
目标数据库dest位于10.2， dbname: ott （共有0张表）
使用otter同步时，设置基于position 同步，数据同步缓慢，日志记录 no found table [*tablename] , pls check 。访问dest，已经同步了4张表，停掉channel, 重新启动channel, 又同步了几张表，日志报相同错，如此反复，不能一次性同步完所有表。

**Comment by agapple** [comment]
物理表估计存在删除，可以在canal黑名单里忽略这张表的解析和同步
