### ISSUE TITLE
在同步过程中需要变换某个字段的值，但是没生效，请问如何修改

### ISSUE THREAD

**Issue by lixqhuoli** [alibaba/otter#208]
代码如下。功能就是像把phone字段的号码去掉中间4位同步出去，实际使用过程中还是原样同步过去了。

package com.alibaba.otter.node.extend.processor;

import com.alibaba.otter.shared.etl.model.EventColumn;
import com.alibaba.otter.shared.etl.model.EventData;

public class PhoneUserEventProcessor extends AbstractEventProcessor {
	
	public boolean process(EventData eventData) {
		 for (EventColumn column : eventData.getColumns()) {
			 //对手机号码进行转换处理
	         if(column.getColumnName().equalsIgnoreCase("phone")){
	            String oriphone = column.getColumnValue();
	            System.out.println("process column phone:"+oriphone);
	            if(oriphone != null && oriphone.length() == 11){
	            	column.setColumnValue(oriphone.substring(0, 3)+"****"+oriphone.substring(7));
	            }
	         }
	        }
		
		return true;
	}

}

**Comment by agapple** [comment]
1. 检查下是否processor配置未生效
2. 打开load详细日志看看具体的数据

**Comment by lixqhuoli** [comment]
确认配置已经生效，改成写到一个新表是可以写进去，就是值没变。  load详细日志是如何配置？

**Comment by agapple** [comment]
pipeline高级参数里

**Comment by leegtang** [comment]
我一样配置后，可以脱敏 http://www.leegtang.com/home_blog_view_id_945f1faf431ce92ca090fb7b4b0cb470.html
