### ISSUE TITLE
针对多主键-全量同步，有一个怎样拼写的示例吗？

### ISSUE THREAD

**Issue by theseusyang** [alibaba/otter#212]
如果针对多主键时，对应的PK_DATA需要将需要同步表几个主键按照(char)1进行拼接,比如 concat(id,char(1),name)

**Comment by theseusyang** [comment]
insert into retl.retl_buffer(ID,TABLE_ID, FULL_NAME,TYPE,PK_DATA,GMT_CREATE,GMT_MODIFIED) (select null,0,'$schema.table$','I',id,now(),now() from $schema.table$);

**Comment by theseusyang** [comment]
比如有 PK1和 PK2两个主键的字段，怎么拼写成上述的PK_DATA?

concat(PK1,char(1),PK2)?

**Comment by theseusyang** [comment]
问题已经解决

**Comment by elefaint** [comment]
请问怎么解决的？我用concat(PK1,char(1),PK2)，无法触发自由门，日志显示data pk column size not match
