### ISSUE TITLE
跨机房同步部署问题

### ISSUE THREAD

**Issue by dusonchen** [alibaba/otter#214]
Q&A中最后一点没说得很明白，假如有这样的场景：
1.两个机房间内网不互通，只能通过公网IP访问，两个机房的数据库不对外暴露，只能通过内网访问
2.机房A为源数据库，机房B为目标数据库
3.机房A中部署了Manager和Zookeeper（单机模式），机房B中部署了一个节点Node
如何达到机房A的数据同步到机房B中？
是否机房2中的Node通过公网IP访问机房1的Manager？但机房B的数据库在机房A的Manager中是不能访问的

**Comment by agapple** [comment]
机房1和2的node之间互相通过公网访问

**Comment by dusonchen** [comment]
@agapple 你是意思是机房2中的Node通过公网IP访问机房1的Manager吧？
那在机房1中的Manager如何配置机房2中的数据源，因为机房2中的数据库是不对外暴露的（即无公网IP）。能否说得具体点呢？Thx

**Comment by agapple** [comment]
配置内网的ip即可，对应机房的node拿到配置后，可以基于内网ip访问。manager不需要连通数据库ip

**Comment by stuxiebin** [comment]
@agapple 
跨机房同步，希望同一机房里的node走内网，添加机器时， 机器IP 和 外部IP 应该怎么样妥善设置？
我的情况跟  @dusonchen 的有点类似，请您帮我解答一下，谢谢。

基本环境：
国内机房CN 部署了节点node1、zookeeper、manager(三者在一台机器),    node2
国外机房US 部署了节点node3, node4

其中，国内CN 、 国外US 的机器都配置有公网IP、私网IP，
目前同步需要： node1<->node3  跨机房
                          node1 ->node2   走内网、速度快
                          node3 ->node4   走内网、速度快

按照您上面的意思,我的理解(可能有错)是：
1.node的配置均为   otter.manager.address = manager public ip:1099
2.manager中 添加机器时，机器IP为： node public ip ，   外部IP不用填、也不启用
3.manager中 配置 数据源时，URL为： jdbc:mysql://node private ip:3306

**Comment by agapple** [comment]
1. 可以在添加机器，增加public ip
2. 在任务定义时选择想要启用public ip的机器，高级参数里打开外部ip通讯. 

数据源配置都是配置内网ip即可，因为数据源都是各自地域的node机器访问本机房的，只要你任务定义时源和目标的node机器选对即可

**Comment by stuxiebin** [comment]
@agapple  感谢您的回复，  我的图示如下(烂图，您凑合着看)：
![shili](https://cloud.githubusercontent.com/assets/19545894/20384621/6e77fa90-acef-11e6-964a-c8f83f22cfb3.PNG)

node1、node2在一个机房，
node1(公网IP:1.1.1.1     私网IP:192.168.1.1)， node2(公网IP:1.1.1.2    私网IP：192.168.1.2)

node3、node4在一个机房，
node3(公网IP:2.2.2.2     私网IP:192.168.2.1)， node4(公网IP:2.2.2.3     私网IP：192.168.2.2)

------> 单箭头代表 单向同步， <---------->双箭头代表 双向同步

我特别关注的是：在manager界面添加机器时， 这4个node节点的 机器IP 和 外部IP 应该具体怎么填？
机器IP设为 私网地址？ 外部IP设为公网地址？ 然后再启用外部IP？

不知道跨机房能不能实现 :  
node1、node2 之间通过 192.168.1.0/32 连接，
node3、node4之间通过 192.168.2.0/32 连接，
node1、node3之间通过 公网地址 来连接，

也就是说，同一机房的机器彼此用私网地址，同一机房中需要跨机房的机器   例如node1或node3除了用私网地址外 同时还可以用公网地址？

**Comment by agapple** [comment]
1. node1和node2为啥要通讯？
2. node1和node2如果作为互相备份节点，都会和node3和node4进行通讯

**Comment by yjp211** [comment]
我实际的部署拓扑结果跟楼主差不多，不过manager我是部署在国外。
请教一个问题， 如果是中国-》国外同步，manager是靠近select端好还是load端好？

另外，可以提供几点实际遇到的问题，供楼主参考
1、node1、2、3、4都要对所有外网IP都配置2088-2090的权限（本机也要对本机的公网IP开放权限）
2、manager部署在node1，node2、node3、node4的hostname必须设置为外网IP

@agapple  为什么会有第二条这样限制？

**Comment by agapple** [comment]
没理解你的第二条问题，能再具体描述一下？

**Comment by wh469012917** [comment]
@stuxiebin 错了，新增机器的时候机器ip不能填写为公网IP，这样的话node启动会报错
