### ISSUE TITLE
新版本只配置timestamp和binlog文件名同步有问题，无法定位同步

### ISSUE THREAD

**Issue by xmison** [alibaba/otter#215]
出现 KILL DUMP 224413593 failure:java.io.IOException: ErrorPacket [errorNumber=1094, fieldCount=-1, message=Unknown thread id: 224413593, sqlState=HY000, sqlStateMarker=#]
with command: KILL CONNECTION 224413593

**Comment by agapple** [comment]
使用下canal主干版本，还未release
