### ISSUE TITLE
一个表先目标加字段,再源加字段,之后同步报找不到字段

### ISSUE THREAD

**Issue by wlcwfwyt** [alibaba/otter#218]
pid:20 nid:6 exception:setl:com.alibaba.otter.node.etl.load.exception.LoadException: java.util.concurrent.ExecutionException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: column name extended_content is not found in Table[Table [name=deal_price_check; 18 columns]]

2016-11-03 18:51:02.329 [DbLoadAction] WARN  com.alibaba.otter.node.etl.load.loader.db.DbLoadAction - ##load phase one failed!
 201 java.util.concurrent.ExecutionException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception
     .LoadException: column name extended_content is not found in Table[Table [name=deal_price_check; 18 columns]]

停止channel后,再启动channel才能正常继续同步

**Comment by agapple** [comment]
估计是内存的表结构没有被刷新，目前ddl只能刷新源库，没法刷新目标库，是一个bug

**Comment by agapple** [comment]
可以开启自动恢复的功能，这样再出现异常后自动重启channel同步

**Comment by aiaix** [comment]
这个自动恢复功能在那里开启@agapple

**Comment by wlcwfwyt** [comment]
在监控管理里 “触发自动恢复阀值” 这个选项设置里

**Comment by aiaix** [comment]
触发自动恢复阀值 默认是2 表示什么含义？

**Comment by wlcwfwyt** [comment]
异常报警两次后就会自动停止再启channel

**Comment by aiaix** [comment]
多谢@wlcwfwyt
