### ISSUE TITLE
一个mysql多db同步效率请教

### ISSUE THREAD

**Issue by yjp211** [alibaba/otter#219]
一个mysql包含10个要同步的DB，以下哪种方案更好？
1、10个channel，每个channel都是 1个pipeline，1个canal，1个db映射  （一共建立10个canal）
2、1个channel，  1个pipile, 1个canal , 10个db映射(只有1个canal)

**Comment by agapple** [comment]
2更好

2016-11-10 19:55 GMT+08:00 yjp <notifications@github.com>:
