### ISSUE TITLE
rename操作容易导致select异常

### ISSUE THREAD

**Issue by yjp211** [alibaba/otter#222]
在做table的rename, 字段的rename，字段删除等 非【增加】ddl操作，很容易导致同步出错（SELECT阶段）：

报表找不到、column size is not match for table

**Comment by yjp211** [comment]
图中这个值可以手动修改吗？ 找遍了，也没有找到这个值存储在哪？
通过修改这个值，跳过相应的DDL同步出错，修复问题。可行吗？
![image](https://cloud.githubusercontent.com/assets/3926181/20341682/31ff1a4e-ac22-11e6-9343-a0d8814b2540.png)

**Comment by agapple** [comment]
参看wiki FAQ里重置位点
