### ISSUE TITLE
支持下DRDS做为目标

### ISSUE THREAD

**Issue by agapple** [alibaba/otter#225]
支持下分布式数据库DRDS作为目标进行同步

使用注意点:
1.  需要关闭高级参数里的batch模式(因为otter默认会开事务,避免DRDS进行分布式事务管理,无意义)
2.  DRDS会要求update/delete都必须带上拆分字段,所以实现上会将拆分字段按照主键进行处理，避免变更主键或者拆分字段 【如果源库和目标库存在异构，比如拆分字段列名不同，需要将源表映射到目标的拆分字段的列设置为主键，切记】

just have fun.

**Comment by tengjh** [comment]
DRDS会要求update/delete都必须带上拆分字段,所以实现上会将拆分字段按照主键进行处理，避免变更主键或者拆分字段 【如果源库和目标库存在异构，比如拆分字段列名不同，需要将源表映射到目标的拆分字段的列设置为主键，切记】
这个是要修改分区键主键吗？
