### ISSUE TITLE
中美同步延时问题

### ISSUE THREAD

**Issue by shopshow** [alibaba/otter#226]
![image](https://cloud.githubusercontent.com/assets/9455965/20451644/ca364f92-ae36-11e6-885f-c9bcf40b8103.png)
如图 pipeline1 是 美国往中国同步，有时候延时达到了4m多钟，中国往美国同步很快

pipeline1 的设置：
![image](https://cloud.githubusercontent.com/assets/9455965/20451657/f6d181d4-ae36-11e6-92f6-302827d92549.png)

请问如何设置可提高同步效率？

**Comment by shopshow** [comment]
![image](https://cloud.githubusercontent.com/assets/9455965/20451885/da320456-ae39-11e6-9003-5e4685b32585.png)

**Comment by agapple** [comment]
机器别选错了，select机器尽可能靠近源，load机器尽可能靠近目标

**Comment by shopshow** [comment]
也就是说，load 机器的node 我要选择国内的服务器？

**Comment by agapple** [comment]
多看下wiki FAQ
