### ISSUE TITLE
通信端口的疑问

### ISSUE THREAD

**Issue by yjp211** [alibaba/otter#231]
美国节点manager/node1， node2
中国节点 node3 , node4

中国--》美国的数据同步已正常开启，并一直有数据。
使用netstat观察
manager通过1099与所有的node连接
node之间通过2088都有互相连接

1、所有的node端口2089、2090并没有任何连接建立
   ```
  地址端口：	2088
 下载端口：	2089
 MBean端口：	2090
```
 因为有数据时刻在同步着，2089没有任何连接表示很奇怪
2、pipline文件传输加密，开启后。抓取2088的通信数据，并无变化？ 怎么验证传输加密是否开启

**Comment by agapple** [comment]
你选择传输模式为HTTP传输时，你就能看到2089端口的使用了，并且看到一些临时文件有一些加密处理
