### ISSUE TITLE
最近otter老自动停掉，日志查看是正常，有同样的人遇到的吗？

### ISSUE THREAD

**Issue by jsrgqinbin** [alibaba/otter#233]
最近otter老自动停掉，日志查看是正常，跑了好久一直正常，只有这两天才出现的问题。

PID文件都在，进程已经没有了，不知道怎么查问题，有人遇到的能说说吗？

**Comment by agapple** [comment]
jvm进程不在？得查查是否是OOM或者是linux oom killer给杀掉了进程
