### ISSUE TITLE
表结构同步问题

### ISSUE THREAD

**Issue by hyml** [alibaba/otter#238]
通过源码只能同步库名与表名相同的表结构，有没有其他方式支持库名或表名不同的表结构同步。

**Comment by weikuo0506** [comment]
不太明白你的问题，通过实现AbstractEventProcessor接口，自定义数据扩展修改，想怎么修改数据都可以啊

**Comment by chenxiaozhong** [comment]
库名与表名都不需要相同。也可以同步的啊

**Comment by agapple** [comment]
DDL同步目前有约束，要求库名和表名都一致
