### ISSUE TITLE
Otter双向回环控制实现机制疑问

### ISSUE THREAD

**Issue by EternalSpring** [alibaba/otter#239]
群主，想咨询下，otter配置双向同步，在MasterA批量修改N条数据后，同步到MasterB的binlog数据量为何会扩增几十倍以上不止？查看binlog文件，发现多出很多如下update retl_mark的语句
 UPDATE `retl`.`retl_mark`
 WHERE
   @1=249 /* LONGINT meta=0 nullable=0 is_null=0 */
   @2=0 /* INT meta=0 nullable=1 is_null=0 */
   @3=NULL /* INT meta=384 nullable=1 is_null=1 */
 SET
   @1=249 /* LONGINT meta=0 nullable=0 is_null=0 */
   @2=11 /* INT meta=0 nullable=1 is_null=0 */
   @3=NULL /* INT meta=384 nullable=1 is_null=1 */
 at 305919305
161209 14:21:54 server id 3308  end_log_pos 305919361 CRC32 0xf8fe8149         Table_map: `retl`.`retl_mark` mapped to number 70896
 at 305919361
161209 14:21:54 server id 3308  end_log_pos 305919423 CRC32 0xc1e11543         Update_rows: table id 70896 flags: STMT_END_F

BINLOG '
gk1KWBPsDAAAOAAAAIH1OxIAAPAUAQAAAAEABHJldGwACXJldGxfbWFyawADCAMPAoABBkmB/vg=
gk1KWB/sDAAAPgAAAL/1OxIAAPAUAQAAAAEAAgAD///8+QAAAAAAAAALAAAA/PkAAAAAAAAAAAAA
AEMV4cE=
'/*!*/;
 UPDATE `retl`.`retl_mark`
 WHERE
   @1=249 /* LONGINT meta=0 nullable=0 is_null=0 */
   @2=11 /* INT meta=0 nullable=1 is_null=0 */
   @3=NULL /* INT meta=384 nullable=1 is_null=1 */
 SET
   @1=249 /* LONGINT meta=0 nullable=0 is_null=0 */
   @2=0 /* INT meta=0 nullable=1 is_null=0 */
   @3=NULL /* INT meta=384 nullable=1 is_null=1 */
 at 305919423
161209 14:21:54 server id 3308  end_log_pos 305919454 CRC32 0xd02a4bf7         Xid = 4651024813
按照双向回环控制逻辑的理解，大于300是在事务头和尾中插入otter同步标识，在binlog中两条update retl_mark中间会嵌入业务表操作语句，但目前发现的是有很多<300的update retl_mark，如果是用于内部系统的话，为何会多出这么多？求解。

**Comment by agapple** [comment]
otter同步目标是走了batch，每批数据前后都会有retl_mark表的变更操作，变更操作的量取决于原始数据量，最多2倍的sql量

**Comment by EternalSpring** [comment]
好的，如果是这样的话，按这边的统计，十分钟内业务库表的SQL操作条数是39000条，而UPDATE:retl.retl_mark表的操作条数是680000条，这种情况可以定论为非正常现象？

**Comment by timothyzhw** [comment]
我配置的双A，两边同时修改同一条数据，会出现循环修改，请问一下原因？

**Comment by agapple** [comment]
@timothyzhw 检查一下是否用了innodb以外的存储引擎

**Comment by timothyzhw** [comment]
找到原因了，是因为在 my.conf里设置了只有几个业务库写binlog，缺了retl库。

**Comment by EternalSpring** [comment]
有，除了innodb，还有memory存储引擎，这个是否有影响呢？

**Comment by agapple** [comment]
有影响的，不支持事务的引擎，binlog生成会和retl_mark的事务分离，导致无法判断是否是回环同步

**Comment by EternalSpring** [comment]
好的，了解

**Comment by gerori** [comment]
> 找到原因了，是因为在 my.conf里设置了只有几个业务库写binlog，缺了retl库。

請問retl也要同步嗎？為什麼retl也需要binlog呢？
