### ISSUE TITLE
添加字段OTTER同步失败

### ISSUE THREAD

**Issue by aiaix** [alibaba/otter#242]
pid:5 nid:1 exception:setl:com.alibaba.otter.node.etl.transform.exception.TransformException: wallet_user_id is not found in Table [name=tj_oto_order; 31 columns] and source : oto..*
	

2016-12-23 09:34:38.483 [pipelineId = 5,taskName = transformWorker] WARN  c.a.o.s.a.i.setl.zookeeper.termin.WarningTerminProcess - nid
:1[5:setl:com.alibaba.otter.node.etl.transform.exception.TransformException: wallet_user_id is not found in Table [name=tj_oto_order; 
31 columns] and source : oto..*
]
2016-12-23 09:36:39.428 [pipelineId = 5,taskName = transformWorker] ERROR com.alibaba.otter.node.etl.transform.TransformTask - [5] tra
nsformWork executor is error! data:EtlEventData[currNid=1,nextNid=1,desc=[MemoryPipeKey[identity=Identity[channelId=3,pipelineId=5,pro
cessId=15],time=1482456999059,dataType=DB_BATCH]],processId=15,startTime=1482456998513,endTime=<null>,firstTime=1482214467000,batchId=
16,number=10159,size=<null>,exts=<null>,pipelineId=5]
com.alibaba.otter.node.etl.transform.exception.TransformException: wallet_user_id is not found in Table [name=tj_oto_order; 31 columns
] and source : oto..*
2016-12-23 09:36:39.494 [pipelineId = 5,taskName = transformWorker] WARN  c.a.o.s.a.i.setl.zookeeper.termin.WarningTerminProcess - nid
:1[5:setl:com.alibaba.otter.node.etl.transform.exception.TransformException: wallet_user_id is not found in Table [name=tj_oto_order; 
31 columns] and source : oto..*
]

源头成功，目标不成功。双向配置，只在源开启DDL，源头跳过DDL也没用。OTTER 4.2.12 MYSQL 5.6.30

@agapple

**Comment by aiaix** [comment]
跳过DDL错误也没用

**Comment by aiaix** [comment]
目标端添加字段解决

**Comment by agapple** [comment]
wallet_user_id is not found in Table [name=tj_oto_order; 31 columns]

是目标库缺少一个列

**Comment by berace** [comment]
> pid:5 nid:1 exception:setl:com.alibaba.otter.node.etl.transform.exception.TransformException: wallet_user_id is not found in Table [name=tj_oto_order; 31 columns] and source : oto..*
> 
> 2016-12-23 09:34:38.483 [pipelineId = 5,taskName = transformWorker] WARN c.a.o.s.a.i.setl.zookeeper.termin.WarningTerminProcess - nid
> :1[5:setl:com.alibaba.otter.node.etl.transform.exception.TransformException: wallet_user_id is not found in Table [name=tj_oto_order;
> 31 columns] and source : oto..*
> ]
> 2016-12-23 09:36:39.428 [pipelineId = 5,taskName = transformWorker] ERROR com.alibaba.otter.node.etl.transform.TransformTask - [5] tra
> nsformWork executor is error! data:EtlEventData[currNid=1,nextNid=1,desc=[MemoryPipeKey[identity=Identity[channelId=3,pipelineId=5,pro
> cessId=15],time=1482456999059,dataType=DB_BATCH]],processId=15,startTime=1482456998513,endTime=,firstTime=1482214467000,batchId=
> 16,number=10159,size=,exts=,pipelineId=5]
> com.alibaba.otter.node.etl.transform.exception.TransformException: wallet_user_id is not found in Table [name=tj_oto_order; 31 columns
> ] and source : oto..*
> 2016-12-23 09:36:39.494 [pipelineId = 5,taskName = transformWorker] WARN c.a.o.s.a.i.setl.zookeeper.termin.WarningTerminProcess - nid
> :1[5:setl:com.alibaba.otter.node.etl.transform.exception.TransformException: wallet_user_id is not found in Table [name=tj_oto_order;
> 31 columns] and source : oto..*
> ]
> 
> 源头成功，目标不成功。双向配置，只在源开启DDL，源头跳过DDL也没用。OTTER 4.2.12 MYSQL 5.6.30
> 
> @agapple

请问你是如果添加的字段，我添加后新字段值一直写不到目标库：
public class TestEventProcessor extends AbstractEventProcessor {

	public boolean process(EventData eventData) {
	 boolean isHandle = true;
     if (eventData == null)
         return isHandle;
	 EventColumn c = new EventColumn();
	 /*c.setColumnName("update_time");
	 c.setColumnType(Types.DATE);
	 c.setColumnValue("2019-03-05 00:00:00");*/
	 c.setColumnName("mark");
	 c.setColumnType(Types.VARCHAR);
	 c.setColumnValue("fafasfdsaf");
	 c.setUpdate(true);
	 eventData.getColumns().add(c);
	 List<EventColumn> cols = eventData.getColumns();
     cols.add(c);
	 eventData.setColumns(cols);
    return isHandle;
}

}
