### ISSUE TITLE
自由门数据的疑惑

### ISSUE THREAD

**Issue by boboChina** [alibaba/otter#249]
看了历史的几个问答，retl库必须和源库在同一个实例   ，然后再插入相关数据。但是一般的生产库会分散在多个实例上面，也就是生产库每个实例都需要新建一个retl库 然后启动了channal再插入数据。这样对生产库入侵太大了，有没有更好的方式。如果用位点来做，那么更悲剧了。需要把所有的库先记录位点，然后备份到目标库，然后在cannal设置位点，然后再启动。。。

请问是否有更好的方式，或者下个版本是否考虑优化下初始化的方式

**Comment by agapple** [comment]
LS正解
