### ISSUE TITLE
希望有一个发送邮件测试

### ISSUE THREAD

**Issue by jake2009** [alibaba/otter#255]
希望有一个发送邮件测试

**Comment by agapple** [comment]
看一下wiki

**Comment by luyee** [comment]
记录下，以后谁要的能翻到不
修改manager的otter.properties
```
# manager email user config
otter.manager.monitor.email.host = smtp.gmail.com
otter.manager.monitor.email.username = 
otter.manager.monitor.email.password = 
otter.manager.monitor.email.stmp.port = 465
```
添加接受人邮件地址
         系统管理-->系统参数-->自定义报警联系人(格式：key=邮箱)
添加监控
         同步管理-->点击需要加监控的channel-->监控-->添加（一键添加监控）-->设置阈值(这里一定要改，默认是ERROR,EXCEPTION这种)，报警间隔时间，发送人KEY( 注意这里配置的是key)

**Comment by wz2cool** [comment]
同样希望有这个东西 这样可以方便测试
