### ISSUE TITLE
rds的slave同步数据到另一个数据库的问题

### ISSUE THREAD

**Issue by ziyege** [alibaba/otter#257]
现象：
1.使用阿里云主库的一个从库来作为源数据库，把数据同步到另一个数据库里面，bin_log和 row 都开启了，然后测试结果是：ddl操作能够同步无问题，数据的增删改查无法同步。
2.使用相同的 node 和配置 ，从 rds的主库同步数据到另一个数据库，ddl和数据都没有问题。
请问：阿里云从库的同步，不支持吗？或者说有 额外的 配置？ 谢谢！
![image](https://cloud.githubusercontent.com/assets/21215179/21845871/6ba7f9c6-d82f-11e6-96ad-3ee1ead20752.png)

**Comment by agapple** [comment]
没有特殊的限制

**Comment by ziyege** [comment]
请问：从库同步数据到另一台机器，只能同步ddl，不能同步数据，可能会是什么原因？非常感谢。

**Comment by agapple** [comment]
可能只读实例没有开启slave日志？

**Comment by ziyege** [comment]
开启了的。提了阿里云工单，只是说，阿里云从库的binlog，用户使用不了

**Comment by agapple** [comment]
binlog对于数据库的压力还好了，CPU影响很小，按照阿里的经验一般是不超过10个slave
