### ISSUE TITLE
如何解决mysql主外键约束的问题

### ISSUE THREAD

**Issue by LWT1118** [alibaba/otter#260]
数据库Mysql，一端在美国机房，另一端在阿里云
先从美国机房倒出数据，倒出数据之后启动美国的服务器，然后把导出来的数据导入到阿里云服务器，在这个过程中因为美国的数据库处于启动状态，所以会丢失部分数据。我的问题是如何补回这部分丢失的数据。

先做了一个直接同步的尝试，结果提示主外键冲突，我估计是因为表没有指定顺序，先导入的子表的数据，导致insert失败，后来禁用主外键之后还是同样的错误。

**Comment by agapple** [comment]
可以使用otter的表权重，子表的权重配置>主表，这样可以保证增量同步优先同步主表数据，然后再插入子表

**Comment by LWT1118** [comment]
@agapple 映射关系里的那里的权重是默认的数字5,要改成子表权重配置>主表这里应该写哪个值？

**Comment by LWT1118** [comment]
@agapple 又重新看了一遍otter的文档，将权重数字设为了1，还是会报：Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails ……

**Comment by LWT1118** [comment]
@agapple 已明白权重，正在重新同步……  谢谢！

**Comment by heshangdaben** [comment]
@LWT1118 怎么设置的。我也遇到一样的问题，求教！！！

**Comment by LWT1118** [comment]
@heshangdaben 如果不同表之间的主外键约束可以根据设置权重来解决，如果是单表的主外键约束，除非去掉物理约束，不然没办法解决。

**Comment by quanllong** [comment]
如果通过配置otter表权重解决外键约束，有可能引入新问题，可能会导致更新父表失败
1、如果默认不配置权重，load阶段并行写入有可能报错：Cannot add or update a child row。
2、如果设置子表的权重配置>主表，虽然控制先插入主表然后是子表，避免了插入报错，但是delete时也会先删父表，此时报另一个错  Cannot delete or update a parent row。

其实在第一种情况最好就不作处理，otter并行写入失败后，默认降级为串行写入，最后写目标表是成功的
