### ISSUE TITLE
自由门到底该怎么触发？

### ISSUE THREAD

**Issue by LWT1118** [alibaba/otter#263]
现在的情况是可以同步数据，但是不触发自由门的数据导入。

环境： otter库、retl库、源库和manager都配置在一台服务器上。但是往retl_buffer表里面用source导入insert的SQL，如：
insert into retl_buffer(TABLE_ID, FULL_NAME,TYPE,PK_DATA,GMT_CREATE,GMT_MODIFIED) values (0,'test.sales_flat_order','I','entity_id',now(),now());
请问执行完SQL之后什么时侯会触发自由门的数据导入？如果触发了有没有什么地方可以查询，如果有异常日志记在哪里？
谢谢！

**Comment by LWT1118** [comment]
已可以同步了

**Comment by dmnwuguo** [comment]
你好，请问你是怎么处理好的呢，能说明一下吗？ 谢谢
