### ISSUE TITLE
同步异常：com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: SimpleDdlParser process query failed. 

### ISSUE THREAD

**Issue by LanChunqian** [alibaba/otter#264]
otter版本：4.2.14
pid:3 nid:3 exception:canal:187canal_208master:com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: SimpleDdlParser process query failed. pls submit issue with this queryString: create table mq_bind( 
id BIGINT NOT NULL AUTO_INCREMENT COMMENT '业务无关自增主键', 
topic_id BIGINT NOT NULL COMMENT 'exchange id', 
queue_name VARCHAR(32) NOT NULL COMMENT '订阅队列名称', 
routing_key VARCHAR(64) NOT NULL DEFAULT '' COMMENT '路由规则，广播类型exchange，该字段为空', 
queue_desc VARCHAR(64) NOT NULL DEFAULT '' COMMENT '订阅消费业务线描述', 
web_hook VARCHAR(1028) NOT NULL DEFAULT '' COMMENT '产品线消费回调地址，json格式 {default:http1,jx:http2....},key为机房标识，value未回调接口地址 
默认使用default地址', 
exclusive_consumer TINYINT NOT NULL DEFAULT 1 COMMENT '默认独占消费者类型', 
default_consumer_ip VARCHAR(64) NOT NULL COMMENT '启动默认消费者的ip地址,多个ip 逗号分隔', 
app_id BIGINT NOT NULL COMMENT '订阅主题的app_info id', 
is_work_queue TINYINT NOT NULL DEFAULT 0 COMMENT '是否为队列服务,默认为非队里服务', 
status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' comment'当前订阅关系生效状态', 
ctime int UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间秒级时间戳', 
utime int UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新时间秒级时间戳', 
PRIMARY KEY (id), 
INDEX `idx_mq_bind_app_id`(app_id), 
INDEX `idx_mq_bind_topic_id`(topic_id), 
UNIQUE `uk_mq_bind_queue_name`(queue_name) 
)ENGINE =Innodb DEFAULT CHARSET =utf8 COMMENT 'mq 订阅关系表'

**Comment by agapple** [comment]
最新版本切换到了druid sql全解析，可以解决这个问题
