### ISSUE TITLE
数据库命名不规范，导致otter数据同步报错

### ISSUE THREAD

**Issue by gantts** [alibaba/otter#274]
1、数据命名含有关键字 如“order"
2、数据命名含有歧义符号 如"test.3.5"

**Comment by gantts** [comment]
不规范的命名会导致DML、DDL操作都有问题   例如“insert into test.3.5.TableName values(); ”

**Comment by agapple** [comment]
oracle没有做转义，mysql做了

**Comment by gantts** [comment]
同步的数据库是mysql5.6.34  otter版本为4.2.12    没办法修改数据库名了，取消了关键字和符号"."

**Comment by agapple** [comment]
4.2.15已解决
