### ISSUE TITLE
otter是否一个channel对映一个线程，配置了一百多个channel，otter会不会挂掉？

### ISSUE THREAD

**Issue by gantts** [alibaba/otter#276]
A方案、 一个channel + 一个pipeline + 多个映射关系表 
B方案、 一个channel + 一个pipeline + 一个映射关系表

A 方案按业务主题区分，考虑这种配置如果其中一张表挂了，会导致整个pipeline挂起，影响其他表无法同步，因此改为B方案，以表为单位配置 ，已经配置了一百多个channel了，随着表同步需求增多会增加更多。 

jstack pid 查看线程有很多，请问是否一个channel对映一个线程，B方案有问题吗，应该采用哪种方式配置呢？

**Comment by agapple** [comment]
建议A方案，降低对mysql binlog dump的压力

**Comment by gantts** [comment]
已使用A方案，谢谢
