### ISSUE TITLE
初学者 安装问题

### ISSUE THREAD

**Issue by tithonus163** [alibaba/otter#277]
要实现:
[A机mysql] ==单项同步==>[B机mysql]

自己都感觉是白痴的问题: 刚开始了解,见谅..
otter的mysql,manager,zookeeper,node,aria2都必须安装在哪台主机上?

可以像下面的这样安装吗? 
[A机mysql] ===> [X机安装mysql,manager,zookeeper,node,aria2] ===>[B机mysql]

能列出A/B/X机上必须安装的软件是哪些吗?

A机若是RDS.除了开log-bin=mysql-bin,binlog_foramt=ROW需要配置些什么?

**Comment by agapple** [comment]
先看一下quick start
