### ISSUE TITLE
延迟告警信息没有收到

### ISSUE THREAD

**Issue by suhuaguo** [alibaba/otter#278]
在 DelayStatRuleMonitor 中 checkDelayTime(AlarmRule rule, Long delayTime) 这个方法
的 代码片段：
if (delayTime >= maxDelayTime * 1000) {
            sendAlarm(rule, String.format(DELAY_TIME_MESSAGE, rule.getPipelineId(), delayTime));
            return true;
        }

delayTime 是 秒。而 maxDelayTime * 1000 这个表示是 毫秒了。所以。就不能发送告警了

**Comment by agapple** [comment]
tks

**Comment by agapple** [comment]
d028d470727e4419056ec8d9c0e8e8e50d00a0fa
