### ISSUE TITLE
node重启后，同步时断时续的挂起

### ISSUE THREAD

**Issue by stuxiebin** [alibaba/otter#282]
otter同步过程中，发现一个node不明原因的停止了，重启node后，没一会儿同步就挂起，
解挂 按钮为灰色，点击推送后也没效果，
![default](https://cloud.githubusercontent.com/assets/19545894/23574966/6cd82ed8-00c0-11e7-9a40-78bf6fb776cf.PNG)

查看了日志信息，持续的显示如下：
![default](https://cloud.githubusercontent.com/assets/19545894/23574994/e17abfda-00c0-11e7-8a6b-6da52649d479.PNG)

pid:15 nid:null exception:channel:can't restart by exist process[7738405,7738406,7738407,7738408,7738410,7738411,7738412,7738413,7738414]
请问下这种情况该怎么解决？

**Comment by agapple** [comment]
这异常是指上一个任务没停止成功，需要多停止几次同步任务，然后再启动

**Comment by dossec** [comment]
我在测试中也遇到挂起，是因为node挂了。

**Comment by agapple** [comment]
停止任务，重新启动，多试几次就能恢复，毕竟是分布式系统有一些网络不确定因素
