### ISSUE TITLE
如何设置同步的频率，日志老撑爆硬盘

### ISSUE THREAD

**Issue by GreenJoson** [alibaba/otter#286]
请教下，如何设置otter同步推送的频率，1分钟都产生几个日志，硬盘时不时就撑爆，有没有办法设置同步的频率，比如几个小时同步一次之类的？

**Comment by agapple** [comment]
这是增量同步，不是单纯ETL工具，不能控制时间

**Comment by GreenJoson** [comment]
好，谢谢老大百忙回复
