### ISSUE TITLE
如何配置一对多映射？

### ISSUE THREAD

**Issue by operands** [alibaba/otter#287]
官方文档上提到otter支持一对多的字段映射，但我试了几种方法都无法实现
我的做法如下：
有A、B两个库
A库：a表（pk、m、n三个字段，pk为主键）
B库：b表（pk、m1）、c表（pk、n1）
映射1：a表{pk、m}->b表{pk、m1}
映射2：a表{pk、n}->c表{pk、n1}
测试结果：
我把映射1和映射2配置到了一个pipeline中，测试发现m变化能触发m1变化，但n变化n1却不变，并且node和manager没有挂起和出现任何异常,load日志也没有任何打印。
我又尝试了把映射1和映射2的源表配置为不同编号的数据表，但实际上是指向同一个表，还是不行。
请问一对多映射我这种配置方式有什么问题吗？正确的方式应该怎样配呢？难道要配置多个channel么？

P.S.
我尝试修改ViewExtractor类源码，实现了在一个pipeline下配置多个映射达到一对多映射的效果，但担心出现其他问题，真心请教设计者正确的配置方式，感谢赐教！

**Comment by agapple** [comment]
目前一张表有两个不同的view配置，会有一些影响，的确是会有一些问题

**Comment by agapple** [comment]
分成两个任务把

**Comment by operands** [comment]
我自己修改了ViewExtractor和RowDataTransformer类源码，实现了上述多个view的映射的效果，自测各种情况暂时没有发现问题。能否把diff发给您帮忙review一下呢？

**Comment by operands** [comment]
@agapple

**Comment by agapple** [comment]
@operands 欢迎提交PR
