### ISSUE TITLE
maven打包时报错

### ISSUE THREAD

**Issue by Nem0Wang** [alibaba/otter#290]
[ERROR] Failed to execute goal on project shared.common: Could not resolve dependencies for project com.alibaba.otter:shared.common:jar:4.2.15-SNAPSHOT: Failed to collect dependencies at org.jtester:jtester:jar:1.1.8 -> mockit:jmockit:jar:0.999.10: Failed to read artifact descriptor for mockit:jmockit:jar:0.999.10: Failure to find mockit:mockit:pom:0.999.10 in http://repo1.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project shared.common: Could not resolve dependencies for project com.alibaba.otter:shared.common:jar:4.2.15-SNAPSHOT: Failed to collect dependencies at org.jtester:jtester:jar:1.1.8 -> mockit:jmockit:jar:0.999.10
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project com.alibaba.otter:shared.common:jar:4.2.15-SNAPSHOT: Failed to collect dependencies at org.jtester:jtester:jar:1.1.8 -> mockit:jmockit:jar:0.999.10
Caused by: org.apache.maven.model.resolution.UnresolvableModelException: Failure to find mockit:mockit:pom:0.999.10 in http://repo1.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced

 http://repo1.maven.org/maven2源没有mockit:mockit:pom:0.999.10 这个版本的包啊，你给的lib添加到本地库的也没有这个文件。该怎么解决呢

**Comment by Nem0Wang** [comment]
jtester-1.1.8.pom 里的 org.fitnesse:fitnesse 20100211 maven仓库里没有 我换成了20111025版本
mockit:mockit 0.999.10 也没有 我换成存在的0.999.4 这样编译打包才能成功 不知这样有影响吗？

**Comment by agapple** [comment]
我本地lib下有一个install脚本吧，操作一下这个试试

**Comment by Nem0Wang** [comment]
install脚本我肯定执行过了，而且都是build sucess添加到本地库。我和同事编译都遇到了上面的错误，远程maven库的确是没有项目里配置的几个依赖版本。

**Comment by ryansunboy** [comment]
看下jmockit-0.999.10.pom中是否有父模块
     <parent><groupId>mockit</groupId>
      <artifactId>mockit</artifactId><version>0.999.10</version>
</parent>
将其删除

**Comment by duval1024** [comment]
![image](https://user-images.githubusercontent.com/21072525/128279921-bb075bf6-b327-4644-a0d9-5c2ad6b81c83.png)

**Comment by duval1024** [comment]
真是个年久失修的项目
