### ISSUE TITLE
pid:1 processIds:3658678 elapsed 65 seconds 导致原因

### ISSUE THREAD

**Issue by ziyege** [alibaba/otter#293]
群主，otter 偶尔出现这类日志：
pid:1 processIds:3658678 elapsed 65 seconds
pid:1 processIds:3658646,3658648,3658650 elapsed 70 seconds
这是什么原因啊？会影响数据吗

**Comment by agapple** [comment]
多停止几次，然后再启动

**Comment by lilykyung** [comment]
我也遇到了，经常报此类warn，但貌似不会影响同步
另外群主，otter经常显示定位中，且同步会出现延时，一般是什么情况导致的啊

**Comment by agapple** [comment]
定位中估计还是一段时间没收到mysql binlog数据的问题，考虑开启定时心跳？
issue中对应的异常日志是指单个process执行时间过长

**Comment by luyee** [comment]
遇到+1.

**Comment by LinQThomas** [comment]
怎么解决呢？

**Comment by Kinger0216** [comment]
重启无用
