### ISSUE TITLE
otter manager界面如何关闭匿名访问

### ISSUE THREAD

**Issue by dossec** [alibaba/otter#298]
匿名访问可以看到一些配置信息，在外网不安全，如何关闭呢？谢谢！

**Comment by agapple** [comment]
需要做一些系统改造

**Comment by dossec** [comment]
@agapple 能说的具体点吗，要个性哪些设置呢，谢谢！

**Comment by liyongcun** [comment]
通过防火墙 ip+port 实现拦截

**Comment by zhonghui001** [comment]
> 匿名访问可以看到一些配置信息，在外网不安全，如何关闭呢？谢谢！

com.alibaba.otter.manager.web.webx.valve.AuthContextValve这个类
修改invoke方法
` public void invoke(PipelineContext pipelineContext) throws Exception {
        TurbineRunData rundata = getTurbineRunData(request);

        // TODO 走 api 的验证
        if (isAPI(rundata)) {
            if (apiAuthService.auth(rundata)) {
                pipelineContext.invokeNext();
            } else {
                redirect(pipelineContext, rundata, forbiddenLink); // TODO 需要转跳到 json 格式的 link
            }
            return;
        }

        // 得到请求URL相对路径(不包含域名/端口信息)
        String requestUrl = rundata.getRequest().getRequestURI();
        List<AuthorizeType> result = urlAnalyze.check(requestUrl);
        String action = StringUtil.toCamelCase(trimToNull(rundata.getParameters().getString(actionParam)));
        String eventName = getEventName();

        // 首先判断是否登录
        User user = (User) rundata.getRequest().getSession().getAttribute(WebConstant.USER_SESSION_KEY);

        if (StringUtils.isNotEmpty(action)) {
            result.addAll(urlAnalyze.check(action, eventName));
        }

        if (result.isEmpty()) {
            // 访问的连接不符合权限匹配规则，跳转到登录页面
            redirect(pipelineContext, rundata, forbiddenLink);
        } else {
            if (null == user) {
                // 如果用户未登录，则判断访问连接的权限匹配集合：
                // 1.如果有高于匿名权限，则跳转到登录页面；
                // 2.如果集合中只包含匿名权限，则通过。
                if (requestUrl.contains("login")){
                    pipelineContext.invokeNext();
                }else
                    redirect(pipelineContext, new TurbineRunDataImpl(request), loginLink);

//                if (result.contains(AuthorizeType.OPERATOR) || result.contains(AuthorizeType.ADMIN)) {
//                    redirect(pipelineContext, rundata, loginLink);
//                }
//                else {
//                    pipelineContext.invokeNext();
//                }
            } else {
                // 如果用户已经登录，则判断访问连接的权限匹配集合：
                // 1.如果权限集合有等于（低于）用户权限，则通过；
                // 2.如果权限集合有高于用户权限，则跳转到登录页面。
                if (compareAuth(user.getAuthorizeType(), result)) {
                    pipelineContext.invokeNext();
                } else {
                    redirect(pipelineContext, rundata, forbiddenLink);
                }
            }
        }
    }`

修改了
`if (null == user) {}`
部分代码
然后打包，替换服务器上的manager.web-4.2.17.jar包

**Comment by agapple** [comment]
LS正解

**Comment by linqh1** [comment]
直接修改webx.xml配置文件即可
`<?xml version="1.0" encoding="UTF-8"?>
<beans:beans xmlns:beans="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:p="http://www.springframework.org/schema/p"
	xmlns:services="http://www.alibaba.com/schema/services"
	xmlns:ml-adapters="http://www.alibaba.com/schema/services/module-loader/adapters"
	xmlns:ml-factories="http://www.alibaba.com/schema/services/module-loader/factories"
	xmlns:pull-factories="http://www.alibaba.com/schema/services/pull/factories"
	xmlns:request-contexts="http://www.alibaba.com/schema/services/request-contexts"
	xmlns:basic-interceptors="http://www.alibaba.com/schema/services/request-contexts/basic/interceptors"
	xmlns:parser-filters="http://www.alibaba.com/schema/services/request-contexts/parser/filters"
	xmlns:session-encoders="http://www.alibaba.com/schema/services/request-contexts/session/encoders"
	xmlns:session-idgens="http://www.alibaba.com/schema/services/request-contexts/session/idgens"
	xmlns:session-interceptors="http://www.alibaba.com/schema/services/request-contexts/session/interceptors"
	xmlns:model-encoders="http://www.alibaba.com/schema/services/request-contexts/session/model-encoders"
	xmlns:session-stores="http://www.alibaba.com/schema/services/request-contexts/session/stores"
	xsi:schemaLocation="
                 http://www.alibaba.com/schema/services http://localhost:8080/schema/services.xsd
                 http://www.alibaba.com/schema/services/module-loader/adapters http://localhost:8080/schema/services-module-loader-adapters.xsd
                 http://www.alibaba.com/schema/services/module-loader/factories http://localhost:8080/schema/services-module-loader-factories.xsd
                 http://www.alibaba.com/schema/services/pull/factories http://localhost:8080/schema/services-pull-factories.xsd
                 http://www.alibaba.com/schema/services/request-contexts http://localhost:8080/schema/services-request-contexts.xsd
                 http://www.alibaba.com/schema/services/request-contexts/basic/interceptors http://localhost:8080/schema/services-request-contexts-basic-interceptors.xsd
                 http://www.alibaba.com/schema/services/request-contexts/parser/filters http://localhost:8080/schema/services-request-contexts-parser-filters.xsd
                 http://www.alibaba.com/schema/services/request-contexts/session/encoders http://localhost:8080/schema/services-request-contexts-session-encoders.xsd
                 http://www.alibaba.com/schema/services/request-contexts/session/idgens http://localhost:8080/schema/services-request-contexts-session-idgens.xsd
                 http://www.alibaba.com/schema/services/request-contexts/session/interceptors http://localhost:8080/schema/services-request-contexts-session-interceptors.xsd
                 http://www.alibaba.com/schema/services/request-contexts/session/model-encoders http://localhost:8080/schema/services-request-contexts-session-model-encoders.xsd
                 http://www.alibaba.com/schema/services/request-contexts/session/stores http://localhost:8080/schema/services-request-contexts-session-stores.xsd
                 http://www.springframework.org/schema/beans http://localhost:8080/schema/www.springframework.org/schema/beans/spring-beans.xsd
             ">
             
	<beans:description>父容器所在的配置</beans:description>

	
	<services:property-placeholder location="classpath:otter.properties">
		<property key="component">common</property>
	</services:property-placeholder>

	
	<beans:import resource="common/webx-component-and-root.xml" />

	
	<beans:import resource="common/pipeline-exception.xml" />

	
	<beans:import resource="common/resources.xml" />

	
	<beans:import resource="common/uris.xml" />

	
	<beans:import resource="applicationContext.xml" />

	
    <services:webx-configuration>
        
        <productionMode>${otter.manager.productionMode:true}</productionMode>
        <components defaultComponent="home" />
    </services:webx-configuration>

	
	 <services:request-contexts>
		<request-contexts:basic />
        <request-contexts:buffered />
        <request-contexts:lazy-commit />
        <request-contexts:parser>
         	<filters>
                <parser-filters:uploaded-file-whitelist extensions="jpg, gif, png" />
            </filters>
        </request-contexts:parser>
		<request-contexts:set-locale defaultLocale="zh_CN" defaultCharset="UTF-8" />
		<request-contexts:session forceExpirationPeriod="14400">
			<stores>
                <session-stores:cookie-store id="temporaryCookie">
                    <cookie name="OTTER_WEBX_JSESSIONID" />
                </session-stores:cookie-store>
            </stores>
            <store-mappings>
                <match name="*" store="temporaryCookie" />
            </store-mappings>
            <interceptors>
                <session-interceptors:lifecycle-logger />
                <session-interceptors:attribute-whitelist>
                    <attribute name="_csrf_token" />
                    <attribute name="_lang" />
                    <attribute name="managerUser" />
                </session-interceptors:attribute-whitelist>
            </interceptors>
		</request-contexts:session>
	</services:request-contexts>

	
	<services:upload sizeMax="5M" />

	
	<services:pull>
		<pull-factories:utils />
		<pull-factories:page-tool />
		<pull-factories:control-tool detailLevel="throwException" />
		<pull-factories:uris-tool />
		<pull-factories:bean-tool scope="global" id="numberFormat"
			class="com.alibaba.otter.manager.web.common.NumberFormatUtil" />
	</services:pull>

	
	 <services:module-loader>
        <ml-factories:class-modules>
            <search-packages type="$1" packages="com.alibaba.otter.manager.web.home.module.*" />
        </ml-factories:class-modules>
    </services:module-loader>
    
	
	<beans:bean id="urlAnalyze"
		class="com.alibaba.otter.manager.web.webx.valve.auth.RegExpURLAnalyze">
		<beans:property name="operator">
			<beans:bean
				class="com.alibaba.otter.manager.web.webx.valve.auth.AuthorizeProtected">
				<beans:property name="urlProtected">
					<beans:value>
						/.*check.*\.htm
						/.*conflictStatList\.htm
						/.*conflict_stat_list\.htm
						/.*behaviorHistoryCurve\.htm
						/.*behavior_history_curve\.htm
						/.*List\.htm
						/.*Info\.htm
						/.*\_list\.htm
						/.*\_info\.htm
						/.*\_detail\.htm
						/.*\_path\.htm
						/.*search.*\.htm
						/.*analysis.*\.htm
						/.*record.*\.htm
						/.*Record.*\.htm
						/.*alarmRuleList.*\.htm
						/.*alarm_rule_list.*\.htm
						/.*init_sql.*\.htm
						/.*wiki_guide.*\.htm
					</beans:value>
				</beans:property>
				<beans:property name="actionProtected">
					<beans:value>
						userAction|logout
						.*Action|search
					</beans:value>
				</beans:property>
			</beans:bean>
		</beans:property>
		<beans:property name="anonymous">
			<beans:bean
				class="com.alibaba.otter.manager.web.webx.valve.auth.AuthorizeProtected">
				<beans:property name="urlProtected">
					<beans:value>
						/
						/dwr/.*
						/js/.*
						/css/.*
						/images/.*
						/monitor/.*
						/.*\.css
						/.*\.png
						/.*\.js
						/.*login\.htm
						/.*error\.htm
						/.*Error\.htm
						/.*\_error\.htm
						/.*forbidden\.htm
					</beans:value>
				</beans:property>
				<beans:property name="actionProtected">
					<beans:value>
						userAction|login
					</beans:value>
				</beans:property>
			</beans:bean>
		</beans:property>
		<beans:property name="admin">
			<beans:bean
				class="com.alibaba.otter.manager.web.webx.valve.auth.AuthorizeProtected">
				<beans:property name="urlProtected">
					<beans:value>
						/.*add.*\.htm
						/.*edit.*\.htm
						/.*select.*\.htm
						/.*userManager\.htm
						/.*user_manager\.htm
						/.*system_reduction\.htm
						/.*system_parameter\.htm
						/.*systemParameter\.htm
					</beans:value>
				</beans:property>
				<beans:property name="actionProtected">
					<beans:value>
						.*Action|add
						.*Action|edit
						.*Action|delete
						.*Action|status
						.*Action|restart
						.*Action|all_status
						DataMatrixAction|switch
						SwitchWarmupAction|switch
						SwitchWarmupAction|restart
					</beans:value>
				</beans:property>
			</beans:bean>
		</beans:property>
	</beans:bean>
	<beans:bean id="apiAuthService" class="com.alibaba.otter.manager.web.common.api.DefaultApiAuthService" />
	
	<beans:bean class="org.springframework.beans.factory.config.CustomEditorConfigurer" depends-on="arbitrateConfigImpl">  
	   <beans:property name="customEditors">  
		    <beans:map>  
		       <beans:entry key="com.alibaba.otter.manager.web.webx.valve.auth.url.URLProtected" value="com.alibaba.otter.manager.web.webx.valve.auth.url.URLProtectedEditor" /> 
		       <beans:entry key="com.alibaba.otter.manager.web.webx.valve.auth.action.ActionProtected" value="com.alibaba.otter.manager.web.webx.valve.auth.action.ActionProtectedEditor" /> 
		    </beans:map>
	   </beans:property>
	</beans:bean>
</beans:beans>
`

**Comment by xdkaka** [comment]
太危险了，发现`otter.domainName`不管配置什么，都能通过IP访问到

谷歌上随便搜了下，一大堆对外暴露的。。。。

**Comment by chenbt-hz** [comment]
> 直接修改webx.xml配置文件即可
> 
> 允许匿名用户访问js,css等文件，并允许调用login的api即可。
> 
> 可参照这如下的webx.xml：
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <beans:beans xmlns:beans="http://www.springframework.org/schema/beans"
> 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:p="http://www.springframework.org/schema/p"
> 	xmlns:services="http://www.alibaba.com/schema/services"
> 	xmlns:ml-adapters="http://www.alibaba.com/schema/services/module-loader/adapters"
> 	xmlns:ml-factories="http://www.alibaba.com/schema/services/module-loader/factories"
> 	xmlns:pull-factories="http://www.alibaba.com/schema/services/pull/factories"
> 	xmlns:request-contexts="http://www.alibaba.com/schema/services/request-contexts"
> 	xmlns:basic-interceptors="http://www.alibaba.com/schema/services/request-contexts/basic/interceptors"
> 	xmlns:parser-filters="http://www.alibaba.com/schema/services/request-contexts/parser/filters"
> 	xmlns:session-encoders="http://www.alibaba.com/schema/services/request-contexts/session/encoders"
> 	xmlns:session-idgens="http://www.alibaba.com/schema/services/request-contexts/session/idgens"
> 	xmlns:session-interceptors="http://www.alibaba.com/schema/services/request-contexts/session/interceptors"
> 	xmlns:model-encoders="http://www.alibaba.com/schema/services/request-contexts/session/model-encoders"
> 	xmlns:session-stores="http://www.alibaba.com/schema/services/request-contexts/session/stores"
> 	xsi:schemaLocation="
>                  http://www.alibaba.com/schema/services http://localhost:8080/schema/services.xsd
>                  http://www.alibaba.com/schema/services/module-loader/adapters http://localhost:8080/schema/services-module-loader-adapters.xsd
>                  http://www.alibaba.com/schema/services/module-loader/factories http://localhost:8080/schema/services-module-loader-factories.xsd
>                  http://www.alibaba.com/schema/services/pull/factories http://localhost:8080/schema/services-pull-factories.xsd
>                  http://www.alibaba.com/schema/services/request-contexts http://localhost:8080/schema/services-request-contexts.xsd
>                  http://www.alibaba.com/schema/services/request-contexts/basic/interceptors http://localhost:8080/schema/services-request-contexts-basic-interceptors.xsd
>                  http://www.alibaba.com/schema/services/request-contexts/parser/filters http://localhost:8080/schema/services-request-contexts-parser-filters.xsd
>                  http://www.alibaba.com/schema/services/request-contexts/session/encoders http://localhost:8080/schema/services-request-contexts-session-encoders.xsd
>                  http://www.alibaba.com/schema/services/request-contexts/session/idgens http://localhost:8080/schema/services-request-contexts-session-idgens.xsd
>                  http://www.alibaba.com/schema/services/request-contexts/session/interceptors http://localhost:8080/schema/services-request-contexts-session-interceptors.xsd
>                  http://www.alibaba.com/schema/services/request-contexts/session/model-encoders http://localhost:8080/schema/services-request-contexts-session-model-encoders.xsd
>                  http://www.alibaba.com/schema/services/request-contexts/session/stores http://localhost:8080/schema/services-request-contexts-session-stores.xsd
>                  http://www.springframework.org/schema/beans http://localhost:8080/schema/www.springframework.org/schema/beans/spring-beans.xsd
>              ">
>              
> 	<beans:description>父容器所在的配置</beans:description>
> 
> 	
> 	<services:property-placeholder location="classpath:otter.properties">
> 		<property key="component">common</property>
> 	</services:property-placeholder>
> 
> 	
> 	<beans:import resource="common/webx-component-and-root.xml" />
> 
> 	
> 	<beans:import resource="common/pipeline-exception.xml" />
> 
> 	
> 	<beans:import resource="common/resources.xml" />
> 
> 	
> 	<beans:import resource="common/uris.xml" />
> 
> 	
> 	<beans:import resource="applicationContext.xml" />
> 
> 	
>     <services:webx-configuration>
>         
>         <productionMode>${otter.manager.productionMode:true}</productionMode>
>         <components defaultComponent="home" />
>     </services:webx-configuration>
> 
> 	
> 	 <services:request-contexts>
> 		<request-contexts:basic />
>         <request-contexts:buffered />
>         <request-contexts:lazy-commit />
>         <request-contexts:parser>
>          	<filters>
>                 <parser-filters:uploaded-file-whitelist extensions="jpg, gif, png" />
>             </filters>
>         </request-contexts:parser>
> 		<request-contexts:set-locale defaultLocale="zh_CN" defaultCharset="UTF-8" />
> 		<request-contexts:session forceExpirationPeriod="14400">
> 			<stores>
>                 <session-stores:cookie-store id="temporaryCookie">
>                     <cookie name="OTTER_WEBX_JSESSIONID" />
>                 </session-stores:cookie-store>
>             </stores>
>             <store-mappings>
>                 <match name="*" store="temporaryCookie" />
>             </store-mappings>
>             <interceptors>
>                 <session-interceptors:lifecycle-logger />
>                 <session-interceptors:attribute-whitelist>
>                     <attribute name="_csrf_token" />
>                     <attribute name="_lang" />
>                     <attribute name="managerUser" />
>                 </session-interceptors:attribute-whitelist>
>             </interceptors>
> 		</request-contexts:session>
> 	</services:request-contexts>
> 
> 	
> 	<services:upload sizeMax="5M" />
> 
> 	
> 	<services:pull>
> 		<pull-factories:utils />
> 		<pull-factories:page-tool />
> 		<pull-factories:control-tool detailLevel="throwException" />
> 		<pull-factories:uris-tool />
> 		<pull-factories:bean-tool scope="global" id="numberFormat"
> 			class="com.alibaba.otter.manager.web.common.NumberFormatUtil" />
> 	</services:pull>
> 
> 	
> 	 <services:module-loader>
>         <ml-factories:class-modules>
>             <search-packages type="$1" packages="com.alibaba.otter.manager.web.home.module.*" />
>         </ml-factories:class-modules>
>     </services:module-loader>
>     
> 	
> 	<beans:bean id="urlAnalyze"
> 		class="com.alibaba.otter.manager.web.webx.valve.auth.RegExpURLAnalyze">
> 		<beans:property name="operator">
> 			<beans:bean
> 				class="com.alibaba.otter.manager.web.webx.valve.auth.AuthorizeProtected">
> 				<beans:property name="urlProtected">
> 					<beans:value>
> 						/.*check.*\.htm
> 						/.*conflictStatList\.htm
> 						/.*conflict_stat_list\.htm
> 						/.*behaviorHistoryCurve\.htm
> 						/.*behavior_history_curve\.htm
> 						/.*List\.htm
> 						/.*Info\.htm
> 						/.*\_list\.htm
> 						/.*\_info\.htm
> 						/.*\_detail\.htm
> 						/.*\_path\.htm
> 						/.*search.*\.htm
> 						/.*analysis.*\.htm
> 						/.*record.*\.htm
> 						/.*Record.*\.htm
> 						/.*alarmRuleList.*\.htm
> 						/.*alarm_rule_list.*\.htm
> 						/.*init_sql.*\.htm
> 						/.*wiki_guide.*\.htm
> 					</beans:value>
> 				</beans:property>
> 				<beans:property name="actionProtected">
> 					<beans:value>
> 						userAction|logout
> 						.*Action|search
> 					</beans:value>
> 				</beans:property>
> 			</beans:bean>
> 		</beans:property>
> 		<beans:property name="anonymous">
> 			<beans:bean
> 				class="com.alibaba.otter.manager.web.webx.valve.auth.AuthorizeProtected">
> 				<beans:property name="urlProtected">
> 					<beans:value>
> 						/
> 						/dwr/.*
> 						/js/.*
> 						/css/.*
> 						/images/.*
> 						/monitor/.*
> 						/.*\.css
> 						/.*\.png
> 						/.*\.js
> 						/.*login\.htm
> 						/.*error\.htm
> 						/.*Error\.htm
> 						/.*\_error\.htm
> 						/.*forbidden\.htm
> 					</beans:value>
> 				</beans:property>
> 				<beans:property name="actionProtected">
> 					<beans:value>
> 						userAction|login
> 					</beans:value>
> 				</beans:property>
> 			</beans:bean>
> 		</beans:property>
> 		<beans:property name="admin">
> 			<beans:bean
> 				class="com.alibaba.otter.manager.web.webx.valve.auth.AuthorizeProtected">
> 				<beans:property name="urlProtected">
> 					<beans:value>
> 						/.*add.*\.htm
> 						/.*edit.*\.htm
> 						/.*select.*\.htm
> 						/.*userManager\.htm
> 						/.*user_manager\.htm
> 						/.*system_reduction\.htm
> 						/.*system_parameter\.htm
> 						/.*systemParameter\.htm
> 					</beans:value>
> 				</beans:property>
> 				<beans:property name="actionProtected">
> 					<beans:value>
> 						.*Action|add
> 						.*Action|edit
> 						.*Action|delete
> 						.*Action|status
> 						.*Action|restart
> 						.*Action|all_status
> 						DataMatrixAction|switch
> 						SwitchWarmupAction|switch
> 						SwitchWarmupAction|restart
> 					</beans:value>
> 				</beans:property>
> 			</beans:bean>
> 		</beans:property>
> 	</beans:bean>
> 	<beans:bean id="apiAuthService" class="com.alibaba.otter.manager.web.common.api.DefaultApiAuthService" />
> 	
> 	<beans:bean class="org.springframework.beans.factory.config.CustomEditorConfigurer" depends-on="arbitrateConfigImpl">  
> 	   <beans:property name="customEditors">  
> 	   <beans:property name="customEditors">  
> 		    <beans:map>
> 		       <beans:entry key="com.alibaba.otter.manager.web.webx.valve.auth.url.URLProtected" value="com.alibaba.otter.manager.web.webx.valve.auth.url.URLProtectedEditor" /> 
> 		       <beans:entry key="com.alibaba.otter.manager.web.webx.valve.auth.action.ActionProtected" value="com.alibaba.otter.manager.web.webx.valve.auth.action.ActionProtectedEditor" /> 
> 		    </beans:map>
> 	   </beans:property>
> 	</beans:bean>
> </beans:beans>
> ```

直接修改webx.xml是可行的，但是我这边4.2.18直接复制该配置无法运行web页面。
因此在默认配置的基础上，自己修改urlProtected实现禁止匿名用户访问相关的url,跟引用部分其实是一样的，其中admin 权限包含operator 权限包含operator 权限anonymous。
anonymous只保留login、error等基础页面的访问权限。把其他页面权限驾到operator或者admin中
