### ISSUE TITLE
update 字段 null-->空串''时 MySQLSyntaxErrorException

### ISSUE THREAD

**Issue by tmriver** [alibaba/otter#299]
1，表结构
CREATE TABLE `User` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `mobile` varchar(255) DEFAULT NULL,
  `num` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

2，现有数据
INSERT INTO `User` VALUES (1, 'aaabcdf', '11', null);

3,update 操作
update User set num='' where id=1;

4，执行 mysqlbinlog --base64-output=decode-rows -v  mysql-bin.000009
#170407 17:29:39 server id 91  end_log_pos 426 CRC32 0x4a097dfe         Update_rows: table id 109 flags: STMT_END_F
###   @4=''

5，开启同步，
解析出的EventData
[EventData[tableId=4041,tableName=User,schemaName=test,eventType=UPDATE,executeTime=1491557379000,oldKeys=[],keys=[EventColumn[index=0,columnType=4,columnName=id,columnValue=1,isNull=false,isKey=true,isUpdate=true]],columns=[],size=74,pairId=-1,sql=<null>,ddlSchemaName=<null>,syncMode=<null>,syncConsistency=<null>,remedy=false,hint=<null>,withoutSchema=false,canLoadDDL=false,logfileIndex=9,logfileOffset=352]]
生成的sql
update test.User set where ( `id` = ? )

报错：
:----------------- 
- PairId: 24 , TableId: 4,040 , EventType : U , Time : 1491557379000 
- Consistency : , Mode : 
----------------- 
---Pks 
EventColumn[index=0,columnType=4,columnName=id,columnValue=1,isNull=false,isKey=true,isUpdate=true] 
---oldPks 

---Columns 

---Sql 
update test.User set where ( `id` = ? ) 

Caused by: java.util.concurrent.ExecutionException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [update test.User set where ( `id` = ? )]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where ( `id` = 1 )' at line 1

**Comment by tmriver** [comment]
调用栈：
CanalEntry$RowChange$Builder(AbstractMessageLite$Builder<BuilderType>).mergeFrom(ByteString) line: 122	
CanalEntry$RowChange$Builder(AbstractMessage$Builder<BuilderType>).mergeFrom(ByteString) line: 695	
CanalEntry$RowChange.parseFrom(ByteString) line: 4728	

想改的话比较危险。

暂时考虑直接跳过这种EventData。但这样会丢失 null --> ‘’ 操作

**Comment by tmriver** [comment]
或者在rowChange = RowChange.parseFrom(entry.getStoreValue());之后
再做一次检查，如果所有字段column.getUpdated()都为false的话，再逐个比较重置一下。

**Comment by agapple** [comment]
印象中之前有人提交过一次PR，你再更新一下最新版试试？

**Comment by tmriver** [comment]
可以了，升级到v4.2.13就可以了，原来用的是4.2.13-snapshot，依赖的是canal-parse-1.0.20。
https://github.com/alibaba/canal/issues/135这里修复的。
这几天忙其他事情了，没顾上这个。
另外v4.2.14不支持mysql5.5，期待v4.2.15

非常感谢！
