### ISSUE TITLE
otter-manager为什么只能添加嵌入式的canal节点？（独立服务那个选项无法选中）

### ISSUE THREAD

**Issue by defconzhou** [alibaba/otter#301]
如果添加的是嵌入式的，canal自己本身能HA吗？

![image](https://cloud.githubusercontent.com/assets/2505581/24939692/b1f5eba2-1f71-11e7-98a9-9fda9113634a.png)

**Comment by agapple** [comment]
是的，高可用是通过otter调度来保证的

**Comment by defconzhou** [comment]
谢谢！
