### ISSUE TITLE
不能全量同步

### ISSUE THREAD

**Issue by dearplain** [alibaba/otter#303]
两个mysql，开启了binlog，初始化了retl。
表结构如下：
CREATE TABLE  `test`.`example` (
  `id` int(11)  NOT NULL AUTO_INCREMENT,
  `name` varchar(32) COLLATE utf8_bin DEFAULT NULL ,
   PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
在example插入10多条数据，然后起双向同步，
执行：
insert into retl.retl_buffer(ID,TABLE_ID, FULL_NAME,TYPE,PK_DATA,GMT_CREATE,GMT_MODIFIED) (select null,0,'test.example','U','id',now(),now() from test.example);
显示10多条数据受到影响，但是另一个mysql的test.example还是空。

**Comment by dearplain** [comment]
canal也配了，能正常双向同步。

**Comment by agapple** [comment]
otter本身不支持全量，可以看一下wiki
