### ISSUE TITLE
 otter多Ａ机房同步

### ISSUE THREAD

**Issue by clover1983** [alibaba/otter#308]
请问谁做过ｏｔｔｅｒ多Ａ机房同步？
如果有四个机房，香港，美国，澳洲，法国，如果实现多Ａ同步，不是单向同步，而是每个节点都可以写入，最终数据一致性？

下面这个架构可行吗？
http://blog.csdn.net/zhxdick/article/details/50808040
![20160306094412805](https://cloud.githubusercontent.com/assets/14799412/25237006/71652462-25b7-11e7-883a-34abec5fae5b.png)

**Comment by agapple** [comment]
可行的

**Comment by 2207085293** [comment]
这个是如何实现的呢

**Comment by 2207085293** [comment]
我配置了多个channel，每个channel两个 Pipeline，在第二个channel的pipeline时提示：canal已经被其他pipeline所关联

**Comment by agapple** [comment]
需要配置多个canal

**Comment by nettm** [comment]
官方文档提到了多A同步，有配置过的吗？

 多A同步
基于以上的单向/双向/双A/级联同步，可以随意搭建出多A同步，不过目前受限于同步数据的一致性算法，只能通过星形辐射，通过级联同步的方式保证全局多A机房的数据一致性. 
比如图中B和C之前的一致性同步，需要通过主站点A来保证.

**Comment by hylyLLL** [comment]
> 我配置了多个channel，每个channel两个 Pipeline，在第二个channel的pipeline时提示：canal已经被其他pipeline所关联

你好，请问，你解决了该问题吗？

**Comment by zgldh** [comment]
> Referenc

在otter manager里新建一个canal即可。 两个canal可以指向同一个数据库的。
