### ISSUE TITLE
java.sql.SQLException: Incorrect string value: '\xEF\xBF\xBD\xEF\xBF\xBD...' for column 'tmall_stu_nick' at row 1,编码均为UTF8，同步报此错误是什么问题

### ISSUE THREAD

**Issue by angelmm126** [alibaba/otter#314]
pid:7 nid:1 exception:setl:com.alibaba.otter.node.etl.load.exception.LoadException: java.util.concurrent.ExecutionException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [insert into `tmall`.`tmall_sub_order`(`tmall_order_id` , `tmall_sub_order_id` , `tmall_num_id` , `tmall_stu_nick` , `tmall_outer_id` , `tmall_num` , `tmall_title` , `tmall_item_price` , `tmall_discount_fee` , `tmall_secure_fee` , `tmall_payment` , `tmall_sub_order_status` , `biz_status` , `err_msg` , `payment_time` , `create_time` , `update_time` , `id`) values (? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ?) on duplicate key update `tmall_order_id`=values(`tmall_order_id`) , `tmall_sub_order_id`=values(`tmall_sub_order_id`) , `tmall_num_id`=values(`tmall_num_id`) , `tmall_stu_nick`=values(`tmall_stu_nick`) , `tmall_outer_id`=values(`tmall_outer_id`) , `tmall_num`=values(`tmall_num`) , `tmall_title`=values(`tmall_title`) , `tmall_item_price`=values(`tmall_item_price`) , `tmall_discount_fee`=values(`tmall_discount_fee`) , `tmall_secure_fee`=values(`tmall_secure_fee`) , `tmall_payment`=values(`tmall_payment`) , `tmall_sub_order_status`=values(`tmall_sub_order_status`) , `biz_status`=values(`biz_status`) , `err_msg`=values(`err_msg`) , `payment_time`=values(`payment_time`) , `create_time`=values(`create_time`) , `update_time`=values(`update_time`) , `id`=values(`id`)]; SQL state [HY000]; error code [1366]; Incorrect string value: '\xEF\xBF\xBD\xEF\xBF\xBD...' for column 'tmall_stu_nick' at row 1; nested exception is java.sql.SQLException: Incorrect string value: '\xEF\xBF\xBD\xEF\xBF\xBD...' for column 'tmall_stu_nick' at row 1

字符集均为UTF-8，请教大神，咋解决？

**Comment by qdql** [comment]
改成utf8mb4

**Comment by angelmm126** [comment]
找到原因了，库为UTF8,但是表为GBK
