### ISSUE TITLE
manager的canal配置中的默认连接超时设置不起作用

### ISSUE THREAD

**Issue by operands** [alibaba/otter#317]
我在canal配置上看到默认连接超时是30s，个人理解是canal通过socket读取binlog，超过30s没有数据就会报timeout异常，不知道理解对不对？
我看代码中是通过SocketChannel.read获取数据库的binlog的（DirectLogFetcher.fetch0方法），但这个方法貌似是永久阻塞的，不支持超时设置（见http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4614802）
因此canal的默认连接超时配置不起作用，我的试验结果也确实是这样，请问设计者这个超时设置是如何工作的呢？

**Comment by agapple** [comment]
这块也有人给我反馈了，我近期会修复一下

**Comment by agapple** [comment]
4.2.15已经修复
