### ISSUE TITLE
同步过程中创建无数database connection

### ISSUE THREAD

**Issue by conglun** [alibaba/otter#320]
pool size设置为5， 但后台数据库出现过百连接； 

## otter communication pool size
otter.communication.pool.size = 5

mysql 设置
+-----------------------------+----------+
| Variable_name               | Value    |
+-----------------------------+----------+
| connect_timeout             | 10       |
| delayed_insert_timeout      | 300      |
| have_statement_timeout      | YES      |
| innodb_flush_log_at_timeout | 1        |
| innodb_lock_wait_timeout    | 50       |
| innodb_rollback_on_timeout  | OFF      |
| interactive_timeout         | 28800    |
| lock_wait_timeout           | 31536000 |
| net_read_timeout            | 120      |
| net_write_timeout           | 120      |
| rpl_stop_slave_timeout      | 31536000 |
| slave_net_timeout           | 60       |
| wait_timeout                | 28800    |
+-----------------------------+----------+

**Comment by agapple** [comment]
这参数不是指数据库的链接池大小哦
