### ISSUE TITLE
主库表结构修改引起的问题？请问怎么解决，谢谢！

### ISSUE THREAD

**Issue by yyangh** [alibaba/otter#322]
A到B的单向同步
otter安装好以后，一开始一切同步正常，B的数据比A滞后10天，在B开始同步到第九天的时候，A的表t_goods_item的表增加了三个字段range_entity_type， type_id,  range_id，otter却报错了，报错内容如下：

pid:6 nid:1 exception:setl:com.alibaba.otter.node.etl.transform.exception.TransformException: range_entity_type is not found in Table [name=t_goods_item; 14 columns] and source : goods.(.*).(.*)

会不会A的表结构修改后，node检查的时候，发现两边表结构不一致，而停止同步？
怀疑是不是跟反查机制有关，node去反查的时候，发现两边表结构不一致，就报异常了？请大神指教怎么解决！谢谢！！

**Comment by agapple** [comment]
停用启用一下任务，应该是之前版本的bug，DDL变化时内存缓存未更新

**Comment by agapple** [comment]
4.2.15已经修复

**Comment by Kinger0216** [comment]
A-B双向同步，A库单写，同样问题，启停任务无效。
