### ISSUE TITLE
双向同步主A中新建表的中文注释到B库里变成乱码

### ISSUE THREAD

**Issue by ojeo** [alibaba/otter#329]
双向同步主A中新建表的中文注释到B库里变成乱码
数据库编码都为utf8
otter里所有配置编码都是utf8
表里的中文数据同步正常，不会乱码
只有新建表的字段注释及表注释会乱码
请  @agapple  问如何解决

**Comment by tmriver** [comment]
新增表可以自动同步过去？求指教/文档/链接
我都是手动添加配置的

**Comment by agapple** [comment]
canal解析里的编码配置设置为utf8了么？
