### ISSUE TITLE
线上运行的mysql.怎么把老数据也同步进来？保证单向同步数据的一致性

### ISSUE THREAD

**Issue by lxshopping** [alibaba/otter#331]
线上运行的mysql已经有100多G数据，首先将备份数据在异地服务器上还原，然后搭建了otter实现了实时同步，但是在备份数据导入的这段时间内otter并没有开始同步，请问这段时间内缺失的老数据怎么能够同步回来？

**Comment by agapple** [comment]
历史数据需要先做一次全量

**Comment by lxshopping** [comment]
历史数据不能停止，否则业务有很大影响，在不停止的情况下怎么进行全量同步

**Comment by luyee** [comment]
同问  怎么做全量好！ 全量[mysqldump(记录位点)+source]+otter 指定位点开始增量 可以不影响线上业务！ 但是数据量大了  source 花费时间太久

**Comment by 307545758** [comment]
历史数据先做个热全备，同时记录下pos点信息，恢复到目标环境，然后将pos点信息写入到canal中，然后配置channel 开启同步！

**Comment by 307545758** [comment]
使用innobackupex

**Comment by luyee** [comment]
多谢@307545758  先试试

**Comment by luyee** [comment]
innobackupex 到单个表 还是挺麻烦的 [Transporting tablespace from MySQL 5.6 to MySQL 5.7 (case study)](https://www.percona.com/blog/2015/12/01/how-to-transport-tablespace-from-mysql-5-6-to-mysql-5-7/)

**Comment by luyee** [comment]
持续更新[debezium](https://github.com/debezium/debezium)可以支持全量+增量
原理[MySQL snapshotter is not guaranteed to give a consistent snapshot](https://issues.jboss.org/projects/DBZ/issues/DBZ-210?filter=allopenissues)
