### ISSUE TITLE
otter能支持json数据类型

### ISSUE THREAD

**Issue by deanjin** [alibaba/otter#333]
问下otter能支持json数据类型，我们导入的时候出现这个错误。

 Data truncation: Cannot create a JSON value from a string with CHARACTER SET 'binary'.; nested exception is com.mysql.jdbc.MysqlDataTruncation: Data truncation: Cannot create a JSON value from a string with CHARACTER SET 'binary'.
谢谢！

**Comment by agapple** [comment]
需要升级mysql driver版本

**Comment by agapple** [comment]
尝试一下4.2.15版本吧
