### ISSUE TITLE
如何保障传输时走加密通道

### ISSUE THREAD

**Issue by handou** [alibaba/otter#337]
请问如何保障binlog文件同步时走加密通道，比如sftp，或者说传输前对文件加密再传输，接受时先解密再处理文件内容？

**Comment by agapple** [comment]
看一下wiki，有加密处理的选项

**Comment by phillipyuan** [comment]
您说的加密是不是指pipeline 高级设置里面的“文件传输加密”？
如果是的话，我想问在哪个配置文件或者页面可以设置pipeline ？
