### ISSUE TITLE
自由门怎么才能全表同步

### ISSUE THREAD

**Issue by swords1999** [alibaba/otter#340]
环境： otter、retl库、源库在一台服务器上。但是往retl_buffer表里面用插入记录，如：
insert into retl_buffer(TABLE_ID, FULL_NAME,TYPE,PK_DATA,GMT_CREATE,GMT_MODIFIED) values (0,'test.sales','I','id',now(),now());
但是没有触发全表同步，只能同步更改的那一行。看了所有的issues都没找到解决方法。
一定要把所有行都更新一下才可以吗？

**Comment by agapple** [comment]
是的，需要把所有行的id插入

**Comment by swords1999** [comment]
好的，多谢。

**Comment by hylyLLL** [comment]
> 好的，多谢。

请问，插入到retl_buffer中的数据同步完过后，需要将ret_buffer中的数据删除吗？
