### ISSUE TITLE
多个源 自由门有用嘛

### ISSUE THREAD

**Issue by luyee** [alibaba/otter#341]
既然自由门 必须 otter、retl库、源库同一个server

多个源就不能用自由门全量同步了？ 多个源怎么做全量？

基于自定义位点全量可以嘛，比如配置自定义位点为第一个journalName的最小position：  {"journalName":"mysql-bin.000001","position":4};

**Comment by agapple** [comment]
每个源一个通道，每个源里单独处理全量

**Comment by luyee** [comment]
binlog 文件不保存全部，所以全量暂时用mysqldump+mysql命令行导入，但是速度较慢；几千万还好，上亿起码几个小时吧。。。  准备测试下innobackupex。。。其他工具似乎不能很好滴支持position位点 +线上业务更新。。。
