### ISSUE TITLE
otter做数据同步，中文乱码问题

### ISSUE THREAD

**Issue by dnfhujun** [alibaba/otter#343]
场景是这样的，
   A数据库版本5.0，存储引擎是MyISAM,默认编码是GBK
   B数据库版本5.6，存储引擎InnoDB,默认编码是UTF8

需要将A库中的表同步到B数据库，但是过去之后的中文发现是乱码的？有哪位大神可以解答下

**Comment by agapple** [comment]
canal配置里选择GBK编码，目标库B选择UTF8编码
