### ISSUE TITLE
MySQL5.5同步MySQL5.6

### ISSUE THREAD

**Issue by EternalSpring** [alibaba/otter#349]
请教下群主，双主模式，希望跨版本同步，不知道otter是否兼容？

**Comment by swords1999** [comment]
不兼容，有BUG，需要升级到1.0.24

**Comment by EternalSpring** [comment]
嗯嗯，感谢回答，想请教下具体的bug是什么？我看最新版本是嵌入canal 1.0.23，升级1.0.24是需要修改otter里面的canal模块？

**Comment by swords1999** [comment]
你直接把code拿下来编译就好了。

**Comment by agapple** [comment]
尝试一下4.2.15版本吧
