### ISSUE TITLE
OTTER同步循环卡住的问题

### ISSUE THREAD

**Issue by yangh214** [alibaba/otter#357]
现在从MYSQL到ORACLE的同步，大批量的更新，时常会卡住，不停的刷新之前刷过的数据，有人解决这个bug么

**Comment by agapple** [comment]
看一下FAQ，是否是监控位点更新处理的

**Comment by yangh214** [comment]
我是开了监控，那你意思是由于监控导致的？是不是关了监控就好？

**Comment by agapple** [comment]
监控的原理是识别位点更新，如果超过10分钟还没更新，就会自动重启任务.  因为大事务，10分钟之内还没同步完(位点更新是以事务结束才更新)

**Comment by agapple** [comment]
解决：1.  避免超大事务  2.  调大位点监控时间，保证时间内能处理完大数据的同步

**Comment by yangh214** [comment]
把监控暂时关了好一些，谢谢
