### ISSUE TITLE
怎样配置域名访问otter manager管理后台？？

### ISSUE THREAD

**Issue by Simonfld** [alibaba/otter#361]
我nginx配置域名 otter.admin.my.com  
upstream 
192.168.1.100:8080
192.168.1.101:8080

用otter.admin.my.com访问，能打开页面，然后点击登录时，地址栏跳转到  
http://192.168.1.101:8080/?action=userAction&eventSubmitDoLogout=true

这是什么情况啊？？  怎样配置能解决域名访问

**Comment by agapple** [comment]
otter.properties里domainName改成域名
