### ISSUE TITLE
canal_list.htm canal列表页面打开奇慢，这个是什么原因？  

### ISSUE THREAD

**Issue by Simonfld** [alibaba/otter#364]
怎么解决？

**Comment by liyongcun** [comment]
同感，如果配置多了，这个页面非常满

**Comment by shanexu** [comment]
貌似是配置了域名之后就会非常慢！！

**Comment by Simonfld** [comment]
@liyongcun @shanexu 问题找到了，manager的机器必须配置mysql机器的host，慢是因为解析host慢

**Comment by linqh1** [comment]
不是这个原因吧。

我特地在本地调试了下，CanalList.execute 执行的时间还可以忍受，但是之后到浏览器响应成功就特别慢。似乎是citrus-webx这个jar包的哪个处理流程特别慢
