### ISSUE TITLE
数据表使用正则匹配时同步不起做用，求解

### ISSUE THREAD

**Issue by wl198972** [alibaba/otter#365]
序号 | 源表 | 目标表 | 权重 | FileSize | FileCount | DeleteCount | UpdateCount | InsertCount | 最后同步时间 | 操作
8 | modb_bl.^(bns_).*$ | modb_bl_t.^(bns_).*$ | 5 | 0 B | 0 | 0 | 0 | 0 |   | 查看 行为曲线

**Comment by luyee** [comment]
先看下表能不能出来吧 数据表-->编辑-->查询Schema&Table

**Comment by wl198972** [comment]
可以查到，但是开启同步的时候不成功，没有数据

**Comment by wl198972** [comment]
自己顶一下吧...

**Comment by zhumt** [comment]
请问有解决了吗，我也是配了十几张表有一张同步不了

**Comment by wl198972** [comment]
还没有，单表配置的，没有使用正则，300多张表....

**Comment by zzcclp** [comment]
请问这个问题解决了吗？同样遇到配置稍微复杂的正则，就不同步，select还是能获取：

**Comment by agapple** [comment]
一般正则写的比较复杂，主要是想过滤部分表，可以在canal配置里添加黑名单模式

**Comment by zzcclp** [comment]
试过，也不起作用

**Comment by linqh1** [comment]
同样有这个疑问, 查询Schema&Table可以显示n张表, 但是实际却无法同步. 
这个issue不该关啊

**Comment by linqh1** [comment]
> 请问这个问题解决了吗？同样遇到配置稍微复杂的正则，就不同步，select还是能获取：
> ^(?!batch_|step_).*

我也是这么配置的, 无法同步...
