### ISSUE TITLE
otter是是否可以提供相关配置API？

### ISSUE THREAD

**Issue by vzong** [alibaba/otter#369]
otter是否可以提供配置相关的API？每次配置都需要添加channel，canal，数据源，table，Pipeline，映射关系列表等一系列的步骤，手动点网页效率太低了，尤其在大规模应用的时候效率低下。
目前我这边就有一个需求，填写源头和目的端，自动化配置好复制关系。
看了下源码，配置的过程不是简单的SQL插入，还有一些node通信调用，所以不能指望Insert相关配置数据就能解决。如果使用HTTP POST的手段，则会被CheckCsrfTokenValve给挡掉返回500错误。
请问能提否提供相应的API，谢谢！

**Comment by agapple** [comment]
暂时没有，目前定位为工具
