### ISSUE TITLE
第三方包有些旧了，有升级计划吗? 

### ISSUE THREAD

**Issue by slieer** [alibaba/otter#378]
spring， jetty, guava的版本，可以说都是老掉牙了。
还引用了以下库：
http://jtester.googlecode.com/svn/m2
google code 不是停了好多年了吗？
要不，把我加进来吧！

**Comment by agapple** [comment]
你可以提交一下优化的PR

**Comment by liyongcun** [comment]
我已经基于guava 19修改了otter的源码，且在线生产1年左右了，我可以提交我的代码么？

**Comment by agapple** [comment]
欢迎提交PR给我
