### ISSUE TITLE
db不可用，任务也不会挂起？

### ISSUE THREAD

**Issue by luyee** [alibaba/otter#379]
有台db挂了，channel没挂起，日志有
`
pid:21 nid:1 exception:canal:aaaaa:com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: connect /xxx.xxx.xxx.xxx:3306 failure:java.net.NoRouteToHostException: No route to host
`

**Comment by agapple** [comment]
No route to host，整个任务会处于定位中
