### ISSUE TITLE
问下，otter支持整库同步吗

### ISSUE THREAD

**Issue by welyss** [alibaba/otter#382]
Table规则配的正则：.*
create和drop语句会报：
pid:1 nid:1 exception:setl:com.alibaba.otter.node.etl.transform.exception.TransformException: no support ddl for [hb.tee] to [hb2.tee] , sql :DROP TABLE `tee` /* generated by server */.

**Comment by swords1999** [comment]
支持的，但是要库名表名一致。

**Comment by luyee** [comment]
同表明同库名

**Comment by agapple** [comment]
最新版支持库名不同了

**Comment by welyss** [comment]
再问下，同库名测通了，但是不同库名不行。
我的版本是release版本（https://github.com/alibaba/otter/releases/tag/v4.2.14下载的latest版）：
manager.deployer-4.2.14.tar.gz
node.deployer-4.2.14.tar.gz
是配置上有不同还是需要自己打个最新的非release版本?
我的配置是：
源表：hb..*
目标表：hb_des..*
报错信息是：
pid:1 nid:1 exception:setl:com.alibaba.otter.node.etl.transform.exception.TransformException: no support ddl for [hb.ttt] to [hb_des.ttt] , sql :DROP TABLE `hb`.`ttt` /* generated by server */

**Comment by luyee** [comment]
4.2.14   的canal 版本不是不稳定？

**Comment by welyss** [comment]
@luyee 那哪个版本好？我看wiki里给的最新的是这个release。
刚看了下最新的源码，RowDataTransformer.java的88行那段确实注了，不过我反编了node.etl-4.2.14.jar看了下，那段代码还在，这个功能如果能加入，能打个新的release版吗，我自己打包的时候貌似有个google的jar需要翻墙= =多谢了
