### ISSUE TITLE
otter 支持过滤 delete 语句吗？

### ISSUE THREAD

**Issue by wps352** [alibaba/otter#390]

**Comment by huogenghao** [comment]
支持。参见[https://github.com/alibaba/otter/wiki/%E6%98%A0%E5%B0%84%E8%A7%84%E5%88%99%E9%85%8D%E7%BD%AE](url) 的高级映射

**Comment by huogenghao** [comment]
支持的。可以参见wiki里映射规则配置里的高级映射。

**Comment by chenweihua** [comment]
@huogenghao 高级映射要编程啊，不会java

**Comment by chenweihua** [comment]
package com.alibaba.otter.node.extend.processor;

import com.alibaba.otter.shared.etl.model.EventData;

public class FilterEventProcessor extends AbstractEventProcessor {
    public boolean process(EventData eventData) {
        if (eventData.getEventType().isDelete()) {
            return false;
        } else {
           return true;
       }
    }
}
