### ISSUE TITLE
在运行的两个MySQL，怎么才能让他们同步数据呢。otter不能同步开启之前的数据。

### ISSUE THREAD

**Issue by yuanxiaoqi** [alibaba/otter#394]
两个MySQL都有数据，然后需要从某一刻开始，数据变成一样的。

**Comment by luyee** [comment]
这个是都会碰到的痛点就是全量问题 。。。

1,最基本的方案(必须有binlog postion)就是:
mysqldump+mysql<sql  导入速度可能不太理想
xbackup+mysql<sql  

2, 都这么坑能绕开嘛？  

类离线+自动位点

mysql-->hdfs(sqoop)-->mysql

3, 其他类似DBZ, 全量增量都有，注意FTWRL 
[Debezium Connector for MySQL](http://debezium.io/docs/connectors/mysql/)

4,

**Comment by junneyang** [comment]
@luyee 
您好请问一下：mysql-->hdfs(sqoop)-->mysql全量+然后otter 根本不需要关心postion啊
otter 根本不需要关心postion啊，这句话怎么理解
谢谢
