### ISSUE TITLE
关于otter的单向同步

### ISSUE THREAD

**Issue by nothingsNeed** [alibaba/otter#396]
node1 服务器仅有内网ip 192.168.157.2
node2 服务器仅有外网ip 111.73.222.X
现在要把 node1的 user表 同步到 node2 服务器(node2 ping 不到 node1，但node1可以ping到 node2)
我需要把 manager 安装到 node1 上还是安装到 node2上
还是 安装到哪个node都不行 都无法用otter实现单向同步

**Comment by luyee** [comment]
see wiki
