### ISSUE TITLE
数据库实例的dump线程在关闭同步任务之后依然存在

### ISSUE THREAD

**Issue by HorandGao** [alibaba/otter#397]

**Comment by HorandGao** [comment]
![image](https://user-images.githubusercontent.com/12339527/32414261-9bacfdf8-c1e8-11e7-987d-e3bda2066029.png)
当前就一个channel

**Comment by luyee** [comment]
最难刚好看到碰到这个问题，观察了下4.2.13 版本正常

**Comment by arikshi** [comment]
otter版本：v4.2.14
重现步骤：
1. 保持mysql中无数据写入，binlog无更新
2. 停用channel
3. 启动channel
步骤2和3每重复一次，mysql dump线程数加1

问题定位：
是监控项目中的Position超时逻辑引起的。

默认为自动恢复，监控周期为600秒。代码逻辑如下：

com.alibaba.otter.manager.biz.monitor.impl.RestartAlarmRecovery.java
function processRecovery()
            channelService.stopChannel(channelId);
            channelService.startChannel(channelId);

也就是在数据库无写入的情况下，每隔600秒左右，Position超时逻辑便会重启一下channel，从而导致大量dump线程堆积。

**Comment by erictanghu** [comment]
最新版本的otter release使用的是1.0.23版本的canal
这版canal有个bug
https://github.com/alibaba/canal/commit/db4fc68a550a2a6c42ddc91e7302eca985e9a468#diff-d53e1d0de26a33cbb0798f2173b01d64
所以建议自己编译源代码 修复这个问题。。

**Comment by agapple** [comment]
尝试一下4.2.15版本吧
