### ISSUE TITLE
如何测试监控邮件

### ISSUE THREAD

**Issue by wz2cool** [alibaba/otter#398]
麻烦问一下，我已经在manager otter.properties 里面设置了 smtp 地址，并且在监控配置列表里面加了发送对象。
但是我怎么都试不成功发送邮件，比如我吧node 关闭了，错误日志打出错误日志了，但是我还是看不到邮件

**Comment by wz2cool** [comment]
麻烦给予一下帮助，我看别人也遇到同样问题
https://www.oschina.net/question/3587530_2254099

**Comment by wz2cool** [comment]
@agapple 麻烦大神能看一下么，搞了两天都没搞定

**Comment by wz2cool** [comment]
用了gmail 收到邮件

**Comment by lralin** [comment]
我配置了还是收不到邮件，能看下你是怎么配置的吗？google邮箱登录一般不是要安全验证吗？那直接把账号密码放服务器上能登录上吗？0.0
