### ISSUE TITLE
监控似乎非常不敏感

### ISSUE THREAD

**Issue by wz2cool** [alibaba/otter#399]
#398 我以前还以为不发邮件了，我把一个node 节点关闭了，过了很久才收到邮件，请问如何设置，感觉太久了。

收到的邮件如下：

> alarm_from_otter 
XXXXXXXXXXX
发给 XXXXXXXXXXX
????2017-11-07 11:12
发件人: 
XXXXXXXXXXX
收件人: 
XXXXXXXXXXX
时间: 
Tuesday, November 7, 2017 (Tue) 11:12
大小: 
3 KB
pid:5 position 602 seconds no update

**Comment by liuzhuqing516** [comment]
这个问题有解决吗？邮件有发，就是特别慢，报警间隔时间，阀值也有设置
