### ISSUE TITLE
网路问题出现不同步

### ISSUE THREAD

**Issue by keyzq** [alibaba/otter#400]
com.alibaba.dubbo.remoting.transport.AbstractClient -  [DUBBO] client reconnect to 192.168.1.100:1099 find error . url: dubbo://192.168.1.100:1099/endpoint?acceptEvent.timeout=50000&client=netty&codec=dubbo&connections=30&heartbeat=60000&iothreads=4&lazy=true&send.reconnect=true&serialization=java&threads=50, dubbo version: 2.5.3, current host: 192.168.1.242
com.alibaba.dubbo.remoting.RemotingException: client(url: dubbo://192.168.1.100:1099/endpoint?acceptEvent.timeout=50000&client=netty&codec=dubbo&connections=30&heartbeat=60000&iothreads=4&lazy=true&send.reconnect=true&serialization=java&threads=50) failed to connect to server /192.168.1.100:1099, error message is:connection timed out

一旦网路出现问题pipline的mainstem状态就会变成   ”定位中“ ，然后就不会同步了。

**Comment by arikshi** [comment]
同遇到这个问题，有三个解决方法供参考：
1. 开启position超时监控的自动恢复选项，利用此处的定时健康重启channel解决
2. 自己手动重启channel
3. 修改zookeeper中的/otter/channel/[chanel_id]/[问题pipelineid]/mainstem中的status，将TAKING改为OVERTAKE

**Comment by keyzq** [comment]
![242](https://user-images.githubusercontent.com/2142155/34144083-0168129a-e4cb-11e7-9793-5f0e00081c53.png)

设置自动恢复后还是会出现上述问题。。

**Comment by hphuangpu** [comment]
请问该问题解决了吗？什么原因呀？我是通过重启node恢复正常，原因不了解，不知道该咋办！
