### ISSUE TITLE
如何node 灾备

### ISSUE THREAD

**Issue by wz2cool** [alibaba/otter#401]
我看ppt 里面有node集群灾备，这个实在不是很理解，zookeeper 我们可以做集群，但是我们建立的时候，是建立一个channel 一个 pipeline， 选择一个 Select node， 选择衣蛾load node，  然后映射表。比如说 里面选择 select node 那个node挂掉了，请问如何自动切换到其他节点上面.

这里在ppt 里面的， a 我大概理解了，不知道哪个地方可以知道b,c 咋弄
a.  zookeeper集群容灾
	leader/follower :  hz(3台) + cm3(2台) + cm4(2台) 
observer : us(2台) 读节点，加速读请求

b.  manager杭州多机房部署
	node节点客户端容灾，链接失败后切到下一台.

c.  node跨IDC机房部署
	i.  依赖manager的HA监控机制 (node无法自己监控自己)

**Comment by agapple** [comment]
select node可以选择多个
