### ISSUE TITLE
点击刷新zookeeper 报错

### ISSUE THREAD

**Issue by wz2cool** [alibaba/otter#407]
#183 这里遇到了同样的问题，但是作者说解决了，但是没有说少什么包，请大家的告诉我少什么包啊

**Comment by wz2cool** [comment]
已经解决了， 我的问题是 需要在zookeeper 机器上面安装 nc 命令，供大家参考

**Comment by qingw1983** [comment]
Manager 的Server 上需要访问zookeeper 的信息，通过nc 命令来访问的。所以需要在Manager 的Server 上安装nc 命令。具体命令可以参考 https://blog.csdn.net/fenglongmiao/article/details/79272708. 楼上可能manager Server 和zookeeper Server 在同一台机器上。
