### ISSUE TITLE
请教阿里云RDS到自建数据库同步如何部署？

### ISSUE THREAD

**Issue by trockxi** [alibaba/otter#412]
请问阿里云上RDS数据库同步要如何来做，因为部署不了node，直接添加数据源和表映射后，同步不起作用，任务也被挂起，请问具体要怎么来做？

**Comment by agapple** [comment]
信息太少

**Comment by eancoder** [comment]
搞通了吗？同求，RDS的链接配置上一直提示配置信息不正确，干不起
