### ISSUE TITLE
双A同步pipeline“定位中”问题

### ISSUE THREAD

**Issue by erictanghu** [alibaba/otter#416]
双A同步 运行几个小时后 有几率出现pipeline显示“定位中” 约十几秒一般自动恢复成“工作中”但这段期间的数据不会同步 要恢复成 工作中 之后才会同步过去
没有稳定复现的方式
有没有同学遇到过？

**Comment by zzzxx** [comment]
我也是这个问题  最新版本
node.log   一直报 这个  WARN  c.a.o.shared.arbitrate.impl.setl.monitor.MainstemMonitor - mainstem is not run any in node
1.log 一直报这个  WARN  c.a.o.s.a.i.setl.zookeeper.termin.WarningTerminProcess - nid:2[2:canal:canal-1.78:com.ali
baba.otter.canal.parse.exception.CanalParseException: command : 'show master status' has an error! pls check. you need (at least one of) the SUPER,REPLICATION CLIENT privilege(s) for this operation]

~

**Comment by agapple** [comment]
LS的是权限不足的问题

**Comment by 1032231418** [comment]
我这边测试，物理机同步，pipeline一直定位中，写入数据就会变成 定位中，虚拟机之间同步就正常，感觉只适合虚拟机，物理机同步，就一直定位中，请作者解释一下，谢谢
