### ISSUE TITLE
no found table [mysql.user] , pls check

### ISSUE THREAD

**Issue by m582445672** [alibaba/otter#419]
你好，请教你一个问题。
就单台otter做同步..2台机器，一主一从.用otter同步.
同步表规则都是.*  全库,全表同步.
但是.同步是没有问题的..但是时不时就报no found table [mysql.user] , pls check的异常.
然后就挂起了。请问这是为什么。？

**Comment by agapple** [comment]
mysql.user表没有权限，同步表映射配置不要加所有的库和表
