### ISSUE TITLE
OTTER同步很缓慢

### ISSUE THREAD

**Issue by windtalkerbj** [alibaba/otter#422]
源、目标、OTTER均在同一机房，采用列模式，自定义模式同步，观察row_select日志：
* Batch Id: [859] ,total : [22,800] , normal : [20,445] , filter :[2,355] , Time : 2017-11-28 10:49:00:604
* Start : [mysql-bin.008981:231536929:1511836352000(2017-11-28 10:32:32)] 
* End : [mysql-bin.008982:30110852:1511836599000(2017-11-28 10:36:39)] 
--略--------
* Batch Id: [860] ,total : [28,169] , normal : [22,433] , filter :[5,736] , Time : 2017-11-28 11:06:18:603
* Start : [mysql-bin.008982:30111414:1511836599000(2017-11-28 10:36:39)] 
* End : [mysql-bin.008982:137748142:1511837228000(2017-11-28 10:47:08)] 
可见，BATCHID 860花了16分钟，才处理了22433条记录；
另外，在manager端channel管理  >  Pipeline  >  同步进度，查看SETL PENDING情况，发现T出现PENDING：stage:TRANSFORM , pending:[261]，跪求大神帮忙看下

**Comment by agapple** [comment]
如果是load里的日志，需要看看是否db执行比较慢

**Comment by windtalkerbj** [comment]
@agapple 
后来我将PIPELINE的并行度由5改成了8，目前生产上延时变小很多。同时，channel管理  >  Pipeline  >  同步进度，查看Mainsteam状态，原来Transformer的统计，TPM现在是101（原来是个位数)，average是19599，跟ALI的线上相比，慢多少呢？
另外用PT工具抽了下目标库的SLOW QUERY，目标库毫无压力。
我这边生产日DML量接近100W，单事务峰值为8W，请参考下。

**Comment by agapple** [comment]
你们单事务峰值有8w记录？

**Comment by windtalkerbj** [comment]
@agapple ，是的
* Batch Id: [60509] ,total : [7,533] , normal : [7,529] , filter :[4] , Time : 2017-12-04 01:07:21:700
* Start : [mysql-bin.009153:146486992:1512321029000(2017-12-04 01:10:29)]
* End : [mysql-bin.009153:150803473:1512321030000(2017-12-04 01:10:30)]
* Batch Id: [60510] ,total : [15,264] , normal : [15,258] , filter :[6] , Time : 2017-12-04 01:07:27:962
* Batch Id: [60511] ,total : [16,549] , normal : [16,542] , filter :[7] , Time : 2017-12-04 01:07:34:244
* Batch Id: [60512] ,total : [16,611] , normal : [16,605] , filter :[6] , Time : 2017-12-04 01:07:38:539
* Batch Id: [60513] ,total : [16,512] , normal : [16,506] , filter :[6] , Time : 2017-12-04 01:07:43:541
* Batch Id: [60514] ,total : [4,447] , normal : [4,444] , filter :[3] , Time : 2017-12-04 01:07:48:887
* Start : [mysql-bin.009153:210041629:1512321052000(2017-12-04 01:10:52)]
* End : [mysql-bin.009153:214843567:1512321059000(2017-12-04 01:10:59)]

**Comment by windtalkerbj** [comment]
@agapple ,问题已解决，是Tranfsform流程中，OTTER向MYSQL发出大量SHOW TABLE语句卡住导致。撸了下源码，通过在MANAGER上设置PIPE的 ‘启动数据表类型转化’和‘兼容字段新增同步’为‘关闭’后，故障消失。
