### ISSUE TITLE
关于启用数据表类型转化

### ISSUE THREAD

**Issue by welyss** [alibaba/otter#423]
启用数据表类型转化开启的时候，发现单个节点需要同时访问源和目标的库，这种情况下，跨机房多节点的场景是不是必须要关闭这个选项，另外这个选项的具体使用场景是什么样的，文档里没找到相关的介绍，不是很明白

**Comment by agapple** [comment]
表类型转换，比如源库和目标库的类型不同的时，需要开启转换

**Comment by welyss** [comment]
懂了多谢
