### ISSUE TITLE
使用InetSocketAddress来存储mysql的地址和端口信息不妥（跨机房同步）

### ISSUE THREAD

**Issue by whaon** [alibaba/otter#427]
如果我们都用IP那没问题
但是如果用hostname的话，跨机房同步的话，canal的mysql信息会在manager那端取出来并反序列化为InetSocketAddress对象，同时InetSocketAddress对象会解析出ip地址，但是这个ip地址是和manger在同一机房的内网的mysql的地址，然后该InetSocketAddress对象被传送到另一机房的node中，该node直接用该InetSocketAddress对象去连接mysql，就会出现错误了

所以用InetSocketAddress来存储终究不妥

现在粗略的修改方法为：在MysqlConnector的`public MysqlConnector(InetSocketAddress address, String username, String password)`方法中重新构造一个InetSocketAddress对象让其再进行一次ns解析，代码如下：
```
      String addr = address.getHostString();
      int port = address.getPort();
      
      this.address = new InetSocketAddress(addr, port);
```

**Comment by agapple** [comment]
嗯，这个设计上是有一些小问题

**Comment by agapple** [comment]
如果方便，可以提交一个PR给我
