### ISSUE TITLE
系统中进行时间更新 导致mainstem状态进入定位中  求原因

### ISSUE THREAD

**Issue by lzq894880417** [alibaba/otter#435]
系统日志：
cat /var/log/messages | grep "Time has been changed"
Dec 18 16:59:54 db05 systemd: Time has been changed
otter manager日志：
17:00:26 发生
 com.alibaba.otter.canal.parse.inbound.AbstractEventParser$4 cannot be cast to com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser$MysqlDetectingTimeTask

mainstem状态进入定位中 
重启问题解决
测试进行重新ntpdate  无法重现   求原因  防止后面再出现类似问题

**Comment by agapple** [comment]
新版本已经修复
