### ISSUE TITLE
某个位点不能同步

### ISSUE THREAD

**Issue by jwcjlu** [alibaba/otter#438]
otter跑得好好 的，突然同步到某个位点的时候就行报下面错误
![image](https://user-images.githubusercontent.com/6467979/34374628-10e63be0-eb1d-11e7-9052-19d08bae7aa8.png)
，这样一直都不能同步位点，然后修改成下一个位点，就可以正常同步了，然后改回出问题的位点的时候又出现上图的异常，请问各位大佬遇到这个问题吗？

**Comment by hittanic** [comment]
我也遇到了，纠结好几天了，查不出原因， 日志啥也看不出来！！！！！

**Comment by agapple** [comment]
这是被mysql端链接重置
