### ISSUE TITLE
单向回环的一致性算法

### ISSUE THREAD

**Issue by lralin** [alibaba/otter#449]
最终的一直性是否用了paoxs协议，如果没用，那最终一致性什么情况是根据主站点来确定的，什么情况是根据更新时间来确定的。例如HZ已经发起同步到US，正好在HZ到达US的时候US修改了同一条数据，那么这时如何保证数据一致性？

**Comment by agapple** [comment]
看一下wiki

**Comment by lralin** [comment]
恩恩。
