### ISSUE TITLE
请教otter如何调优，有没有测试指标，异地机房同步的最大tps是多少？

### ISSUE THREAD

**Issue by xiaoqiang2209** [alibaba/otter#455]
请教otter如何调优，有没有测试指标，异地机房同步的最大tps是多少？
我这边压测显示同步较慢，tps比较低

![11111111111111111111](https://user-images.githubusercontent.com/23546815/35321806-f41ddab0-0122-11e8-869f-9f75dbda2d46.png)

**Comment by blademainer** [comment]
+1

**Comment by ZhiXingHeYiApple** [comment]
+1

**Comment by agapple** [comment]
之前测试基本在5k~1w
