### ISSUE TITLE
manager中channel对象有个‘推送‘功能，是做什么的？查看wiki文档没有找到解释。。。’

### ISSUE THREAD

**Issue by ZhiXingHeYiApple** [alibaba/otter#458]
![image](https://user-images.githubusercontent.com/20380664/35436011-c5602aba-02c7-11e8-95f8-cf5faf8e7594.png)

**Comment by dikang123** [comment]
+1

**Comment by 1329555958** [comment]
+1

**Comment by Wu-Jianqiang** [comment]
+1

**Comment by agapple** [comment]
推送功能是在任务无法正常退出时，重新触发一次当前状态数据同步到node，对齐一下状态
