### ISSUE TITLE
canal的HA机制中media方式是如何切换的?

### ISSUE THREAD

**Issue by ZhiXingHeYiApple** [alibaba/otter#459]
otter中canal配置有个HA机制，分为heartbeat和media。对media方式不是很理解其是怎么切换的，望知道的能解释一下，谢谢！

**Comment by agapple** [comment]
media的切换，是在页面上管理主备信息，页面上点击切换后可以通知到客户端做切换

**Comment by beebol** [comment]
切换后会自动找点吗？

**Comment by agapple** [comment]
必须会
