### ISSUE TITLE
Node启用External Ip之后，查看node详情时manager仍然尝试连接node的内网IP导致失败 

### ISSUE THREAD

**Issue by Macrame** [alibaba/otter#461]
使用otter版本4.2.15在跨机房的情况下：
Manager在一个机房，这个机房也有一个Node，看起来正常。添加了另外一个机房的node并配置好了Node的External Ip，并且查看数据库中也已经是启用了外网IP
另外机房的Node启动之后，在Manager的列表中看到都是已启动，但点击查看Node详情时，Manager报错了。错误是Caused by: java.rmi.ConnectIOException: Exception creating connection to: 10.1.98.9; nested exception is: 
	java.net.NoRouteToHostException: No route to host (Host unreachable)
这是另一个机房中的Node的内网IP,感觉这个启用外网IP没启作用，或者是Otter本身的bug

**Comment by Macrame** [comment]
我查过一些以前close的issue，算是找到了解决方案，就是node这台服务器的hostname -i显示的IP地址，必需等于配置的外网IP.但这我认为这仍然是个bug，在NodeMBeanServiceImpl这个类中明明已经获致到了onde的externalIp，为什么不用配置好的外部IP,而要用从node上获取的hostname对应的IP?这个外部IP配置成为了鸡肋。具体做法中最简单就是在/etc/hosts中增加一行记录10.1.98.9   222.xx.xx.23就是把公网IP解析为内网IP.很诡异的做法，很奇葩的做法，很恶心的bug

**Comment by sfilyh** [comment]
@Macrame  感谢！ 
我也碰到了。

机房1 (mysql_1 +  manage_1 + node_1)
机房2（mysql_2 + node_2） 

在 manage_1 查看 node_2  详情时，请求的却是内网 IP。

按照上面方法修改 Host 记录，使 hostname -i 返回外网 IP，查看详情成功。

**Comment by agapple** [comment]
LS正解
