### ISSUE TITLE
自由门做全量同步的问题探讨

### ISSUE THREAD

**Issue by dikang123** [alibaba/otter#463]
我们知道触发自由门的方式是：
insert into retl.retl_buffer(ID,TABLE_ID, FULL_NAME,TYPE,PK_DATA,GMT_CREATE,GMT_MODIFIED) (select null,0,'$schema.table$','I',id,now(),now() from $schema.table$); 

那如果需要通过自由门做同步的表一直在做DML变更，会不会导致，最终对于这个表的同一条记录，DML的变更最终被自由门触发的同步给覆盖掉，而导致不一致。

**Comment by agapple** [comment]
理论上不会，因为这个操作也是会排队到binlog中
