### ISSUE TITLE
关于otter同步日期类型问题

### ISSUE THREAD

**Issue by yhxxming** [alibaba/otter#467]
我用otter把mysql的数据同步到oracle数据是同步过去了但是对于日期类型有些问题，mysql使用的是datatime类型，时间值到秒一级，oracle我用的date，但是同步过去只有年月日，没有时分秒，后来我使用timstamp（0）类型，时分秒有了，但是后面多了000000,请问怎样同步到oracle里面时间保持时分秒一级，而且后面没有零。canal解析的数据我已经看了和mysql的一致。

**Comment by agapple** [comment]
这个是oracle gui客户端显示问题

**Comment by yhxxming** [comment]
谢谢  @agapple   解决掉了  通过代码直接查看去了下日期的值  的确是显示的问题
