### ISSUE TITLE
找不到jterster依赖

### ISSUE THREAD

**Issue by huanm** [alibaba/otter#485]
http://jtester.googlecode.com/svn/m2/这个地址是不是不能访问了？翻了也找不到这个地址
cannot collect jtester,the url is reachable?

**Comment by f-zhao** [comment]
执行一下代码里面的lib下面的脚本，把这个jar安装到本地的仓库中即可。

**Comment by huanm** [comment]
manager biz module for otter这个模块也找不到，Failed to execute goal on project manager.biz: Could not resolve dependencies for project com.alibaba.otter:manager.biz:jar:4.2.16-SNAPSHOT: Failure to find com.alibaba.otter:canal.instance.manager:jar:1.
0.26-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots

**Comment by tutar** [comment]
@huanm git canal编译安装到本地仓库
git clone https://github.com/alibaba/canal.git ;cd canal;mvn clean install -Dmaven.test.skip=true
