### ISSUE TITLE
找不到fastsql-2.0.0_preview_135.pom文件

### ISSUE THREAD

**Issue by JarvisLee** [alibaba/otter#486]
lib目录下执行 install.sh 脚本时报错
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.4:install-file (default-cli) on project standalone-pom: File not found /Users/jarvis_mac/Sites/otter/lib/fastsql-2.0.0_preview_135.pom: /Users/jarvis_mac/Sites/otter/lib/fastsql-2.0.0_preview_135.pom (No such file or directory)

**Comment by wu933** [comment]
在根目录的pom文件中把fastsql的依赖版本号改为2.0.0_preview_186可以解决依赖问题
<dependency>
       <groupId>com.alibaba.fastsql</groupId>
       <artifactId>fastsql</artifactId>
      <version>2.0.0_preview_186</version>
</dependency>

**Comment by zhouxiangling** [comment]
打开lib/install.sh，修改 fastsql 所有配置项中的版本号为 644，然后去 https://repo1.maven.org/maven2/com/alibaba/fastsql/fastsql/2.0.0_preview_644/ 下载 
fastsql-2.0.0_preview_644.jar
fastsql-2.0.0_preview_644-sources.jar
fastsql-2.0.0_preview_644.pom
下载到 lib 目录下，然后重新执行 
sh install.sh 
即可成功安装。
需要修改版本号的原因是在 
https://mvnrepository.com/artifact/com.alibaba.fastsql/fastsql 
下也不再提供 135 版本了。
