### ISSUE TITLE
源库的mysql的binlog  dump线程老是关闭

### ISSUE THREAD

**Issue by jwcjlu** [alibaba/otter#488]
Otter版本：4.2.13
mysql版本：5.6
最近otter 的一个通道老是出现数据延迟同步，异常老是抛异常
![image](https://user-images.githubusercontent.com/6467979/37648973-6c41fe5e-2c6b-11e8-954f-503aeb7f7232.png)
然后在源库里执行show  processlist 发现没有对应的binlog dump线程

然后重启该通道 ，在执行show processlist 该命令 发现有binlog dump线程，但是过一会儿该线程就消失了
紧接着就抛上面异常，各位大神有没有遇到这个问题呀

**Comment by agapple** [comment]
被mysql断链

**Comment by jwcjlu** [comment]
但是每次重连上mysql就收到mysql那边发送一个RST标志的报，然后就抛上述异常，想问一下什么情况会导致mysql那边把我们这边的链接断掉
![image](https://user-images.githubusercontent.com/6467979/38003629-03fc71d4-326b-11e8-91bb-c5db24e02d2a.png)

**Comment by agapple** [comment]
试试使用4.2.16？怀疑是slaveId冲突，新版本对slaveId做了自动生成

**Comment by jwcjlu** [comment]
slaveId冲突的是指，我这边同时跑二个slaveId一样的canal也是正常的

**Comment by jwcjlu** [comment]
我们把slaveId改成自动生成也不行

**Comment by agapple** [comment]
slaveId相同之后，mysql server会随机踢掉一个

**Comment by agapple** [comment]
出现重复的uuid概率比较大

**Comment by agapple** [comment]
新的canal版本做了server_uuid的自动化生成

**Comment by hhycz** [comment]
您好 ，请问找到问题原因了吗，我做的主从同步，一样是binlog dump线程自动关闭
