### ISSUE TITLE
请问一下 otter一个channel中配置两个相同源表的pipe，目标表不同，这时候对一个pipe设置映射关系为什么会影响另一个pipe ?

### ISSUE THREAD

**Issue by core1942** [alibaba/otter#489]

**Comment by xvusrmqj** [comment]
一个channel中使用两个pipeline是A -> B , B -> A 这样的场景， 你的是A -> B , A -> C ， 这时应该建两个channel.

**Comment by core1942** [comment]
@xvusrmqj thanks 按你说了果然可行 不过这样的话需要配置两个canal源  是不是有些资源浪费呢
