### ISSUE TITLE
otter邮件告警一直没搞定

### ISSUE THREAD

**Issue by dc-song** [alibaba/otter#496]
用的是阿里云邮smtp.mxhichina.com，配置到mailx上测试可以发送。是不是不支持这个阿里企业邮箱呢？这个问题搁置好久了，希望赶紧把告警搞起来，哪位知道我这个是哪里出的问题吗？除了配置otter.properties和web管理页面，还要做什么？

**Comment by luyee** [comment]
[邮件测试](https://github.com/alibaba/otter/issues/255)

**Comment by hphuangpu** [comment]
我现在能收到提示，也用的阿里云企业邮箱。邮箱username要写全。web管理确定一下接受邮箱正不正确。
