### ISSUE TITLE
canal解析出的binlog文件名有乱码，导致otter重启后就再也无法定位日志位置

### ISSUE THREAD

**Issue by lbj2016** [alibaba/otter#497]
<img width="1212" alt="2018-03-27 3 25 55" src="https://user-images.githubusercontent.com/16698854/37955130-4e5e4914-31da-11e8-991e-79e49b645e60.png">

**Comment by lbj2016** [comment]
MysqlEventParser.java中的findStartPosition返回的文件名是mysql-bin.000008,  是正常的。
后续开始dump数据，上图解析出来的CanalEntry返回的的日志文件中就存在乱码。
由于日志文件存在乱码，保存在zookeeper中的日志文件也存在乱码，从而在otter node重启后无法定位日志，谢谢

**Comment by agapple** [comment]
什么版本？

**Comment by lbj2016** [comment]
otter 4.2.15   canal 1.0.25
这个会跟数据库的字符集类型有关系吗？目前我使用的数据库字符集是UTF-8

**Comment by ZhiXingHeYiApple** [comment]
@lbj2016 我也碰到了这个问题，我用的是otter 4.2.14   canal 1.0.23
主备切换时，由于binlog文件名乱码导致获取不到日志
![image](https://user-images.githubusercontent.com/20380664/38161312-535e13c2-34ff-11e8-8dcb-2fed2aae27e6.png)
不知你解决这个问题没？怎么解决的？

**Comment by ZhiXingHeYiApple** [comment]
通过进一步去调试，我发现我的问题原因是在主备切换时，回退一个时间窗根据时间戳来定位binlog的startPostion时，获取到的entryPosition对象里的journalName就已经乱码了，导致后续去dump时就会出问题。
猜测会不会是特定版本的canal问题，我又进一步拉取了canal1.0.23和canal1.0.25进一步单元测试发现canal1.0.25版本不会有这个问题，而canal1.0.23，调试结果如下：
![image](https://user-images.githubusercontent.com/20380664/38162060-1f5ba216-350d-11e8-85df-b61fe8099c11.png)
备注：我使用的mysql版本为 5.7.19

**Comment by agapple** [comment]
我记得是1.0.25之后修复过这个问题，建议升级了

**Comment by agapple** [comment]
最新的canal1.1.2修复了
