### ISSUE TITLE
windows下修改代码同步可以实现，打包放入linux环境下部署，同步为实现。

### ISSUE THREAD

**Issue by whb420502834** [alibaba/otter#505]
如标题，主要问题在
![qq 20180408180903](https://user-images.githubusercontent.com/32921280/38466202-1468650a-3b58-11e8-921b-4b4dc2e5eac0.png)

页面position信息没有。配置位点也没有效果，但windows环境下启动可以。求解

**Comment by agapple** [comment]
binlog没有正常解析或者没有实际binlog数据

**Comment by i323654** [comment]
数据都能正常同步，但是就是没有position信息，binlog应该确定是开启了吧
