### ISSUE TITLE
otter同步时，部分update的操作没有同步成功

### ISSUE THREAD

**Issue by victorqian** [alibaba/otter#507]
有一种场景，业务上先insert一条数据，再update这条数据。otter进行同步时，update的这个操作丢失了，日志中也没有报错信息。是node在消费时因为多线程原因导致先操作了update失败，然后insert了数据吗？

**Comment by whb420502834** [comment]
看你的意思是说，insert和update是同一批数据，otter处理时，insert和update语句合并成insert语句，但结果应该是update的数据吧，新人如不对，请见谅，参考下吧。

**Comment by victorqian** [comment]
你说的是otter的入库算法，但目前现实的情况是，update的binlog没有执行，最后只有insert的数据。

**Comment by daemonluo** [comment]
我也发现了这个问题。看了下源码，应该是数据入库算法有问题。同一个事务里，如果先插入一条数据，再更新这条数据，数据入库合并时，并不能合并成一条insert事件，这样事实际执行时，insert事件和update事件分别在不同的线程里执行，update事件就有可能不起作用。

**Comment by agapple** [comment]
insert和update，会合并为一条insert去执行

**Comment by victorqian** [comment]
@agapple  insert和update会合并的话，那能提供些思路帮助我们排查这种问题吗？从现象上看是update的操作丢了，并且没有任何错误日志，没法下手排查这种问题。

**Comment by victorqian** [comment]
@daemonluo 那你们是如何避免这种问题的？业务层自己把insert和update合成一个insert操作吗？

**Comment by daemonluo** [comment]
@agapple 在同一批EventData中，insert和update的合并有个bug，RowKey这个对象在判断相等性和计算hashcode时，是直接调用EventColumn的相关方法，这样会把EventColumn的isUpdate属性计算进去，造成insert和update合并不成一个insert。

**Comment by LeoLiang666** [comment]
我这里也有这个问题，一段时间后，有一个表总条数是一样的，但某些数据有某些列的值不一样。估计是update没执行到。

**Comment by luyee** [comment]
有这个问题的都用的哪个版本 ？我不知道是不是最近换了4.2.15的问题。。以前4.2.13好像没有～

**Comment by luyee** [comment]
@daemonluo  看起来hashcode确实是

```
public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((columnName == null) ? 0 : columnName.hashCode());
    result = prime * result + columnType;
    result = prime * result + ((columnValue == null) ? 0 : columnValue.hashCode());
    result = prime * result + index;
    result = prime * result + (isKey ? 1231 : 1237);
    result = prime * result + (isNull ? 1231 : 1237);
    result = prime * result + (isUpdate ? 1231 : 1237);
    return result;
}
```

**Comment by daemonluo** [comment]
@luyee 我用的也是4.2.15

**Comment by paopao5541** [comment]
otter-4.2.14同样遇到这个状况@agapple  ，这个有计划排查确认一下吗。

**Comment by cclouds** [comment]
otter-4.2.16也有这种情况 有没有哪个版本没有这个问题呢

**Comment by kitdine** [comment]
代码没有全部看完，发现一个问题，MessageParser中，在解析update时，会在eventdata中放入keys以及oldkeys（oldkeys isupdate 为true，并且只在eventtype为update，!oldKeys.equals(keys)才会设置oldkeys），但是在DbLoadMerger中打印日志发现 keys和oldkeys是一样的（isupdate 为 false），这不和逻辑

**Comment by yuyid** [comment]
@kitdine isUpdate  正确的值应该 当前值isUpdate=false old值 isUpdate=true 所有才会导致EventColumn的hashcode 
EventColumn
public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((columnName == null) ? 0 : columnName.hashCode());
        result = prime * result + columnType;
        result = prime * result + ((columnValue == null) ? 0 : columnValue.hashCode());
        result = prime * result + index;
        result = prime * result + (isKey ? 1231 : 1237);
        result = prime * result + (isNull ? 1231 : 1237);
        result = prime * result + (isUpdate ? 1231 : 1237);
        return result;
    }
DbLoadMerger.RowKey
public int hashCode() {
            final int prime = 31;
            int result = 1;
            result = prime * result + ((keys == null) ? 0 : keys.hashCode()); --直接调用EventColumn.hashcode
            result = prime * result + ((schemaName == null) ? 0 : schemaName.hashCode());
            result = prime * result + ((tableId == null) ? 0 : tableId.hashCode());
            result = prime * result + ((tableName == null) ? 0 : tableName.hashCode());
            return result;
        }
最终的结果导致insert +update 没有合并 成一条insert 语句去执行
再多线程的情况下导致就有可能导致update语句不执行   特别是数据库insert 后马上做update
具体可以看DbLoadAction.doTwoPhase

**Comment by yuyid** [comment]
各位大佬最后需改RowKey 吗  update应该可以解决 别的会不会有影响 还没看完源码

**Comment by luyee** [comment]
@yuyid  差不多就是RowKey跟EventColumn，可以参考下 [记一次Otter中update bug](https://luyee.github.io/java/2018/07/04/otter_update.html)

**Comment by yuyid** [comment]
@luyee  是的 这些都看过 我现在就是要评估这个改对 别的会不会有影响

**Comment by luyee** [comment]
@yuyid  同担心 所以暂时只改了rowkey相关的～

**Comment by jeffreyji666** [comment]
@luyee 单独维护fix这个bug版的otter么？不知道官方什么时候会修复这个bug, 生产环境影响太大了。

**Comment by yuyid** [comment]
@agapple @daemonluo @luyee  @victorqian 
问题的根源在于RowDataTransformer 
 // 转化new pk
                EventColumn tnewPk = translateColumn(data, newPk, tableHolder, dataMediaPair, translateColumnNames);
                if (tnewPk != null) {
                    tnewPks.add(tnewPk);
                    // 转化old pk，这里不能再用translateColumnNames了，因为转化new
                    // pk已经remove过一次view name了
                    toldPks.add(translateColumn(tnewPk, oldPk.getColumnValue(), dataMediaPair));
                }

修改后
//modify by yuyiding 20180725 主键的isupdate还是oldpk的isupdate
                    EventColumn transEventColumn = translateColumn(tnewPk, oldPk.getColumnValue(), dataMediaPair);
                    transEventColumn.setUpdate(oldPk.isUpdate());
                    toldPks.add(transEventColumn);

已经测试过insert +update merge成了一条insert （这个改动目前看不会影响别的）
请帮忙确认下这个改动的影响  🙏

**Comment by agapple** [comment]
我看一下这个问题

**Comment by agapple** [comment]
修改的思路：将pk的isUpdate设置为true，因为pk的update有内置的逻辑来处理.  当时调整应该是为DRDS做的一个变更导致

**Comment by yuyid** [comment]
感谢agapple解决了我们大问题  
| |
7
邮箱：pjobmail@163.com
|

Signature is customized by Netease Mail Master

在2018年08月01日 15:48，agapple 写道：

修改的思路：将pk的isUpdate设置为true，因为pk的update有内置的逻辑来处理. 当时调整应该是为DRDS做的一个变更导致

**Comment by agapple** [comment]
8月份会发布一个修复版本

**Comment by agapple** [comment]
v4.2.16-alpha 2，打包了一个版本

**Comment by tangdelong** [comment]
请问你们是怎么模拟出来的，我怎么模拟不出来insert+update不合并的情况。

**Comment by zzcclp** [comment]
大神们，我使用4.2.16版本，发现在一个事务中，先insert后再update 100条记录，会有1-2十条数据update没成功，也没有错误，这个要怎么解决呢？
