### ISSUE TITLE
关于otter使用canal的一点疑惑

### ISSUE THREAD

**Issue by jsnorman** [alibaba/otter#510]
每次新建一个同步任务，都会启动一个canal实例吗？

**Comment by agapple** [comment]
内存里启动一个canal实例

**Comment by luyee** [comment]
otter的好处可能就在这里帮忙管理好了canal 实例

**Comment by chrobin** [comment]
那为什么还要在每次配置canal的时候有端口号的选项，一个canal server上不是可以运行多个canal实例吗
