### ISSUE TITLE
node节点机器配置

### ISSUE THREAD

**Issue by deep011** [alibaba/otter#511]
对node节点，有什么硬件配置建议吗？比如CPU，内存，磁盘建议什么样的配置？

**Comment by agapple** [comment]
可以用标配的虚拟机，比如4c8g或者8c16g

**Comment by leeyisoft** [comment]
不知道 4个地区（深圳阿里云RDS 美国硅谷RDS 新加坡RDS 以后还可能做 迪拜）部署 alibaba/otter 硬件配置最低要求是多少？
