### ISSUE TITLE
4.2.15 出现部分字段数据没更新全为0

### ISSUE THREAD

**Issue by luyee** [alibaba/otter#512]
manager4.2.13,node 一台4.2.15,一台4.2.13.。。。 4.2.15版本上跑的channel出现的，目前切换到4.2.13测试是不是会复现

**Comment by SanmuWangZJU** [comment]
是不是开启了数据库表类型转换？

**Comment by luyee** [comment]
@SanmuWangZJU  这个是做啥的 这个默认都是看起的吧？

**Comment by SanmuWangZJU** [comment]
你先试试关了能正常同步吗？如果开启了这个选项，otter会在T阶段把进行同步的字段的类型转化为目标表相应的字段类型，在L阶段会根据这个类型向preparedstatement中setvalue，如果字段前后类型不一致，比如setInt(6.5)是无法set成功的，此时默认set给这个字段默认值。

**Comment by luyee** [comment]
应该是同类问题https://github.com/alibaba/otter/issues/507
