### ISSUE TITLE
fastsql 问题

### ISSUE THREAD

**Issue by liyongcun** [alibaba/otter#522]
1.fastsql 的pom文件呢
2.fastsql 更新了shell 的mvn脚本，bat脚本没有更新
3.fastsql lib下版本为135 ，而代码为159

**Comment by wu933** [comment]
在根目录的pom文件中把fastsql的依赖版本号改为2.0.0_preview_186可以解决依赖问题
<dependency>
       <groupId>com.alibaba.fastsql</groupId>
       <artifactId>fastsql</artifactId>
      <version>2.0.0_preview_186</version>
</dependency>
