### ISSUE TITLE
关于otter支持的字符集

### ISSUE THREAD

**Issue by chrobin** [alibaba/otter#525]
otter只支持manager页面上限定的那4个字符集么，像一般数据库默认的latin之类的不支持吗？似乎在添加数据源的时候添加一个utf8的schema链接，但是在配置数据表的时候选择另外一个schema，但字符集是latin的，也可以正常解析同步。

**Comment by agapple** [comment]
latin就选iso-8859-1

**Comment by jasongwt** [comment]
为啥close了 我也碰到了问题 mysql 5.7

**Comment by joylili** [comment]
mysql版本是5.6.41,也遇到了这个问题

**Comment by agapple** [comment]
这个web页面的字符集只是一个提示作用，不会做物理阻断

**Comment by jasongwt** [comment]
> 这个web页面的字符集只是一个提示作用，不会做物理阻断

哦，明白了，感谢告知~
