### ISSUE TITLE
pid:1 nid:1 exception:mainstem:pid:1 canal elapsed 50 seconds no data

### ISSUE THREAD

**Issue by KimHu01** [alibaba/otter#527]
我用的4.2.15，并没有解决这个问题，总是打印这一句，请教大神什么情况：pid:1 nid:1 exception:mainstem:pid:1 canal elapsed 50 seconds no data

**Comment by agapple** [comment]
主要怀疑还是老版本canal的问题，描述：在mysql长时间没有数据时，mysql server会主动断开连接，canal无法有效感知连接断开，导致一直无法收到binlog数据，重启一下任务可以恢复。 
目前新的canal 1.0.26已经有修复方案，可以使用新版本测试一下

**Comment by xiye518** [comment]
用4.2.15版本的会出现重启后读不到位点，binlog都在的，位点也设置的ok，切换回4.2.14就好了- -

**Comment by agapple** [comment]
canal1.0.25针对nio有一些不稳定的因素，建议直接使用otter4.2.16试试

**Comment by nece001** [comment]
otter4.2.16 我这也有这问题

**Comment by xiye518** [comment]
> otter4.2.16 我这也有这问题

建议你们用4.2.14版本的，我们线上现在就是用的这个，很稳定，偶尔网络波动导致的问题都能快速修复，已经稳定跑几个月了，
