### ISSUE TITLE
otter 4.2.13连接mysql5.7的问题

### ISSUE THREAD

**Issue by LeoLiang666** [alibaba/otter#528]
您好，我想用4.2.13，但连接mysql社区办5.7.21时，出现以下告警
抱歉,数据库未通过验证,请检查相关配置!
查看4.2.13是支持mysql5.7的
修复在监控管理页面删除监控配置时传递参数为空导致删除报错的情况 #85 [页面bug]
EventData.clone出现NPE #111 [bug]
无数据有文件同步时,FileBatch对象出现NPE [bug]
升级Apache Commons Collections to v3.2.2 #121 [bug]
windows启动支持带空格的目录 #140 [bug]
升级canal到1.0.22，支持MySQL5.7和RDS云数据库 [feature]

**Comment by LeoLiang666** [comment]
我配置有问题 自己检查一下先

**Comment by zhang520li** [comment]
> 您好，我想用4.2.13，但连接mysql社区办5.7.21时，出现以下告警 抱歉,数据库未通过验证,请检查相关配置! 查看4.2.13是支持mysql5.7的 修复在监控管理页面删除监控配置时传递参数为空导致删除报错的情况 #85 [页面bug] EventData.clone出现NPE #111 [bug] 无数据有文件同步时,FileBatch对象出现NPE [bug] 升级Apache Commons Collections to v3.2.2 #121 [bug] windows启动支持带空格的目录 #140 [bug] 升级canal到1.0.22，支持MySQL5.7和RDS云数据库 [feature]

请问一下您这个问题解决了吗???

**Comment by shihua-guo** [comment]
请问一下您这个问题解决了吗???
