### ISSUE TITLE
otter关于数据类型CURRENT_TIMESTAMP默认值的问题

### ISSUE THREAD

**Issue by LeoLiang666** [alibaba/otter#529]
您好，我使用的是otter4.2.13。同步时发现以下这个字段的数据不一致
`UPDATE_TIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',

**Comment by agapple** [comment]
建议不设置ON UPDATE CURRENT_TIMESTAMP，否则每次目标库执行sql成功后都会更新为当前时间戳
