### ISSUE TITLE
 canal elapsed 50 seconds no data

### ISSUE THREAD

**Issue by KimHu01** [alibaba/otter#531]
canal elapsed 50 seconds no data, 时不时的有这个错，什么原因呢？我用的是4.2.15的版本，也开启了心跳检测

**Comment by lcl101** [comment]
我这边也报这个异常，并且有数据同步的情况下

**Comment by KimHu01** [comment]
我这儿也是时不时的报这个错，所以这个感觉还是不稳定造成的

**Comment by agapple** [comment]
主要怀疑还是老版本canal的问题，描述：在mysql长时间没有数据时，mysql server会主动断开连接，canal无法有效感知连接断开，导致一直无法收到binlog数据，重启一下任务可以恢复。 
目前新的canal 1.0.26已经有修复方案，可以使用新版本测试一下

**Comment by JerryChin** [comment]
@agapple 跟心跳检查不是同一个连接？

**Comment by agapple** [comment]
建议直接使用otter4.2.16试试
