### ISSUE TITLE
otter警报邮件

### ISSUE THREAD

**Issue by KimHu01** [alibaba/otter#532]
系统参数中设置了接收警报的邮箱，也给pipeline添加完监控后，还需要做什么配置才能收发邮件？

**Comment by hphuangpu** [comment]
首先在ottermanager的配置文件中填写用于**发送**报警邮箱的smtp信息，然后在ottermanager的UI管理中添加用于**接收**报警的邮箱。

**Comment by hphuangpu** [comment]
关于manager发送给你的邮件标题和内容，从配置文件和web管理中是设定不了的，邮件标题一般是alarm_from_otter，内容一般是错误信息。如果想改您应该要去找源码。

**Comment by KimHu01** [comment]
我在代码中找到了，是写死在代码里面的，我重新编译了jar，改成了从otter.properties 文件中读取

在 2018-05-24 10:01:02，"Huangpu" <notifications@github.com> 写道：


关于manager发送给你的邮件标题和内容，从配置文件和web管理中是设定不了的，邮件标题一般是alarm_from_otter，内容一般是错误信息。如果想改您应该要去找源码。
