### ISSUE TITLE
otter数据中的DELAY_STAT, TABLE_HISTORY_STAT, THROUGHPUT_STAT是否可清空？

### ISSUE THREAD

**Issue by hphuangpu** [alibaba/otter#533]
在otter的数据库中，看到DELAY_STAT, TABLE_HISTORY_STAT, THROUGHPUT_STAT这三个表中的数据在不断累积。请问在数据完成同步后，以上三个数据表中的数据是否可以进行清空呢？他们的作用是什么？

**Comment by agapple** [comment]
可以清空

**Comment by Carl-Hee** [comment]
这几个表数据量达到千万级别，会影响到otter本身的性能吗？
