### ISSUE TITLE
otter 如何跨服务器同步images或其它文件

### ISSUE THREAD

**Issue by 291850336asd** [alibaba/otter#537]
本地安装了aria2c,并设置了，
public class TestFileResolver extends AbstractFileResolver {

    public FileInfo[] getFileInfo(Map<String, String> rowMap) {
        // 基本步骤：
        // 1. 获取binlog中的变更字段，比如组成文件有多个字段组成version+path
        // 2. 基于字段内容，构造一个文件路径，目前开源版本只支持本地文件的同步.(如果是网络文件，建议进行NFS mount到ndde机器).
        // 3. 返回FileInfo数组，(目前不支持目录同步，如果是目录需要展开为多个FileInfo的子文件)，如果不需要同步，则返回null.
        String path = rowMap.get("IMA_URL"); //注意为大写
        System.out.println(path);
        FileInfo fileInfo = null;
        if (StringUtils.isNotEmpty(path)) {
            fileInfo = new FileInfo(path);
            return new FileInfo[] { fileInfo };
        } else {
            return null;
        }
    }

}

如何同步网络中的图片到本地，
例如网络中的‘https://192.168.166.111:8988/images/2012.gif’，
想把它同步到192.168.112:8088/images文件夹中

**Comment by agapple** [comment]
你需要构造一下path，指定为目标node机器上需要保存的全路径
