### ISSUE TITLE
为什么同步进度没有进度展示

### ISSUE THREAD

**Issue by gwshawsh** [alibaba/otter#539]
mainstem状态是工作中 position状态也正常，为什么没有同步进度相关的进度显示。用的是4.2.16-SNAPSHOT
![1111](https://user-images.githubusercontent.com/15353976/40830236-7385fde2-65b8-11e8-93f6-8f3fcebcf9dc.png)

**Comment by agapple** [comment]
单node节点内存模式不会有进度显示
