### ISSUE TITLE
无法选择数据源，没反应JS代码抛出异常

### ISSUE THREAD

**Issue by wolfoot** [alibaba/otter#543]
运行版本及环境：  4.2.16-SNAPSHOT + ubuntu16.04 + chrome  
操作步骤：
Channel管理  >  Pipeline管理  >  映射关系管理  >  添加映射关系 ，
点击查找数据表，跳至数据表管理后点击 【选择】后没反应，
JS代码抛出异常：
`selectDataMedia.htm?local=source:112 Uncaught TypeError: window.opener.changeKeyword is not a function
    at returnSelected (selectDataMedia.htm?local=source:112)
    at HTMLInputElement.onclick (selectDataMedia.htm?local=source:162)`

异常代码位置：
http://IP:8080/selectDataMedia.htm?local=source

`<script language="javascript">
	changeNav("sync");
	function returnSelected(keywordId, keyword, local) {
		if(window.opener && !window.opener.closed){
			window.opener.changeKeyword(keywordId, keyword, local);
		}
		window.close();
	}
</script>`

**Comment by agapple** [comment]
如果方便，可以提交一个修复代码

**Comment by suhuaguo** [comment]
一般情况下，选择数据表没反应，我关闭窗口，重新选择就 OK 了。
