### ISSUE TITLE
otter4.2.15 同步point类型出错

### ISSUE THREAD

**Issue by chenyanter** [alibaba/otter#545]
otter4.2.15 同步point类型出错
navicat查出来的结果为 location: POINT(18.7507 26.5846)
mysql终端查询出来的结果为 location:        �Jvl�]@ux  㧕:@
otter报错为

pid:6 nid:1 exception:setl:com.alibaba.otter.node.etl.load.exception.LoadException: java.util.concurrent.ExecutionException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [update `ris_production`.`nodes` set `location` = ? , `updated_at` = ? , `id` = ? where ( `id` = ? )]; Data truncation: Cannot get geometry object from data you send to the GEOMETRY field; nested exception is com.mysql.jdbc.MysqlDataTruncation: Data truncation: Cannot get geometry object from data you send to the GEOMETRY field

---Pks
EventColumn[index=0,columnType=4,columnName=id,columnValue=16201,isNull=false,isKey=true,isUpdate=false]
---oldPks
EventColumn[index=0,columnType=4,columnName=id,columnValue=16201,isNull=false,isKey=true,isUpdate=false]
---Columns
EventColumn[index=23,columnType=1111,columnName=location,columnValue=àJvl°]@uxã§:@,isNull=false,isKey=false,isUpdate=true]
EventColumn[index=25,columnType=93,columnName=updated_at,columnValue=2018-06-07 12:28:14,isNull=false,isKey=false,isUpdate=true]
---Sql
update `ris_production`.`nodes` set `location` = ? , `updated_at` = ? , `id` = ? where ( `id` = ? )

**Comment by agapple** [comment]
point类型没做过而是，应该需要按照byte[]进行处理

**Comment by chenyanter** [comment]
有计划适配point类型么，顺便问一下，正式的新版本计划什么时候发布，迫不及待的想用新版本了

**Comment by agapple** [comment]
可以尝试一下4.2.16-alpha2版本，支持了point类型。ps. 需要关闭pipeline高级参数里的数据类型转换
