### ISSUE TITLE
异地机房节点配置都OK却一直显示节点未启用

### ISSUE THREAD

**Issue by wolfoot** [alibaba/otter#546]
配置了一个manager两个node，一个node是再异地机房，本地机房的node OK，异地机房的node一直显示未启用，查看manager和异地的node都正常启动没有异常错误日志。异地node配置启用外部IP，且异地node机器上 hostname -i 配置为外网IP，查看该节点启动日志显示已经连接到manager，查看该节点机器的3个端口已监听，在manager 上telnet 该节点机器的3个端口都OK。但却一直显示未启用，最诡异的是没有错误日志。

**Comment by wc1993524** [comment]
问下你是怎么解决的，我也遇到了相同的问题
