### ISSUE TITLE
求助，otter数据同步延迟问题

### ISSUE THREAD

**Issue by chenyanter** [alibaba/otter#549]
otter同步时候遇到，数据一直有更新，但是binlog及位点信息一直不变，延迟时间一直变大
请问这种情况如何处理
![1](https://user-images.githubusercontent.com/9622326/41454051-a0a3846e-70aa-11e8-8bbd-11c4d38caf55.png)
![2](https://user-images.githubusercontent.com/9622326/41454052-a0fc0f76-70aa-11e8-92b3-5182d58c0dc5.png)
![3](https://user-images.githubusercontent.com/9622326/41454055-a153e5a2-70aa-11e8-922f-3ca460d3fdf9.png)

**Comment by hongjun0619** [comment]
看监控日志，应该是同步报错了，看下Channel是不已经挂起了

**Comment by chenyanter** [comment]
从node里该任务的日志查到了原因，从web页面有时候并不能准确查到原因
