### ISSUE TITLE
mysql 枚举类型 enum 同步问题

### ISSUE THREAD

**Issue by Mustang888** [alibaba/otter#550]
mysql 枚举类型 enum 同步问题：
【问题描述】
enum字段类型 默认值为‘0’，‘1’，‘2’，‘3’，‘4’，‘5’的值，在经过otter同步到目标数据库的时候值有所+1
【图片说明】
源数据库变更值：
![default](https://user-images.githubusercontent.com/39473851/41456581-7d9c5078-70b3-11e8-95ed-b68b67408c75.png)
目标数据库变更值：
![default](https://user-images.githubusercontent.com/39473851/41456617-a1d365c6-70b3-11e8-87c3-49a8c3129d42.png)
表结构设计：
![default](https://user-images.githubusercontent.com/39473851/41456638-abdb778e-70b3-11e8-8f8b-a849f1db423a.png)

**Comment by agapple** [comment]
给我建表语句

**Comment by Mustang888** [comment]
哈哈，没事，解决了。
        在loader过程中增加了 char类型的处理
        谢谢~
