### ISSUE TITLE
提一个otter编辑保存系统参数报错的bug

### ISSUE THREAD

**Issue by 798566565** [alibaba/otter#551]
![image](https://user-images.githubusercontent.com/30824258/41696147-28f5bb04-7545-11e8-95b9-c840136ab8f7.png)

我用的4.2.14 版本   这里还未修复   我看最新git的上代码这里已经被修复了。
不知道现在发布的版本有没有修复这个问题

**Comment by agapple** [comment]
用一下最新的alpha版本
