### ISSUE TITLE
Otter同步数据很慢

### ISSUE THREAD

**Issue by Winwinter** [alibaba/otter#554]
一个写入量比较稳定的数据库需要同步，在正常情况下，otter能够完成每分钟15000行的数据同步。
但是，如果我停止大约2分钟再启动channel，会出现同步数据数量急剧下降的情况。

正常情况：
* Batch Id: [101191] ,total : [179] , normal : [7] , filter :[172] , Time : 2018-06-28 17:49:45:248
* Start : [SVR13075HP380-bin.017878:691161915:1530179385000(2018-06-28 17:49:45)]
* End : [SVR13075HP380-bin.017878:691250422:1530179385000(2018-06-28 17:49:45)]

异常情况：
* Batch Id: [4899] ,total : [2] , normal : [0] , filter :[2] , Time : 2018-06-28 17:53:11:453
* Start : [SVR13075HP380-bin.017878:722832918:1530179401000(2018-06-28 17:50:01)] 
* End : [SVR13075HP380-bin.017878:722833003:1530179401000(2018-06-28 17:50:01)] 

发现row_select的log中， 一个batch基本上就是2个EVENT， 猜想基本上就是 Transaction begin 和 end event

进入异常情况后，基本上不可能把同步的进度追上。 只能删除 logposition, 丢失一些数据。

请问一下，这种情况大家遇见过吗？ 怎么解决？

**Comment by luyee** [comment]
destination某个表写不进去.？有没有死锁

**Comment by Winwinter** [comment]
已经解决了这个问题，这个是出现在canal 1.0.25  （Otter 4.2.15） 上的。 主要的问题是 SocketChannel  类中 使用ByteBuf cache   = PooledByteBufAllocator.DEFAULT.directBuffer(1024 * 1024); 作为数据buff，当新建连接且数据量比较大的时候，这个cache size 会急剧扩大，再配合
public void writeCache(ByteBuf buf) {
         synchronized (lock) {
             cache.discardReadBytes();// 回收内存
             cache.writeBytes(buf);
         }
     }
方法中的 cache.discardReadBytes(); 使得系统在做无意义的memory copy 操作，使得一个工作核打满，并且writeCache速度极慢。

我们自己重写了 SocketChannel  内部的cache 实现，解决问题了。

看了Canal 的 1.0.26-preview-3的代码，这一块变动挺大，没有用过，不知道是否解决了问题。

**Comment by vTNT** [comment]
分享下？

**Comment by agapple** [comment]
1.0.26会解决这个问题

**Comment by chenyanter** [comment]
@Winwinter 这块可以分享下么？我们也遇到了同样的问题

**Comment by Winwinter** [comment]
你们使用的版本是otter 1.0.25吗？ 那个版本我们用下来质量很差，我们现在用了1.0.26preview3版本，这个问题就没了，我们的那个布丁也就不要了。 谢谢发自我的华为手机-------- 原始邮件 --------主题：Re: [alibaba/otter] Otter同步数据很慢 (#554)发件人：chenyanter 收件人：alibaba/otter 抄送：Winwinter <6570173@qq.com>,Mention @Winwinter 这块可以分享下么？我们也遇到了同样的问题

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/alibaba/otter","title":"alibaba/otter","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/alibaba/otter"}},"updates":{"snippets":[{"icon":"PERSON","message":"@chenyanter in #554: @Winwinter 这块可以分享下么？我们也遇到了同样的问题"}],"action":{"name":"View Issue","url":"https://github.com/alibaba/otter/issues/554#issuecomment-410529214"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/alibaba/otter/issues/554#issuecomment-410529214",
"url": "https://github.com/alibaba/otter/issues/554#issuecomment-410529214",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [alibaba/otter] Otter同步数据很慢 (#554)",
"sections": [
{
"text": "",
"activityTitle": "**chenyanter**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@chenyanter",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"alibaba/otter\",\n\"issueId\": 554,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"alibaba/otter\",\n\"issueId\": 554\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/alibaba/otter/issues/554#issuecomment-410529214"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 351037011\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by agapple** [comment]
canal 25不建议使用了, 直接上最新版
