### ISSUE TITLE
如何禁止node节点启动的2088端口的匿名访问

### ISSUE THREAD

**Issue by YcJu** [alibaba/otter#555]
目前是这样的，manager配置的node节点的2088端口，可以在任意服务器上，telnet node-ip 2088，进入到dubbo命令行，由于我们这边安全检查，他们禁止这种匿名访问。
咨询一下，如何在otter同步服务正常的情况下，禁止匿名访问

**Comment by agapple** [comment]
目前没办法

**Comment by linqh1** [comment]
iptables配置下白名单
