### ISSUE TITLE
数据对象解析MessageParser 为什么需要访问targetDB

### ISSUE THREAD

**Issue by iamyangjy** [alibaba/otter#557]
试用中发现nodeselect 阶段报出访问db失败，查看源码是messageParser阶段会访问到目标库上。能说下这样设计的原因吗。如果是纯mysql的话是否可以去掉这个步骤

`DbDialect targetDbDialect = dbDialectFactory.getDbDialect(pipeline.getId(),
                    (DbMediaSource) targetDataMedia.getSource());
                if (targetDbDialect.isDRDS())`

**Comment by agapple** [comment]
可以关闭的，主要是目标为DRDS时，需要关注拆分条件
