### ISSUE TITLE
otter-node节点异常宕机

### ISSUE THREAD

**Issue by yangliang1111** [alibaba/otter#560]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f1ca1052342, pid=16390, tid=139756371801856
#
# JRE version: Java(TM) SE Runtime Environment (8.0_65-b17) (build 1.8.0_65-b17)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.65-b01 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# v  ~StubRoutines::jlong_disjoint_arraycopy
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /opt/otter-4.2.15/node/bin/hs_err_pid16390.log
Compiled method (c2)  209293 6453       4       io.netty.util.internal.PlatformDependent::copyMemory (8 bytes)
 total in heap  [0x00007f1ca1e2b0d0,0x00007f1ca1e2b338] = 616
 relocation     [0x00007f1ca1e2b1f8,0x00007f1ca1e2b208] = 16
 main code      [0x00007f1ca1e2b220,0x00007f1ca1e2b2a0] = 128
 stub code      [0x00007f1ca1e2b2a0,0x00007f1ca1e2b2b8] = 24
 oops           [0x00007f1ca1e2b2b8,0x00007f1ca1e2b2c0] = 8
 metadata       [0x00007f1ca1e2b2c0,0x00007f1ca1e2b2d0] = 16
 scopes data    [0x00007f1ca1e2b2d0,0x00007f1ca1e2b300] = 48
 scopes pcs     [0x00007f1ca1e2b300,0x00007f1ca1e2b330] = 48
 dependencies   [0x00007f1ca1e2b330,0x00007f1ca1e2b338] = 8
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

**Comment by luyee** [comment]
换版本吧 4.2.15碰到过这个问题而且频繁的很

**Comment by Winwinter** [comment]
https://github.com/alibaba/otter/issues/554

你这个问题其实和我遇到的一样。 看我的comment吧。 canal 1.0.24 版貌似没有这个问题，1.0.25版有。

**Comment by agapple** [comment]
建议跳过canal1.0.25和otter 4.2.15版本
