### ISSUE TITLE
请问可以在自定义数据处理中定义映射规则吗?

### ISSUE THREAD

**Issue by wbsch52** [alibaba/otter#566]
![image](https://user-images.githubusercontent.com/31718669/42814644-70284912-89f7-11e8-95ca-94ca4ce1fb52.png)
举个例子, 我想把源表的ID,NAME 数据同步到目标表, 
但是目标表的ID和COMPANY_ID字段是通过其他方式计算出来的.
这种情况有办法解决吗? 目前我在wiki文档里看到EventProcessor扩展只是修改本次处理的数据,但是没有讲到如和与目标表的字段进行映射, 可能是我还不够了解.

**Comment by agapple** [comment]
只能通过EventProcessor了，字段映射只能是名字不同时做一个映射管理
