### ISSUE TITLE
binary做主键时，部分update语句不同步

### ISSUE THREAD

**Issue by fwdcb** [alibaba/otter#573]
1. 创建表，结构如下
+--------+------------+------+-----+---------+-------+
| Field  | Type       | Null | Key | Default | Extra |
+--------+------------+------+-----+---------+-------+
| sha256 | binary(32) | NO   | PRI | NULL    |       |
| count  | int(11)    | NO   |     | 0       |       |
+--------+------------+------+-----+---------+-------+
2. 在master1中插入一条语句
mysql> insert into test (sha256, count) values (0x02F58AC41C620FD28380EB9DE170031E85EA6A6238861A8339BD4C9200413700, 1),(0x7D98B0A1153D790DD6F7CFCAB29E8D0EB7C852311AF0A63ED495DE57F1C3989C, 1);
3. 查看master2数据
mysql> select hex(sha256), count from test;
+------------------------------------------------------------------+-------+
| hex(sha256)                                                      | count |
+------------------------------------------------------------------+-------+
| 02F58AC41C620FD28380EB9DE170031E85EA6A6238861A8339BD4C9200413700 |     1 |
| 7D98B0A1153D790DD6F7CFCAB29E8D0EB7C852311AF0A63ED495DE57F1C3989C |     1 |
+------------------------------------------------------------------+-------+
4. 在master1上执行update操作
mysql> update test set count=2;
5. 查看master2数据
mysql> select hex(sha256), count from test;
+------------------------------------------------------------------+-------+
| hex(sha256)                                                      | count |
+------------------------------------------------------------------+-------+
| 02F58AC41C620FD28380EB9DE170031E85EA6A6238861A8339BD4C9200413700 |     1 |
| 7D98B0A1153D790DD6F7CFCAB29E8D0EB7C852311AF0A63ED495DE57F1C3989C |     2 |
+------------------------------------------------------------------+-------+
6. 从5可以看出，02F58AC41C620FD28380EB9DE170031E85EA6A6238861A8339BD4C9200413700的count字段没有得到更新。
总结： 此表主键是binary类型，insert语句可以正常同步到master2, 但当执行update语句时，部分记录无法同步到master2.

**Comment by agapple** [comment]
看看是否为  #507 的类似问题

**Comment by zhengwang-qtl** [comment]
主键是binary类型，如果末尾是00，那么是无法同步的。这应该是一个BUG，我觉得很可能是binary转换成string的时候末尾的空字符被去掉了。这个问题在最新的版本4.2.17中依然存在。
@agapple  
可否帮忙确认下这是否为一个BUG。
