### ISSUE TITLE
otter4.2.12 同步 update 没有 set 值

### ISSUE THREAD

**Issue by bjddd192** [alibaba/otter#575]
有一个异常偶尔会蹦出来，就是执行更新没有 set 值，不知道大家有没有遇到过，以及是怎么解决的，谢谢。报错语句类似：
update table set where id=xxx;

就像这样，set 后面没了东西，我分析是不是日志只改了主键信息导致的，但是主键是不会变的啊。

遇到这个同步就挂起了，必须手工处理跳过异常才能继续下去，感觉就是定时炸弹，希望能在这里问到答案

**Comment by agapple** [comment]
什么版本？对应的表结构是啥？

**Comment by bjddd192** [comment]
otter4.2.12 版本，对于的表结构很普通，就是id主键，其他都是 int 或者 varchar 类型的

**Comment by agapple** [comment]
这个我印象在新版本有修复过类似的问题, 可以尝试等8月份的新版本测试一下
