### ISSUE TITLE
dubbo和rmi方式问题

### ISSUE THREAD

**Issue by erictanghu** [alibaba/otter#577]
有一事不解
我看了一下otter代码，似乎现在只有当manager调用node的状态信息这个功能会使用jmx rmi方式的远程调用，具体到代码就是manager的NodeOp这里
其他时候，node之间，manager向node推送配置这些场合都是dubbo的rpc
这样设计为什么呢 @agapple

**Comment by agapple** [comment]
node的jmx只是一个监控状态暴露
