### ISSUE TITLE
调度成本计算确认。

### ISSUE THREAD

**Issue by iamyangjy** [alibaba/otter#581]
看了wiki
中美网络RTT = 200ms , zookeeper一次写入=10ms
调度成本估算：
    a. zookeeper + zookeeper watch (完全分布式)
       10 * 4 + 200 * 2 + 200 = 640ms
    b. zookeeper + rpc (sticky分布式，尽可能选择同节点)
    10 + 100 + 200 = 310ms
这个值是怎么算出来的。有点不大懂。
比如b，processId写入10ms，跨中心rpc调用200ms，100ms这个是哪里的值？

**Comment by agapple** [comment]
100ms应该是一次正向的通知, 没等ack回报
