### ISSUE TITLE
double类型数据同步错误

### ISSUE THREAD

**Issue by owenxiaolei** [alibaba/otter#584]
使用的是otter4.2.15版本，mysql字段类型是double(16,12), 同步到从库mysql后，字段值都是0.0(double默认值)，不知道该版本是否存在该问题

**Comment by agapple** [comment]
提供一下测试的建表语句和测试的数据

**Comment by luyee** [comment]
[507]

**Comment by agapple** [comment]
4.2.16测试不存在这个问题
