### ISSUE TITLE
请问能否将canal分离进行单独部署？

### ISSUE THREAD

**Issue by core1942** [alibaba/otter#588]
项目中的otter是fork下来，二次开发的，内置canal版本低且有bug，能否将canal分离出来单独部署吗，不知可有相关文档，请指教！

**Comment by luyee** [comment]
canal  本来就有单独出来的项目https://github.com/alibaba/canal

**Comment by agapple** [comment]
LS正解

**Comment by core1942** [comment]
canal单独部署我知道，otter如何连接单独部署的canal呢？
