### ISSUE TITLE
channel 在数据同步的时候经常挂起

### ISSUE THREAD

**Issue by chuangyefan** [alibaba/otter#594]
channel 在数据同步的时候经常挂起，报出：java.lang.UnsupportedException:this is supported to be overridden  by subclasses,
想请教一下大神，这个问题怎么解决

**Comment by agapple** [comment]
自己改过代码么，protobuf版本不对齐？

**Comment by chuangyefan** [comment]
主要是修改manager和node 增加了一个目标写入数据库，那个怎么问题怎么解决呀

**Comment by agapple** [comment]
protobuf版本问题
