### ISSUE TITLE
一台机器上能否部署多个otther进行同步

### ISSUE THREAD

**Issue by leididi** [alibaba/otter#597]
问题点1：
我有2个服务，分别使用了2个mysql服务。使用docker拉起了3308 和3306的端口
由于，是跨国际的同步，我尝试过，如果3308或者3306的其中一个同步出问题。manager会将otter重新拉起。导致另一个同步的数据库受到影响。状态就直接变更为定位中；

非常想知道能否在同一台机器上拉起2个otter而不受到影响。

**Comment by agapple** [comment]
可以考虑配置两个独立的node
