### ISSUE TITLE
pipeline状态一直卡住“定位中”，日志也没记录

### ISSUE THREAD

**Issue by goodfly** [alibaba/otter#598]
部署了OTTER，对于一个canal的连接，我数据库密码都乱写的，也没有任何日志，一直卡住在“定位中”

**Comment by goodfly** [comment]
不知，是否有什么办法可以定位问题。因为要用表级的双A同步，Otter基本是唯一选择。

**Comment by agapple** [comment]
学会看node节点上的日志
