### ISSUE TITLE
ClosedByInterruptException

### ISSUE THREAD

**Issue by gaoxing1105** [alibaba/otter#601]
otter 版本4.2.15
同步过程中canal经常会报ClosedByInterruptException
SocketChannel.read(SocketChannel.java:49)
代码：
if (null == channel) {
    throw new java.nio.channels.ClosedByInterruptException();
}
为什么channel突然变为null了呢？
日志里也没什么迹象。

**Comment by agapple** [comment]
4.2.15不建议使用了, 换4.2.16最新的版本
