### ISSUE TITLE
数据不一致求解

### ISSUE THREAD

**Issue by gaoshengL** [alibaba/otter#602]
两地通过otter双向同步，两地出现数据不一致，binlog某条记录三个字段的变化如下（最后一个是modify时间）：
A
1/PROCESSING/2018-09-04 08:56:45 -> 1/STRATEGYCOMPLETED/2018-09-04 09:30:02 -> 3/NOFEEDBACK/2018-09-04 09:30:06
B
1/PROCESSING/2018-09-04 08:56:45 -> 1/NOFEEDBACK/2018-09-04 09:30:06 -> 3/NOFEEDBACK/2018-09-04 09:30:06 -> 3/STRATEGYCOMPLETED/2018-09-04 09:30:02

->表示update一次变更

**Comment by gaoshengL** [comment]
解决了

**Comment by linqh1** [comment]
咋解决的呀老哥
