### ISSUE TITLE
OtterSelectorFactory 没有重用 CanalServerWithEmbedded对象

### ISSUE THREAD

**Issue by JerryChin** [alibaba/otter#603]
https://github.com/alibaba/otter/blob/dce24714ee61246b60574c81ec7dd8d27e56c52d/node/etl/src/main/java/com/alibaba/otter/node/etl/select/selector/OtterSelectorFactory.java#L28-L36

`CanalServerWithEmbedded`  支持多个数据队列，应该使用`CanalServerWithEmbedded.instance()`单例方法减少内存占用。

**Comment by agapple** [comment]
otter的pipeline链路会有重启的情况, 独立的canalserver instance, 互相干扰的成分少
