### ISSUE TITLE
v4.2.16版本中异构库表明同步有问题

### ISSUE THREAD

**Issue by zzhen1229** [alibaba/otter#605]
在4.2.15中增加“支持一下mysql异构库表名的同步”功能，在新版本中该功能对于表名不同的情况下无法进行ddl的更新

**Comment by agapple** [comment]
请提供对应的报错截图和测试表结构

**Comment by zzhen1229** [comment]
![image](https://user-images.githubusercontent.com/43201014/45679303-f1a74980-bb6a-11e8-81c4-d901db65efc7.png)
