### ISSUE TITLE
otter同步set类型出错

### ISSUE THREAD

**Issue by l-dandelion** [alibaba/otter#617]
pid:3 nid:1 exception:setl:com.alibaba.otter.node.etl.load.exception.LoadException: java.util.concurrent.ExecutionException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [update `jz`.`jz_videos` set `category` = ? where ( `video_id` = ? )]; Data truncated for column 'category' at row 1; nested exception is java.sql.SQLException: Data truncated for column 'category' at row 1

---Pks
    EventColumn[index=0,columnType=-5,columnName=video_id,columnValue=3280,isNull=false,isKey=true,isUpdate=true]
---oldPks

---Columns
    EventColumn[index=47,columnType=1,columnName=category,columnValue=-124,isNull=false,isKey=false,isUpdate=true]
---Sql
    update `jz`.`jz_videos` set `category` = ? where ( `video_id` = ? )

**Comment by l-dandelion** [comment]
![image](https://user-images.githubusercontent.com/25959115/46567775-d1013100-c96b-11e8-8afb-6e3cb4120e5c.png)
为什么这里要用getInt8，而不用getUint8?如果使用getUint8是不是就不会出现set字段的value<0，jdbc就不会报异常了？

**Comment by agapple** [comment]
getInt8不会出现负数的情况，因为int是32位的。 估计是同步时sql_mode没设置正确吧，对应的otter版本有升级到最新么？ 我印象中修复过一次sql_mode问题

**Comment by agapple** [comment]
测试的表结构和sql给我
