### ISSUE TITLE
兼容字段新增同步开启，源库新增了一个字段，目标库未添加，未做兼容处理

### ISSUE THREAD

**Issue by ssxlulu** [alibaba/otter#621]
1.开启pipeline兼容字段新增同步
![_20181012104003](https://user-images.githubusercontent.com/14773179/46844906-853b0580-ce0b-11e8-9a22-d2500862ac82.png)

2.源库新增字段无默认值
```ALTER TABLE test.`student_info` add column `telephone5` varchar(100) not null;```

3.源库插入数据
```insert into student_info(id,name,address,telephone5) values (65,'test','test','test')```

4.channal挂起，日志报错
![_20181012104734](https://user-images.githubusercontent.com/14773179/46845094-7f91ef80-ce0c-11e8-9015-89cde07a4a0c.png)

![_20181012104853](https://user-images.githubusercontent.com/14773179/46845148-c08a0400-ce0c-11e8-8147-b520c3ce93db.png)

**Comment by ssxlulu** [comment]
经测试，源库新增字段，目标库未添加，未做兼容处理。

**Comment by agapple** [comment]
这个兼容是建立在你源库没有对新字段做数据写入，如果你新字段有数据写入一定是会同步到目标的

**Comment by ssxlulu** [comment]
好的，了解了，多谢。

**Comment by ssxlulu** [comment]
好的，了解了，多谢。
