### ISSUE TITLE
目标表新增timestamp字段，源表不修改表结构如何同步

### ISSUE THREAD

**Issue by GYY2046** [alibaba/otter#629]
我的源表是mysql目标表是oracle，只同步几张表，会出现偶尔延迟很高的情况，我想再目标表中新增一个timestamp字段默认入库当前时间，这样如何配置呢？求解答

**Comment by berace** [comment]
> 我的源表是mysql目标表是oracle，只同步几张表，会出现偶尔延迟很高的情况，我想再目标表中新增一个timestamp字段默认入库当前时间，这样如何配置呢？求解答

请问你问题解决了吗

**Comment by hitits** [comment]
解决方案呢？
