### ISSUE TITLE
Channel启动提示启动，过1,2秒后刷新就提示挂起，日志见内容

### ISSUE THREAD

**Issue by javahun** [alibaba/otter#634]
pid:8 nid:1 exception:setl:com.alibaba.otter.node.etl.select.exceptions.SelectException: com.alibaba.otter.node.etl.select.exceptions.SelectException: this rowdata has no pks , entry: header {
version: 1
logfileName: "mysql-bin.001513"
logfileOffset: 265804754
serverId: 1788729222
serverenCode: "UTF-8"
executeTime: 1541741089000
sourceType: MYSQL
schemaName: "jiujiang"
tableName: "tb_member_info"
eventLength: 694
eventType: UPDATE
props {
key: "rowsCount"
value: "1"
}
}
entryType: ROWDATA
storeValue: "\bG\020\002P\000b\306\036\n6\b\000\020\373\377\377\377\377\377\377\377\377\001\032\016MEMBER_INFO_ID \000(\0000\000B\00578632R\nbigint(20)\n$\b\001\020\f\032\vMEMBER_CARD \000(\0000\001R\vvarchar(64)\nB\b\002\020\f\032\nBUYER_NICK \000(\0000\000B\034o_t1ruGiohbqy_8RXCPIVCTLRRQoR\fvarchar(128)\n/\b\003\020\f\032\vSELLER_NICK \000(\0000\000B\bjiujiangR\fvarchar(128)\n4\b\004\020\373\377\377\377\377\377\377\377\377\001\032\fRED_ENVELOPE \000(\0000\000B\00519614R\nbigint(20)\n/\b\005\020\373\377\377\377\377\377\377\377\377\001\032\vWX_ENVELOPE \000(\0000\000B\0010R\nbigint(20)\n(\b\006\020\373\377\377\377\377\377\377\377\377\001\032\004BILL \000(\0000\000B\0010R\nbigint(20)\n.\b\a\020\373\377\377\377\377\377\377\377\377\001\032\tPICKUP_TB \000(\0000\000B\0010R\vbigint(255)\n.\b\b\020\373\377\377\377\377\377\377\377\377\001\032\tPICKUP_WX \000(\0000\000B\0010R\vbigint(255)\n/\b\t\020\373\377\377\377\377\377\377\377\377\001\032\vPICKUP_BILL \000(\0000\000B\0010R\nbigint(20)\n/\b\n\020\373\377\377\377\377\377\377\377\377\001\032\vPICKUP_FLOW \000(\0000\000B\0010R\nbigint(20)\n.\b\v\020\373\377\377\377\377\377\377\377\377\001\032\nSET_POINTS \000(\0000\000B\0010R\nbigint(20)\n)\b\f\020\373\377\377\377\377\377\377\377\377\001\032\005SCORE \000(\0000\000B\0010R\nbigint(20)\n-\b\r\020\373\377\377\377\377\377\377\377\377\001\032\aLOTTERY \000(\0000\000B\003243R\nbigint(20)\n/\b\016\020\373\377\377\377\377\377\377\377\377\

**Comment by hanzixiaoshu** [comment]
Has this problem been solved?
