### ISSUE TITLE
请问  2.16版本的this rowdata has no pks , entry: header这个问题，如何解决，日志见内容

### ISSUE THREAD

**Issue by javahun** [alibaba/otter#636]
pid:12 nid:1 exception:setl:com.alibaba.otter.node.etl.select.exceptions.SelectException: com.alibaba.otter.node.etl.select.exceptions.SelectException: this rowdata has no pks , entry: header {
version: 1
logfileName: "mysql-bin.001513"
logfileOffset: 99177637
serverId: 1788729222
serverenCode: "UTF-8"
executeTime: 1541733011000
sourceType: MYSQL
schemaName: "jiujiang"
tableName: "tb_member_info"
eventLength: 728
eventType: UPDATE
props {
key: "rowsCount"
value: "1"
}
}
entryType: ROWDATA
storeValue: "\bG\020\002P\000b\351\036\n6\b\000\020\373\377\377\377\377\377\377\377\377\001\032\016MEMBER_INFO_ID \000(\0000\000B\00546151R\nbigint(20)\n$\b\001\020\f\032\vMEMBER_CARD \000(\0000\001R\vvarchar(64)\nB\b\002\020\f\032\nBUYER_NICK \000(\0000\000B\034o_t1ru

**Comment by agapple** [comment]
不支持无主键的表

**Comment by javahun** [comment]
不是吧。我自己测试了一个没有主键的表，也可以啊。

**Comment by f-zhao** [comment]
数据库必须要有主键，这个应该需要规范下，不然很多问题

**Comment by agapple** [comment]
LS正解

**Comment by hanzixiaoshu** [comment]
我也遇到了这个问题，看了各位老兄的解答，终于知道原因所在了
