### ISSUE TITLE
请教一个otter在同步时出现的问题

### ISSUE THREAD

**Issue by SwaggyQ** [alibaba/otter#644]
`2018-11-14 15:09:15.353 [pipelineId = 7,taskName = LoadTask] WARN  c.a.o.s.a.impl.setl.memory.LoadMemoryArbitrateEvent - pipelineId[7] load ignore processId[26] by status[PAUSE]`
不知道为什么，不报错，但是经常开起来就挂起，然后停止工作，现在处理办法就是一直手动重启，有谁能指点一下吗？

**Comment by kaikai2000** [comment]
#638  已经在这个issue里面解决，等待认可后merge代码。最终修改在

- [ ] f512a3f   @SwaggyQ

**Comment by agapple** [comment]
已合并
