### ISSUE TITLE
在双A的场景下，如出现两个机房数据不一致的情况，可以怎么来补救？

### ISSUE THREAD

**Issue by junjie-tang99** [alibaba/otter#653]
我想把otter应用于生产环境，但是有2个问题，不知道怎么来解决，有没有好心人来解答下：
1、双A的场景下，如真的出现两个机房数据不一致的情况，那一般情况下可以怎么来补救？
2、有什么好的办法，来监控两个机房的数据是否出现了不一致的情况？（除了定时用脚本，查下数据的记录数，并做下对比）

**Comment by agapple** [comment]
多看下wiki里的数据一致性的描述，otter有自己的方案
