### ISSUE TITLE
关于GTID的一些问题

### ISSUE THREAD

**Issue by SwaggyQ** [alibaba/otter#654]
在otter开启gtid模式后，如果监听的数据库有四个分库地址，A，B，C，D，四个数据库服务器上都有各自的gtid Set,那在对应的zk上写gtid起始位点的时候，是需要写四个如下的位点，还是将四个gtid拼成一串字符串，统一写到一个如下的位点信息里呢？
{"journalName":"","position":0,"timestamp":0,"gtid":""};

**Comment by agapple** [comment]
4个地址的暂时不支持gtid，只支持timestamp
