### ISSUE TITLE
同步经常出现find table  error

### ISSUE THREAD

**Issue by hlcompany** [alibaba/otter#66]
centos 6.4，otter 4.2.10测试单向同步，从源端导入sql文件时候，经常出现find table error。本来有6个表但同步到  目的端只有3个表。
![image](https://cloud.githubusercontent.com/assets/7994482/5312786/9ca3a9f0-7c9a-11e4-9237-b9ee0ef8c815.png)

**Comment by aiaix** [comment]
这个问题确实有，我监控里面配置了自动恢复也是不行
