### ISSUE TITLE
CanalEntry.Column对null值字段getValue()方法返回的是空字符串

### ISSUE THREAD

**Issue by bai020** [alibaba/otter#660]
canal使用v1.1.2镜像，客户端使用的v1.1.0的包，
发现 CanalEntry.Column对null值字段 getValue()方法返回的是空字符串
之后序列化发送出去的是空字符串''，不是null值，或者直接过滤掉。导致落地的时候把空字符串写入库了。

**Comment by bai020** [comment]
请问CanalEntry.Column哪个方法能确认数据库字段值为null？hasIsNull()还是getIsNull()

**Comment by junjie-tang99** [comment]
如果想把某个column值为空字符串的数据过滤掉的话，可以在自己实现一个eventProcessor，然后再在这个processor中，把相关的数据剔除掉。

        for (EventColumn column : eventData.getColumns()) {
            if (column.getColumnValue().equals("")) {
            	return false;
            }
        }
如果写Processor可以参考WIKI:
https://github.com/alibaba/otter/wiki/Otter%E6%89%A9%E5%B1%95%E6%80%A7

**Comment by bai020** [comment]
我只需要过滤null值的，空字符串可能是真是的数据字段。hasIsNull()或getIsNull()方法能确认column值是null吗

**Comment by lorangej** [comment]
下面的方法可以判断
public boolean getIsNull() { return this.isNull_;}
