### ISSUE TITLE
File not found lib/fastsql-2.0.0_preview_135.pom

### ISSUE THREAD

**Issue by 362228416** [alibaba/otter#665]
lib/fastsql-2.0.0_preview_135.pom
这个文件应该没提交，我刚下载的代码，打开lib目录没有看到这个文件

**Comment by dhanzhang** [comment]
也遇到了这个的问题

**Comment by 362228416** [comment]
@dhanzhang 
我已经放弃，因为我已经能内嵌canal了

**Comment by agapple** [comment]
fastsql的代码已经更新到maven仓库
