### ISSUE TITLE
docker修改端口映射

### ISSUE THREAD

**Issue by vinnie888** [alibaba/otter#672]
请教一下
有修改docker端口映射成功的吗？
想把run.sh中 8080 8081 2181 2088 2089 2090 这几个端口映射成别的
我试了一下有问题
1.8080映射修改后，网页上的所有链接还是8080端口。
2.8081映射修改后，启动docker一会儿就退出了，不知道为什么，没找到错误日志的输出位置。

所以想请教一下这些端口能改吗，怎么改？

**Comment by agapple** [comment]
需要同步修改一下，docker里的app.sh脚本，把涉及的8080和8081的配置都修改正确

**Comment by vinnie888** [comment]
@agapple 
感谢您的回答
8080和8081应该是可以了
不过其他的端口在app.sh中改了也还是不行
我整体搜了一下 ddl.sql中也有写死的端口号
其他的代码中写死的端口也有好多地方
没时间研究了 先按照默认的使用了
希望以后的版本可以把这些端口变成可配置的
再次感谢
