### ISSUE TITLE
canal配置中数据源和 数据源配置中数据必须是同一个吗

### ISSUE THREAD

**Issue by eason0420** [alibaba/otter#673]
请教个问题，我在使用otter manager时，发现数据源配置(源库) 和 cannal配置 中都需要填写数据库连接和用户名密码，有些不明白，这2个地方的配置有什么区别吗？还是必须一样？ canal配置中这个数据库连接是用来干什么的

**Comment by agapple** [comment]
一个是数据库DML操作, 一个是binlog dump用的

**Comment by eason0420** [comment]
源数据库的话就是用来和目标库做一些库、字段映射及特殊处理用的，cannal中数据库是dump binlog，真正用来数据同步用的，不知我这样理解对不

**Comment by agapple** [comment]
理解正确
