### ISSUE TITLE
mysql源数据库版本5.17，没有binlog_checksum同步出错

### ISSUE THREAD

**Issue by vinnie888** [alibaba/otter#674]
启动同步报异常
![image](https://user-images.githubusercontent.com/16188007/49918698-12b7d600-fedf-11e8-8eec-6175e3049779.png)
现在的docker使用的canal版本时1.1.2吧
canal的这个问题不是已经解决了吗？
请问该怎么处理

**Comment by agapple** [comment]
嗯，这是一个canal新版本的问题

**Comment by vinnie888** [comment]
@agapple 
了解了，谢谢
再问一下，修改后的版本什么时候发布呢
如果有计划发布，我看情况是否等一等

**Comment by vinnie888** [comment]
用当前的canal主干，自己打包这个问题解决了

**Comment by Pointvar** [comment]
我也遇到一样的问题了。

**Comment by Pointvar** [comment]
> 用当前的canal主干，自己打包这个问题解决了

请问怎么打包呢？
