### ISSUE TITLE
多张源表映射一张目标表怎么配置映射关系

### ISSUE THREAD

**Issue by fhqi** [alibaba/otter#679]
如跨库查询语句如下：
from 
ADB.T1 at1 join ADB.T2 at2 on at1.id = at2.at1_id
left join ADB.T3 at2 on at1.code=at3.code
left join BDB.T1 bt1 on at1.gid = bt1.gid

现做异构，将ADB.T1, ADB.T2, BDB.T1两个库的三张表合并到 另一张表BDB.T2中， 表数据之间关系如上
 Pipeline管理 里面如何做规则映射，还是otter有什么方案可以做如上需求支持？

**Comment by fhqi** [comment]
> 1、建立源表ADB.T1, ADB.T2, BDB.T1，目标表BDB.T2
> 2、建立2个canal，分别对应ADB，BDB
> 3、建立2个channel里面，ADB.T1, ADB.T2在channel-A，BDB.T2在channel-B.

那这样，映射关系如何配置？ 现好像同实例同库简单的两张关联表映射到第三张表中，这个pipeline里规则不知道怎么映射

**Comment by fhqi** [comment]
> 在同一个pipeline下面配置表T1--》目标表， T3-->目标表

假如T1, T3之间关系：数据一对一或是一对多通过主键来关联（如订单和商品这样）
场景如下：
比如购买了一件商品，T1生成了一条订单记录T2生成一条商品记录，目标表中这时要生成一条记录商品记录包含了T1表中的订单信息

【在同一个pipeline下面配置表T1--》目标表， T3-->目标表】 这样映射会生成多条记录。

**Comment by kaikai2000** [comment]
- 目标表字段包括（主键1，a,b,c,d,e,f)

- T1字段包括(主键1，a,b,c)----》通过主键1同步到目标（ insert语句）

- T3字段包括（主键1，d,e,f)----》通过主键1同步到目标（发现记录已经存在，update语句）

- 要求T1和T3及目标表有相同的主键，otter里面针对相同的主键，如果发现目标库里面已经存在该记录，改写成update，不会产生重复数据。

**Comment by fhqi** [comment]
> * 目标表字段包括（主键1，a,b,c,d,e,f)
> * T1字段包括(主键1，a,b,c)----》通过主键1同步到目标（ insert语句）
> * T3字段包括（主键1，d,e,f)----》通过主键1同步到目标（发现记录已经存在，update语句）
> * 要求T1和T3及目标表有相同的主键，otter里面针对相同的主键，如果发现目标库里面已经存在该记录，改写成update，不会产生重复数据。

像订单与商品场景中，T1，T3为一对一关系(一个订单对应一个商品)，虽然商品表中的主键与订单表的主建不一样，但合并到**目标表**时可以通过EventProcessor构建T3表中关联的订单id为新的主建替换原来的主建来实现。

但如果T1、T3为一对多(一个订单对应多个商品时)，这时otter是否还能处理这种场景合并到**目标表**中吗？

**Comment by kaikai2000** [comment]
原理就是这些，功能也是这些。 你说的复杂场景，需要定制化扩展otter开发，不在otter的通用职责范畴。

**Comment by fhqi** [comment]
好的，大概了解了otter能够使用的支持到的场景，多谢了
