### ISSUE TITLE
otter支持MariaDB吗？

### ISSUE THREAD

**Issue by alex-17** [alibaba/otter#68]
请问，otter支持MariaDB吗？

**Comment by zhouyq** [comment]
看看otter原理，或者做做测试

**Comment by alex-17** [comment]
别误会，不是伸手党。只是刚开始接触otter，看官网给出了一个推荐“网友分享”，看到里面有说不支持MariaDB。也在做测试。

**Comment by agapple** [comment]
现在版本测试支持的，https://github.com/alibaba/canal/wiki/BinlogChange%28MariaDB5%2610%29

**Comment by alex-17** [comment]
谢谢，已经过测试
