### ISSUE TITLE
如何获取otter保存或更改数据的事件

### ISSUE THREAD

**Issue by fhqi** [alibaba/otter#680]
请问下保存和更新数据后 otter有事件通知的扩展吗，如果修改原码着重从那里入手了？

**Comment by fhqi** [comment]
> 数据保存在canal的EventStore内存中，代码里面没有看到有消息通知。 源码可以从MemoryEventStore.java开始

【数据同步成本到目标表】这动作是在canal中吗？  想咨询下如果想数据同步到目标表成功后，otter源码这那里可以知晓，想加入事件通知到别的应用。

**Comment by kaikai2000** [comment]
在SelectTask.java 的ack方法里面添加。
```
 private void ack(Long batchId) {
        canStartSelector.set(true);
        otterSelector.ack(batchId);
    }
```

**Comment by fhqi** [comment]
> SelectTask

多谢了
