### ISSUE TITLE
经常报这个异常是什么意思

### ISSUE THREAD

**Issue by eason0420** [alibaba/otter#683]
[pipelineId = 5,taskName = LoadWorker] WARN  c.a.o.s.a.i.setl.zookeeper.termin.WarningTerminProcess - nid:2[5:setl:load miss data w
ith keys:[{"dataType":"DB_BATCH","identity":{"channelId":5,"pipelineId":5,"processId":308589},"time":1545198717798}]]

**Comment by kaikai2000** [comment]
JVM内存设置大一点， 这个是因为内存的数据被垃圾回收了,otter采用弱引用，有些数据在jvm内存不足时会被回收。。

**Comment by kaikai2000** [comment]
报错后会重试的，数据不会丢的。

**Comment by eason0420** [comment]
ok，谢谢 @kaikai2000
