### ISSUE TITLE
分库分表主键冲突的情况下如何合成一张表

### ISSUE THREAD

**Issue by 1074559124** [alibaba/otter#685]
a1表id=1,name=liu;id=2,name=wang   a2表id=1,name=li;id=2,name=zhang   如何将这两张表的数据同步到单表a里面，想要的最终结果a表的数据为，id=1,name=liu;id=2,name=wang；id=1,name=li;id=2,name=zhang。a1，a2表里id为自增主键。

**Comment by kaikai2000** [comment]
方案： id+分片字段作为primary key ，目前支持drds，其他像mycat这种中间件需要自己改源码。

**Comment by agapple** [comment]
LS正解
