### ISSUE TITLE
4.2.17编译失败，缺jar包，mockit

### ISSUE THREAD

**Issue by mengfanling** [alibaba/otter#687]
Failure to find mockit:mockit:pom:0.999.10，缺少mocki-0.999.10，这个jar在哪，lib里的我已经安装了，网上也找不到，阿里的maven仓库也没有

**Comment by vinnie888** [comment]
lib/jtester-1.1.8.pom 中的jmockit版本，改回0.999.4，打包就没问题了，
不做单元测试只是打包的话这样应该没问题，我是这么解决的。

**Comment by mengfanling** [comment]
> lib/jtester-1.1.8.pom 中的jmockit版本，改回0.999.4，打包就没问题了，
> 不做单元测试只是打包的话这样应该没问题，我是这么解决的。

谢谢，可以了，BUILD SUCCESS
