### ISSUE TITLE
双A同步，出现字段冲突时数据进入重复死循环

### ISSUE THREAD

**Issue by charlygao** [alibaba/otter#69]
按照教程配置了双A同步的channel，开启了一致性算法。测试时发现无更新冲突时双向同步均正常，而一旦两个DB同时update一个字段为不同值，这个字段就开始反复在两个值之间变动，产生一个死循环。请问是否是配置有问题？是否有日志有助于排查此问题原因？期待您的回复。

节点布置：
机器A：zookeeper，manager， node1，mysql1
机器B：node2，mysql2

软件版本：
CentOS release 6.3
java version "1.6.0_24"
otter: 4.2.11
zookeeper: 3.4.6
mysql: 5.1.61

manager配置：
![image](https://cloud.githubusercontent.com/assets/7473689/5773312/cfb88c94-9d9b-11e4-9964-be7e93d57eaa.png)
![image](https://cloud.githubusercontent.com/assets/7473689/5773314/ee7aa28e-9d9b-11e4-9722-504f2cf07bde.png)
DDL同步为单向。其余设置均为默认值。

mysql配置：
[mysqld]
datadir=/var/lib/mysql
socket=/var/lib/mysql/mysql.sock
user=mysql
symbolic-links=0
# server-id两台机器分别配置为1和2
server-id=2
log-bin=/var/lib/mysql/log_bin
binlog-do-db=test
character-set-server=utf8
binlog_format=ROW
skip-name-resolve
[mysqld_safe]
log-error=/var/log/mysqld.log
pid-file=/var/run/mysqld/mysqld.pid

**Comment by charlygao** [comment]
已解决，问题出在mysql配置中的binlog-do-db=test

双A同步需要对otter的retl表也开启binlog，才能保持一致性。只对业务表开启binlog是不够的。

**Comment by gerori** [comment]
> 已解决，问题出在mysql配置中的binlog-do-db=test
> 
> 双A同步需要对otter的retl表也开启binlog，才能保持一致性。只对业务表开启binlog是不够的。

請問retl也要同步嗎？為什麼retl也需要binlog呢？

**Comment by agapple** [comment]
retl库需要开启binlog，otter会利用这个库的binlog来判断是否是回环同步
