### ISSUE TITLE
解除外键约束是否可行

### ISSUE THREAD

**Issue by liulangwa** [alibaba/otter#693]
是否可以node建立连接的时候 set foREIGN_KEY_CHECKS=0，来解除外键约束，这样的话会不会有什么问题

**Comment by agapple** [comment]
不会有影响，因为load执行的时候也是乱序执行，没有外键的保障处理

**Comment by zzcclp** [comment]
@liulangwa 请教下，怎么在node建立连接是set foreign_key_checks=0？

**Comment by liulangwa** [comment]
> @liulangwa 请教下，怎么在node建立连接是set foreign_key_checks=0？

改源码
