### ISSUE TITLE
单向同步DDL问题

### ISSUE THREAD

**Issue by alex-17** [alibaba/otter#70]
你好：
我们存在这样一种情况：在不同库名、不同表名之间单向同步（但双方表结构是完全相同的），经测试数据可以正常同步，但是当遇到DDL语句时就报错，如下：
pid:1 nid:1 exception:setl:com.alibaba.otter.node.etl.transform.exception.TransformException: no support ddl for [test.t1] to [test_bak.t2] , sql :ALTER TABLE `t1` ADD COLUMN `time`  datetime NULL AFTER `c_1`;

请问otter目前支持这种情况的同步吗？

**Comment by zhouyq** [comment]
把DDL同步选项关掉
Channel管理  >  Pipeline管理  >  编辑Pipeline    高级
![Uploading 屏幕快照 2015-01-20 下午12.55.52.png . . .]()

**Comment by alex-17** [comment]
我的意思是：是否支持这种场景的DDL语句更新？谢谢

**Comment by agapple** [comment]
目前otter暂时不支持这类不同库名的DDL同步，后续可以考虑解析ddl sql来支持
