### ISSUE TITLE
开启双A复制时需要retl库，需要密码为retl的retl用户，这个能配置么？

### ISSUE THREAD

**Issue by qin-jd** [alibaba/otter#705]
比如配置 读取retl库的用户和密码

**Comment by qin-jd** [comment]
我刚发现retl这个用户没有用？初始化sql创建的retl这个用户删了，依然可以同步成功

**Comment by saigu** [comment]
> retl用户只是举个例，链接数据库的账号要有这个权限

卧槽。。。我看了半天源码，想看看哪里配置了datasource的账号密码为retl的，啥都找不到。。。原来是这样。。。。

**Comment by dmanbu** [comment]
卧槽，原来是没用的，好坑
