### ISSUE TITLE
docker 镜像在哪里？

### ISSUE THREAD

**Issue by bjddd192** [alibaba/otter#708]
你好，请问你们最新版本的镜像在 hub.docker.com 中有推送么？我该如何拿到镜像呢？

**Comment by agapple** [comment]
暂时还没

**Comment by bjddd192** [comment]
好的，大概什么时候会有可用的镜像啊

**Comment by liulangwa** [comment]
自己build一个就可以

**Comment by bjddd192** [comment]
> 自己build一个就可以

俺是运维，表示很无奈。既然已经打出了镜像，为什么不推送到共仓给大家试用一下呢

**Comment by bjddd192** [comment]
我自己容器化了4.2.17的版本，初略测试可以正常使用，再深入使用看看。

**Comment by agapple** [comment]
下载源代码, cd docker && sh build.sh

**Comment by qq240996777** [comment]
> 你好，请问你们最新版本的镜像在 hub.docker.com 中有推送么？我该如何拿到镜像呢？

https://hub.docker.com/r/canal/otter-all 
这个地址，文档里面写错了。
其实你可以直接运行这个脚本，自动回去拉取docker文件的

curl -fsSL https://raw.githubusercontent.com/alibaba/otter/master/docker/run.sh | bash

**Comment by agapple** [comment]
LS正解
