### ISSUE TITLE
mysql 字符编码是utf8mb4如何支持

### ISSUE THREAD

**Issue by wuyjhp** [alibaba/otter#71]
目前otter不支持utf8mb4，如果才能支持utf8mb4
![Uploading 1.png . . .]()

**Comment by agapple** [comment]
需要升级mysql driver到5.1.26+

2015-02-09 18:29 GMT+08:00 wuyjhp <notifications@github.com>:

**Comment by ZengQiang** [comment]
MySQL数据库驱动升级到5.1.30后, 在选择utf8编码时还是提示字符集不匹配, 但是这个驱动版本是支持utf8mb4的
![qq 20150513142852](https://cloud.githubusercontent.com/assets/5753595/7604969/b49e02a8-f97c-11e4-86cb-386df10031bf.png)

**Comment by ZengQiang** [comment]
5.1.35版本可支持
