### ISSUE TITLE
otter怎么获取dml的sql语句

### ISSUE THREAD

**Issue by woaijava0802** [alibaba/otter#711]
otter的MessageParser中只在ddl情况下获取了RowChange的sql语句
![image](https://user-images.githubusercontent.com/42115723/51170333-2e046f80-18e9-11e9-83d1-1742d5aeed07.png)
dml的sql语句有获取吗？如果获取了，是在哪个类里面呢？因为我用EventData的getSql只能拿到ddl的sql，不能拿到dml的sql。

**Comment by agapple** [comment]
需要去了解一下binlog_format的几种格式，otter只支持row模式，无法拿到DML的sql语句
