### ISSUE TITLE
不支持连接mysql 8.0.12吗？

### ISSUE THREAD

**Issue by Magic-HLB** [alibaba/otter#714]
出现：throw 'allowScriptTagRemoting is false.'; 提示：抱歉,数据库未通过验证,请检查相关配置!
我检查了下，可以用navicat连接，开启了远程连接，账号密码都对，使用的root账户。

**Comment by qq240996777** [comment]
新版本已经支持mysql8了

**Comment by agapple** [comment]
mysql8.0的新版auth还不支持，可以在安装的时候使用老版本的auth，其余的binlog解析已经支持

**Comment by YUHAI0** [comment]
> 其余的binlog解析已经支持

”在安装的时候使用老版本auth' ,  具体怎么做呢？
