### ISSUE TITLE
报错提示CanalParseException

### ISSUE THREAD

**Issue by Magic-HLB** [alibaba/otter#717]
pid:1 nid:1 exception:canal:ottertest:com.alibaba.otter.canal.parse.exception.CanalParseException: command : 'show master status' has an error! pls check. you need (at least one of) the SUPER,REPLICATION CLIENT privilege(s) for this operation

**Comment by kaikai2000** [comment]
看下canal配置，里面配置的用户没有权限在master上面执行show master status
