### ISSUE TITLE
Otter跨机房同步时如何保证数据传输的安全性？

### ISSUE THREAD

**Issue by gangzi828** [alibaba/otter#718]
Otter跨机房同步时如何保证数据传输的安全性？即：数据从内网机房经网络传输到远端机房时，数据传输时是否经过加密处理的？如果没有加密处理，被拦截到后，是否存在泄漏数据的风险？关于Otter数据安全的问题好像看到的比较少，求指教，谢谢！

**Comment by agapple** [comment]
wiki里有介绍，有自己的加密处理

**Comment by penghuazhou** [comment]
@agapple , wiki哪个地方有介绍呢？没有找到介绍内容

**Comment by digdeep126** [comment]
@penghuazhou 你找到关于加密的介绍吗？我找了一下也没有找到...
