### ISSUE TITLE
otter如何处理命名不规范的关键字字段？

### ISSUE THREAD

**Issue by AlexRenCN** [alibaba/otter#719]
在mysql向oracle单向迁移的过程中发现了mysql数据库中的表有字段对应oracle的数据库关键字，启动channel后抛出异常nested exception is java.sql.SQLSyntaxErrorException: ORA-00923: FROM keyword not found where expected；
尝试用TestEventProcessor 自定义处理，却发现无法通过重设DML语句或者重设EventColumn的名字绕过，请问在不改变映射列名的情况下该如何处理？
是否考虑在TableData中添加一个别名？在构建TableData时发现关键字时自动配置和开放给用户自行配置
版本：canal-1.1.3-alpha-2以及otter-4.2.17

**Comment by agapple** [comment]
oracle的关键字没有特殊处理，mysql的关键字都做了转义，可以考虑通过过滤代码做列名转换吧
