### ISSUE TITLE
请问下 otter的node可以使用独立的canal服务吗？

### ISSUE THREAD

**Issue by jsonchina** [alibaba/otter#720]
我想单独部署canal，并且用otter连接我单独部署的canal 需要怎么做那

**Comment by qq240996777** [comment]
node 嵌入了canal，如果单独的canal的话 配置文件需要共享，node扮演了这个角色。

**Comment by jsonchina** [comment]
> node 嵌入了canal，如果单独的canal的话 配置文件需要共享，node扮演了这个角色。

这个配置文件共享需要修改代码吗  还是怎么做那

**Comment by jsonchina** [comment]
> > node 嵌入了canal，如果单独的canal的话 配置文件需要共享，node扮演了这个角色。
> 
> 这个配置文件共享需要修改代码吗 还是怎么做那

单独部署的话 就就可以把消息放在kafka里面,那么相对应的otter的消费代码是不是得自己去改

**Comment by qq240996777** [comment]
> > > node 嵌入了canal，如果单独的canal的话 配置文件需要共享，node扮演了这个角色。
> > 
> > 
> > 这个配置文件共享需要修改代码吗 还是怎么做那
> 
> 单独部署的话 就就可以把消息放在kafka里面,那么相对应的otter的消费代码是不是得自己去改

otter manager里面的配置是支持动态改的，比如说 A库->B库。
node是otter_manager的work节点，而canal只是拉取binglog的工作。

如果你把数据放到kafaka里面了，那么你需要使用到otter里面的load的工作了。
你可以把这块代码集成到你的kafka的comsumer中去。

**Comment by jsonchina** [comment]
> > > > node 嵌入了canal，如果单独的canal的话 配置文件需要共享，node扮演了这个角色。
> > > 
> > > 
> > > 这个配置文件共享需要修改代码吗 还是怎么做那
> > 
> > 
> > 单独部署的话 就就可以把消息放在kafka里面,那么相对应的otter的消费代码是不是得自己去改
> 
> otter manager里面的配置是支持动态改的，比如说 A库->B库。
> node是otter_manager的work节点，而canal只是拉取binglog的工作。
> 
> 如果你把数据放到kafaka里面了，那么你需要使用到otter里面的load的工作了。
> 你可以把这块代码集成到你的kafka的comsumer中去。

嗯 这个我知道,我意思是 现在otter不修改代码的情况下,支持用单独部署的canal吗

**Comment by qq240996777** [comment]
> > > > > node 嵌入了canal，如果单独的canal的话 配置文件需要共享，node扮演了这个角色。
> > > > 
> > > > 
> > > > 这个配置文件共享需要修改代码吗 还是怎么做那
> > > 
> > > 
> > > 单独部署的话 就就可以把消息放在kafka里面,那么相对应的otter的消费代码是不是得自己去改
> > 
> > 
> > otter manager里面的配置是支持动态改的，比如说 A库->B库。
> > node是otter_manager的work节点，而canal只是拉取binglog的工作。
> > 如果你把数据放到kafaka里面了，那么你需要使用到otter里面的load的工作了。
> > 你可以把这块代码集成到你的kafka的comsumer中去。
> 
> 嗯 这个我知道,我意思是 现在otter不修改代码的情况下,支持用单独部署的canal吗

你可以单独部署canal了，为啥还要部署otter？ 你可以只部署canal即可。

**Comment by jsonchina** [comment]
> > > > > > node 嵌入了canal，如果单独的canal的话 配置文件需要共享，node扮演了这个角色。
> > > > > 
> > > > > 
> > > > > 这个配置文件共享需要修改代码吗 还是怎么做那
> > > > 
> > > > 
> > > > 单独部署的话 就就可以把消息放在kafka里面,那么相对应的otter的消费代码是不是得自己去改
> > > 
> > > 
> > > otter manager里面的配置是支持动态改的，比如说 A库->B库。
> > > node是otter_manager的work节点，而canal只是拉取binglog的工作。
> > > 如果你把数据放到kafaka里面了，那么你需要使用到otter里面的load的工作了。
> > > 你可以把这块代码集成到你的kafka的comsumer中去。
> > 
> > 
> > 嗯 这个我知道,我意思是 现在otter不修改代码的情况下,支持用单独部署的canal吗
> 
> 你可以单独部署canal了，为啥还要部署otter？ 你可以只部署canal即可。

我想用Otter做消费,同步数据

**Comment by qq240996777** [comment]
otter目前不支持消费kafka里面的数据。 建议你再看下otter的工作原理。

**Comment by jsonchina** [comment]
> otter目前不支持消费kafka里面的数据。 建议你再看下otter的工作原理。

是的 我看过otter是从内存队列里面拿的数据,想的既然现在用的内嵌的canal为什么不能独立部署。然后可用性可以更高些
