### ISSUE TITLE
重启docker，访问不了面板，logs里报错：EXIT CODE: 0

### ISSUE THREAD

**Issue by jimstory** [alibaba/otter#723]
docker ps -a，状态如下：
f28694c5e6b8        canal/otter-all       "/alidata/bin/main.s…"   5 weeks ago         Exited (1) 3 minutes ago                                                                                                                                                                 otter-all

查看logs，详细如下：

[root@localhost ~]# docker logs f28694c5e6b8
DOCKER_DEPLOY_TYPE=VM
==> INIT /alidata/init/02init-sshd.sh
==> EXIT CODE: 0
==> INIT /alidata/init/fix-hosts.py
==> EXIT CODE: 0
==> INIT DEFAULT
Generating SSH1 RSA host key:                              [  OK  ]
Starting sshd:                                             [  OK  ]
Starting crond:                                            [  OK  ]
==> INIT DONE
==> RUN /home/admin/app.sh
==> START ...
start mysql ...
Starting mysqld:                                           [  OK  ]
mysql start successful
start zookeeper ...
zookeeper start successful
start manager ...
manager start successful
start node ...
node start successful
you can visit manager link : http://192.168.40.73:8080/ , just have fun !
==> START SUCCESSFUL ...
==> STOP
stop node
192.168.40.73: stopping otter node 474 ... 
Oook! cost:2
stop node successful ...
stop manager
stop manager successful ...
stop zookeeper
stop zookeeper successful ...
stop zookeeper
stop zookeeper successful ...
stop mysql ...
DOCKER_DEPLOY_TYPE=VM
==> INIT /alidata/init/02init-sshd.sh
==> EXIT CODE: 0
==> INIT /alidata/init/fix-hosts.py
==> EXIT CODE: 0
==> INIT DEFAULT
Starting sshd:                                             [  OK  ]
Starting crond:                                            [  OK  ]
==> INIT DONE
==> RUN /home/admin/app.sh
==> START ...
start mysql ...
Starting mysqld:                                           [  OK  ]
mysql start successful
start zookeeper ...
zookeeper start successful
start manager ...
manager start successful
start node ...
node start successful
you can visit manager link : http://192.168.40.73:8080/ , just have fun !
==> START SUCCESSFUL ...
==> STOP
stop node
192.168.40.73: stopping otter node 417 ... 
Oook! cost:3
stop node successful ...
stop manager
stop manager successful ...
stop zookeeper
stop zookeeper successful ...
stop zookeeper
stop zookeeper successful ...
stop mysql ...
DOCKER_DEPLOY_TYPE=VM
==> INIT /alidata/init/02init-sshd.sh
==> EXIT CODE: 0
==> INIT /alidata/init/fix-hosts.py
==> EXIT CODE: 0
==> INIT DEFAULT
Starting sshd:                                             [  OK  ]
Starting crond:                                            [  OK  ]
==> INIT DONE
==> RUN /home/admin/app.sh
==> START ...
start mysql ...
Starting mysqld:                                           [  OK  ]
mysql start successful
start zookeeper ...
zookeeper start successful
start manager ...
manager start successful
start node ...
node start successful
you can visit manager link : http://192.168.40.73:8080/ , just have fun !
==> START SUCCESSFUL ...
DOCKER_DEPLOY_TYPE=VM
==> INIT /alidata/init/02init-sshd.sh
==> EXIT CODE: 0
==> INIT /alidata/init/fix-hosts.py
==> EXIT CODE: 0
==> INIT DEFAULT
Starting sshd:                                             [  OK  ]
Starting crond:                                            [  OK  ]
==> INIT DONE
==> RUN /home/admin/app.sh
==> START ...
start mysql ...
Starting mysqld:                                           [  OK  ]
mysql start successful
start zookeeper ...
zookeeper start successful
start manager ...
DOCKER_DEPLOY_TYPE=VM
==> INIT /alidata/init/02init-sshd.sh
==> EXIT CODE: 0
==> INIT /alidata/init/fix-hosts.py
==> EXIT CODE: 0
==> INIT DEFAULT
Starting sshd:                                             [  OK  ]
Starting crond:                                            [  OK  ]
==> INIT DONE
==> RUN /home/admin/app.sh
==> START ...
start mysql ...
Starting mysqld:                                           [  OK  ]
mysql start successful
start zookeeper ...
zookeeper start successful
start manager ...
DOCKER_DEPLOY_TYPE=VM
==> INIT /alidata/init/02init-sshd.sh
==> EXIT CODE: 0
==> INIT /alidata/init/fix-hosts.py
==> EXIT CODE: 0
==> INIT DEFAULT
Starting sshd:                                             [  OK  ]
Starting crond:                                            [  OK  ]
==> INIT DONE
==> RUN /home/admin/app.sh
==> START ...
start mysql ...
Starting mysqld:                                           [  OK  ]
mysql start successful
start zookeeper ...
zookeeper start successful
start manager ...
DOCKER_DEPLOY_TYPE=VM
==> INIT /alidata/init/02init-sshd.sh
==> EXIT CODE: 0
==> INIT /alidata/init/fix-hosts.py
==> EXIT CODE: 0
==> INIT DEFAULT
Starting sshd:                                             [  OK  ]
Starting crond:                                            [  OK  ]
==> INIT DONE
==> RUN /home/admin/app.sh
==> START ...
start mysql ...
Starting mysqld:                                           [  OK  ]
mysql start successful
start zookeeper ...
zookeeper start successful
start manager ...
DOCKER_DEPLOY_TYPE=VM
==> INIT /alidata/init/02init-sshd.sh
==> EXIT CODE: 0
==> INIT /alidata/init/fix-hosts.py
==> EXIT CODE: 0
==> INIT DEFAULT
Starting sshd:                                             [  OK  ]
Starting crond:                                            [  OK  ]
==> INIT DONE
==> RUN /home/admin/app.sh
==> START ...
start mysql ...
Starting mysqld:                                           [  OK  ]
mysql start successful
start zookeeper ...
zookeeper start successful
start manager ...
DOCKER_DEPLOY_TYPE=VM
==> INIT /alidata/init/02init-sshd.sh
==> EXIT CODE: 0
==> INIT /alidata/init/fix-hosts.py
==> EXIT CODE: 0
==> INIT DEFAULT
Starting sshd:                                             [  OK  ]
Starting crond:                                            [  OK  ]
==> INIT DONE
==> RUN /home/admin/app.sh
==> START ...
start mysql ...
Starting mysqld:                                           [  OK  ]
mysql start successful
start zookeeper ...
zookeeper start successful
start manager ...
DOCKER_DEPLOY_TYPE=VM
==> INIT /alidata/init/02init-sshd.sh
==> EXIT CODE: 0
==> INIT /alidata/init/fix-hosts.py
==> EXIT CODE: 0
==> INIT DEFAULT
Starting sshd:                                             [  OK  ]
Starting crond:                                            [  OK  ]
==> INIT DONE
==> RUN /home/admin/app.sh
==> START ...
start mysql ...
Starting mysqld:                                           [  OK  ]
mysql start successful
start zookeeper ...
zookeeper start successful
start manager ...

**Comment by qq240996777** [comment]
manager没启动成功。
估计你的docker的内存不够。

**Comment by jimstory** [comment]
我这样做了一下，发现了一个问题
重启服务器，容器启动不了，确实是manager没有启动成功
但是，
1，把原来的数据zkData文件夹备份
2，重新安装
3，替换备份文件夹
这才能启动，数据还在
