### ISSUE TITLE
定期删除otter采集的指标数据

### ISSUE THREAD

**Issue by powqabc** [alibaba/otter#725]
otter采集的指标数据存在otter的mysql数据库里，delay_stat、log_record、table_history_stat、throughput_stat这些表都存储了历史数据，这些指标数据有定期删除功能吗？保留所有的历史数据意义不大

**Comment by skytalemcc** [comment]
我都是自己删除的。表结构并不复杂。你可以写个定时任务

**Comment by agapple** [comment]
LS正解
