### ISSUE TITLE
channel无法启动，删除按钮无法点击，这是啥原因？

### ISSUE THREAD

**Issue by WMSen** [alibaba/otter#738]
日志报错
[/?action=channelAction&channelId=16&status=start&pageIndex=1&searchKey=&eventSubmitDoStatus=true] ERROR c.a.o.manager.biz.config.channel.impl.ChannelServiceImpl - ERROR ## switch the channel(16) status has an exception.

**Comment by agapple** [comment]
switch the channel(16) status has an exception ， 后面应该有对应的异常
