### ISSUE TITLE
otter自由门如何配置

### ISSUE THREAD

**Issue by chenlong0427** [alibaba/otter#739]
根据文档中说描述的方式，配置自由门，但是一次都没有成功过；
我当前环境：
节点A：otter-manager，mysql（otter，retl和test库），zokeeper
节点B：otter-node，mysql（retl和test库）
其中只有test库的数据在同步，retl库数据没有同步；

**Comment by agapple** [comment]
看一下历史issue吧，很多人问过类似的问题了
