### ISSUE TITLE
双A环境，中间版本丢失

### ISSUE THREAD

**Issue by woson-wang** [alibaba/otter#743]
环境说明：
A和B之间为双A同步，**A为主站点**，开启数据一致性
同步一致性： 基于当前日志变更
同步模式：列记录模式
数据一致性算法：单向回环补救  
一致性反查数据库延迟阀值(s)：10

过程：
1. 在B端对某行进行了多次变更（即产生了多个版本），则数据会同步到A，这部分binlog会再同步回到B
2. B端在update后，马上进行查询，但是在查询时（同步会由A再回到B），查询到了一个中间状态的版本，此时报错

由于单向回环补救会使B同步到A的binlog，再在B端进行重放，重放过程若有查询，则会导致查询到中间版本。

请问下，该种情况怎么可以避免呢？

**Comment by agapple** [comment]
两边不要改同一个列值

**Comment by woson-wang** [comment]
> 两边不要改同一个列值

只有B端（非主站点）在进行操作，A端在这个过程没有操作。
相当于是B端产生的binlog，单向回环重放的过程中，B端进行了读取，读取到的是binlog的中间状态

**Comment by zzcclp** [comment]
@agapple 我也遇到这个问题了，只有在B端（非主站点）进行操作，insert--update1--update2--update3，此时update2有可能会获取到insert时的数据，即A端单向回环重放导致的。请问这个问题怎么解决呢？

**Comment by zzcclp** [comment]
@woson-wang 请问这个问题解决了吗

**Comment by zzcclp** [comment]
@agapple 采用跟随使用数据库主备，来切换对应的主站点，是否可行呢？

**Comment by linqh1** [comment]
感觉这问题不好解决

**Comment by agapple** [comment]
可以看一下wiki对于数据一致性同步的介绍，可以有反查机制来规避中间版本
