### ISSUE TITLE
otter无法选择数据源

### ISSUE THREAD

**Issue by CrazyJugger** [alibaba/otter#748]
添加数据表的时候、无法选择数据源、点击选择 无反应

**Comment by CrazyJugger** [comment]
测试数据源连接是通过的

**Comment by lianbitangjin** [comment]
> 测试数据源连接是通过的

大哥你解决了吗？？这个问题我看了浏览器日志，报个 window.opener.changeKeyword is not a function
这个是otter的bug，还是我的配置问题，关键是我另一个配置是可以的，求回复

**Comment by CrazyJugger** [comment]
后来 我将otter重启之后 清空数据表配置之后 就可以了

**Comment by Tsuiwiki** [comment]
我重启manage可以选择了
