### ISSUE TITLE
otter配置数据源时是否可以使用域名代替数据库IP （由于IP为变动IP）

### ISSUE THREAD

**Issue by Mycheers** [alibaba/otter#749]

**Comment by SwaggyQ** [comment]
可以的，我的使用情况里就是用域名的
![image](https://user-images.githubusercontent.com/16660199/56104172-4a0bc180-5f69-11e9-8b48-99cac9498ba8.png)

**Comment by Mycheers** [comment]
需要添加什么配置吗？我这边使用域名一直报错，连接不到数据库，使用ip才可以

**Comment by agapple** [comment]
这个是配置序列化所带来的问题，会序列化成域名进行存储

**Comment by agapple** [comment]
#812 已经修复

**Comment by Mycheers** [comment]
> 可以的，我的使用情况里就是用域名的
> ![image](https://user-images.githubusercontent.com/16660199/56104172-4a0bc180-5f69-11e9-8b48-99cac9498ba8.png)

node manager都是内网，只用外网域名需要改什么配置吗 ？
![image](https://user-images.githubusercontent.com/34181528/65293472-ecba1300-db8d-11e9-8f68-4247f4114708.png)

**Comment by agapple** [comment]
是否网络联通不了？
