### ISSUE TITLE
直接往otter数据库导数据，是否可以正常使用

### ISSUE THREAD

**Issue by loadingkang** [alibaba/otter#750]
可以直接往otter数据库里面插入数据源、canal、channel、pipeline、映射关系等数据嘛，node是否可以正常操作这些数据

**Comment by SwaggyQ** [comment]
以我的经验是会报错的，在进入主页的时候会报在zk上找不到节点的问题。可以手动在zk上添加节点解决问题，也可以用主页上的一键补齐功能初始化
![image](https://user-images.githubusercontent.com/16660199/56103660-9a355480-5f66-11e9-8e67-425a86af6d5c.png)

**Comment by agapple** [comment]
LS正解
