### ISSUE TITLE
Docker启动了Otter，但是为什么没有1099这个端口

### ISSUE THREAD

**Issue by yuzd** [alibaba/otter#755]
我要新加node 但是
otter-server只开启了以下端口
 0.0.0.0:2088-2090->2088-2090/tcp, 0.0.0.0:2181->2181/tcp, 0.0.0.0:8080-8081->8080-8081/tcp
我看添加node的文档要配置node连接 manager的1099端口
但是上面都没有1099端口是啥情况？是1099改成了别的了吗？

**Comment by HUIHUIHUANG2018** [comment]
标配的1099端口，在docker内改为了8081，修改的sh文件在docker内的/home/admin/app.sh
![image](https://user-images.githubusercontent.com/37581289/69854189-6cb5d500-12c3-11ea-876d-9639fdd8ac00.png)
