### ISSUE TITLE
请教中美异地配置otter中关于cannal问题

### ISSUE THREAD

**Issue by yuzd** [alibaba/otter#756]
我目前按照如下方式配置的
杭州一台阿里云
里面启动 manager node zokepper 和 mysql

美国一台阿里云
里面启动了 node 配置了指向了杭州阿里云的manager
并且也跑了mysql

我希望达成的效果是杭州阿里云和美国阿里云的一张表可以双向同步

我到配置canal的实收有疑问。
我在杭州阿里云的manager进行添加
2个cannal分别配置的是杭州和美国的mysql(cannal类型是内置)
疑问点：页面上并没有指定这个cannal 是在哪个node进行启动的。
假如说都是在杭州的阿里云启动了2个cannal那不就是美国的机器的mysql需要把binlog传输到杭州 这岂不是很慢，还是说manager会调度美国的mysql的canal会在美国的node创建？

**Comment by SwaggyQ** [comment]
在otter里面的重要的数据通路是  channel - pipeline ，一个channle里面配置多个pipeline，你说的canal就是在pipeline的配置页面去选择的，node也是，在pipeline配置页面中可以选择
![image](https://user-images.githubusercontent.com/16660199/56186533-3be5a000-6052-11e9-83c4-f1ae4af9ec9f.png)
不清楚你想问的是不是这个问题，如果不是的话，可以再发上来讨论一下

**Comment by yuzd** [comment]
@SwaggyQ 多谢回复，我的canal配置目前是这样的 

![image](https://user-images.githubusercontent.com/16083659/56187864-810bd100-6056-11e9-8a56-8862039ae707.png)

我的疑问是我目前配置的这个国外的canal 数据源是国外的mysql的数据源
因为我的manager是国内部署的 那么是不是这个canal服务是在国内的？

**Comment by SwaggyQ** [comment]
对于这个现象我的建议是检查一下国外的node和你的zk连接是不是通的，然后确认一下你的zk路径/otter/channel/{channelId}/{pipelineId}/里面是什么，有子路径/mainstem的话，看看里面是什么值。我个人看法是可能是zk不通，不保证对哈，可以先检查一下

**Comment by yuzd** [comment]
@SwaggyQ 谢谢回复。我有一个怀疑您帮我看下下面这个图：
![image](https://user-images.githubusercontent.com/16083659/56190789-959f9780-605d-11e9-9d6f-1cf3dcd2a12b.png)

**Comment by SwaggyQ** [comment]
哦那是的，你可以看一下在manager的channel页面上点下启用按钮后，在代码中会去得到对应的node的 ip+port，用于通知
![image](https://user-images.githubusercontent.com/16660199/56192028-119adf00-6060-11e9-83b6-a640be9f487e.png)
然后在node端会有相应的响应方法来处理事件，
![image](https://user-images.githubusercontent.com/16660199/56192100-41e27d80-6060-11e9-89a9-127ae7b12a75.png)
然后才会开始在node中的SETL任务，所以我觉得你可以针对这个port问题排查一下

**Comment by yuzd** [comment]
@SwaggyQ 端口改好了之后 状态显示工作中，然后我国内修改一条数据 发现同步到国外失败了
日志如下：
![image](https://user-images.githubusercontent.com/16083659/56210419-65b9b980-6088-11e9-9e0a-c0a575719b47.png)
![image](https://user-images.githubusercontent.com/16083659/56210492-897cff80-6088-11e9-9a62-ab589fdec77f.png)

**Comment by SwaggyQ** [comment]
我看了一下，应该就是因为你这个是国内国外两个node，所以其中国内node的SE阶段处理完之后，需要用dubbo rpc的方式通知海外的node节点开始TL阶段，但是你这个dubbo rpc连不通，你看一下异常栈中time out的那个url，就是47.254.的那个地址连不通，看看是端口问题还是网络连接问题

**Comment by yuzd** [comment]
![image](https://user-images.githubusercontent.com/16083659/56213759-38243e80-608f-11e9-898e-698571b43b2d.png)
您帮忙看下 我的端口是不是都开了？还缺少别的端口吗？比如 11111端口也需要开出来吗？

**Comment by linqh1** [comment]
这就没下文了？

**Comment by linqh1** [comment]
你这zk是新装的吧
