### ISSUE TITLE
ProcessTermin has an error! retry

### ISSUE THREAD

**Issue by ppj19891020** [alibaba/otter#763]
导致任务被挂起，然后一直重试消费
错误如下：
21-2019-04-20-38.log:2019-04-20 18:52:09.175 [pipelineId = 21,taskName = ProcessTermin] INFO  com.alibaba.otter.node.etl.select.SelectTask - [21] ProcessTermin has an error! retry...
21-2019-04-20-38.log-com.alibaba.otter.node.etl.select.exceptions.SelectException: unmatched terminId, SelectTask batchId = 2581683 processId = 2572237 and Termin Event: TerminEventData[type=NORMAL,code=setl,desc=,currNid=2,processId=2572267,startTime=1555757499440,endTime=1555757499531,firstTime=1555757499000,batchId=2581713,number=1,size=<null>,exts=<null>,pipelineId=21]

**Comment by agapple** [comment]
unmatched terminId，停用启用一下任务
