### ISSUE TITLE
retl_mark表id为什么用threadId呢？

### ISSUE THREAD

**Issue by xmpace** [alibaba/otter#767]
看源码过程中发现回环控制给语句打标记时retl_mark表的id键值用的threadId，这个值是一个[0,300]的值，如果一个库有多个上游库往它同步，会不会出现多个上游用到同一个threadId的情况，这样的话针对retl_mark表应该会出现同一记录锁争用的情况吧？

**Comment by agapple** [comment]
会有概率出现并发，所以设计上用了300个id来降低并发
