### ISSUE TITLE
canal配置gtid位点

### ISSUE THREAD

**Issue by clixiang** [alibaba/otter#768]
canal的位点设置，如果启用gtid，怎么配置对应的位点信息啊？找了很久没找到。

下面的这3个值怎么设置？

{"journalName":"","position":0,"timestamp":0};

**Comment by SwaggyQ** [comment]
在对应的数据库服务器上show master status，然后{"journalName":"","position":0,"timestamp":0,"gtid":xxxxxxx};

**Comment by agapple** [comment]
LS正解
