### ISSUE TITLE
配置文件密码和镜像连接密码不一致。。。

### ISSUE THREAD

**Issue by AllenHu2018** [alibaba/otter#774]
otter/manager/deployer/src/main/resources/otter.properties密码是hello
otter-master/docker/image/admin/app.sh 密码是otter

**Comment by AllenHu2018** [comment]
otter-master/docker/image/admin/app.sh 密码是otter
包括MYSQL_USER_PASSWORD和MYSQL_ROOT_PASSWORD

**Comment by agapple** [comment]
docker是默认的内置配置，而otter.properties是让用户自行修改
