### ISSUE TITLE
oracle连接,编码问题

### ISSUE THREAD

**Issue by Perterually** [alibaba/otter#781]
![编码](https://user-images.githubusercontent.com/12246868/58220713-7e318980-7d42-11e9-972b-f5f05c67ba4c.png)

**Comment by agapple** [comment]
这个只是提示，不影响配置保存，如果确认是utf8，可以忽略之

**Comment by Perterually** [comment]
> 这个只是提示，不影响配置保存，如果确认是utf8，可以忽略之

好的，谢谢
