### ISSUE TITLE
多次update操作合并之后，导致从机房唯一索引冲突如何解决

### ISSUE THREAD

**Issue by gaoshiwei** [alibaba/otter#784]
otter将多次update操作合并之后，导致本该提前执行的SQL,执行时间推后，最终导致从机房唯一索引冲突如何解决。是否有参数，可以配置不合并update操作。还有就是
获取批次数据超时时间： 300 参数设置为300毫秒之后，观察日志相差几秒的SQL还是被合并，是超时时间没生效吧

**Comment by gaoshiwei** [comment]
通过去掉合并算法和数据归并解决

**Comment by wojiaoliuhao** [comment]
大哥，能否详细说下怎么操作的呢
