### ISSUE TITLE
Otter Node硬件要求。

### ISSUE THREAD

**Issue by PassXml** [alibaba/otter#799]
数据库同步中选用了otte作为方案，基于本地docker的数据库同步，无问题。在仿真环境下（两台阿里云服务器）做数据同步，同步状态总会被挂起，并报该错误，
【setl:transform miss data with keys:[RpcPipeKey[nid=1,identity=Identity[channelId=2,pipelineId=5,processId=35],time=1563853525511,dataType=DB_BATCH]]】

查阅相关资料后，得知跟节点负载率有关系，实际同步量并不大（一条示例数据），所以怀疑是内存不足导致被gc回收，节点同步数据被丢失。所以提出该issues，望大佬告知node节点硬件最低配置。

**Comment by agapple** [comment]
减少pipeline运行数目 或者 canal的buffer大小

**Comment by leeyisoft** [comment]
不知道 4个地区（深圳阿里云RDS 美国硅谷RDS 新加坡RDS 以后还可能做 迪拜）部署 alibaba/otter 硬件配置最低要求是多少？
