### ISSUE TITLE
otter manager公网访问

### ISSUE THREAD

**Issue by yazhou0514** [alibaba/otter#800]
只有一个公网端口80，如何配置才能实现manager通过nginx的公网访问？
修改过jetty的context为：/otter，但是页面里很多地址都是固定的otter.domainName:otter.port

## otter manager domain name
otter.domainName = 10.2.4.146
## otter manager http port
otter.port = 8089
## jetty web config xml
otter.jetty = jetty.xml

## otter communication port
otter.communication.manager.port = 1099

## otter arbitrate connect manager config
otter.manager.address = ${otter.domainName}:${otter.communication.manager.port}

**Comment by linqh1** [comment]
修改urls.xml中这个配置
![image](https://user-images.githubusercontent.com/42435177/62354394-4e231580-b53f-11e9-9cff-2f7277353adb.png)

**Comment by linqh1** [comment]
otter.domainName要改成域名啊
