### ISSUE TITLE
如何进行全量数据的同步

### ISSUE THREAD

**Issue by raisemeup** [alibaba/otter#802]
刚接触otter，对otter的很多东西还不了解，想咨询以下各位大神，otter可否实现存量数据的同步，如果可以的话大体是一个怎么样的操作流程，万分感谢！

**Comment by linqh1** [comment]
什么叫存量数据同步？全量？

**Comment by raisemeup** [comment]
对，是全量

**Comment by raisemeup** [comment]
> 什么叫存量数据同步？全量？

对，是全量

**Comment by linqh1** [comment]
全量备份的话，otter有个自由门的功能。
你可以这里看到（搜："自 由 门"带空格）：https://github.com/alibaba/otter/wiki/Manager%E9%85%8D%E7%BD%AE%E4%BB%8B%E7%BB%8D

不过我没用过自由门这个功能，感觉太麻烦。

一般全量同步我都是这么做的：

1. 全量备份（备份前请确认binlog已经开启）
mysqldump --single-transaction **--master-data=2** --databases db1 db2 -u user -p > full_bak.sql
[注]: 必须使用--master-data=2，这样在sql中才有会备份文件的位点信息，如下
![image](https://user-images.githubusercontent.com/42435177/62844351-47d92a00-bcf3-11e9-8c3f-9425a9310cfe.png)

2. 在otter中创建canal，指定位点信息，如下（以上图的位点信息为例）：
![image](https://user-images.githubusercontent.com/42435177/62844386-92f33d00-bcf3-11e9-8601-a6deadd8b272.png)

3. 然后创建channel，pipline就和正常的步骤一样了

你可以参考一下

**Comment by raisemeup** [comment]
> 全量备份的话，otter有个自由门的功能。
> 你可以这里看到（搜："自 由 门"带空格）：https://github.com/alibaba/otter/wiki/Manager%E9%85%8D%E7%BD%AE%E4%BB%8B%E7%BB%8D
> 
> 不过我没用过自由门这个功能，感觉太麻烦。
> 
> 一般全量同步我都是这么做的：
> 
> 1. 全量备份（备份前请确认binlog已经开启）
>    mysqldump --single-transaction **--master-data=2** --databases db1 db2 -u user -p > full_bak.sql
>    [注]: 必须使用--master-data=2，这样在sql中才有会备份文件的位点信息，如下
>    ![image](https://user-images.githubusercontent.com/42435177/62844351-47d92a00-bcf3-11e9-8c3f-9425a9310cfe.png)
> 2. 在目标库执行上述的full_bak.sql
> 3. 在otter中创建canal，指定位点信息，如下（以上图的位点信息为例）：
>    ![image](https://user-images.githubusercontent.com/42435177/62844386-92f33d00-bcf3-11e9-8601-a6deadd8b272.png)
> 4. 然后创建channel，pipline就和正常的步骤一样了
> 
> 你可以参考一下

好的，我试试，万分感谢
