### ISSUE TITLE
eventData after viewExtractor has no pks , pls check

### ISSUE THREAD

**Issue by ccjetweat** [alibaba/otter#810]
eventData after viewExtractor has no pks , pls check异常
源表和目标表在同一阿里云RDS实例上，只是不同的库，源库的表只同步一部分字段到目标库的表，目标表是一个新建的表，只有表结构，无外键字段，有一个主键字段，其他没什么特别的字段，channel开启之后，显示挂起状态，看同步日志，显示如下：
pid:30 nid:2 exception:setl:com.alibaba.otter.node.etl.extract.exceptions.ExtractException: eventData after viewExtractor has no pks , pls check! identity:Identity[channelId=30,pipelineId=30,processId=4], new eventData:EventData[tableId=152,tableName=customer,schemaName=souche_crm,eventType=UPDATE,executeTime=1566472516000,oldKeys=[],keys=[],columns=[EventColumn[index=37,columnType=93,columnName=date_update,columnValue=2019-08-22 19:15:16,isNull=false,isKey=false,isUpdate=true]],size=523,pairId=-1,sql=,ddlSchemaName=,syncMode=,syncConsistency=,remedy=false,hint=,withoutSchema=false]
这个是什么原因呀，使用自定义的binlog位点也是报这个错误，能帮忙分析一下吗

**Comment by linqh1** [comment]
![image](https://user-images.githubusercontent.com/42435177/63560096-41667000-c587-11e9-916e-56331e00c97e.png)
没主键啊

**Comment by ccjetweat** [comment]
> ![image](https://user-images.githubusercontent.com/42435177/63560096-41667000-c587-11e9-916e-56331e00c97e.png)
> 是不是源库没主键啊

嗯，发现问题了，源表的主键没有创建到目标表，导致无主键报错，执行了DDL，添加主键字段到目标表，在管道高级设置关闭DDL同步，跳过DDL错误检测，重启channel,同步恢复正常了
