### ISSUE TITLE
保存canal时，数据库ip自动转换为hostname保存到数据库

### ISSUE THREAD

**Issue by linqh1** [alibaba/otter#812]
新建/编辑canal时，数据库地址填写本机ip，结果保存的时候被自动转化为manager所在机器的hostname了。

这样canal在其他node上执行的时候，有可能会出现node不识别manager hostname的情况吧？

查看了下源代码，FastJson在序列化json的时候出的问题

![image](https://user-images.githubusercontent.com/42435177/63565063-0e79a780-c59a-11e9-9cd8-5e099e4ab7a2.png)

本来想写一个自定义类继承InetSocketAddress的，但是发现InetSocketAddress的getHostName是final的，有没有其他解决方法能保证数据库存的是ip地址？

**Comment by happyguy1986** [comment]
试试反射？
