### ISSUE TITLE
心跳SQL不允许使用select,建议为insert/update,定时产生binlog数据

### ISSUE THREAD

**Issue by pengpai2016** [alibaba/otter#813]
1、我想把“心跳sql：” 修改为 select version()，提示 “心跳SQL不允许使用select,建议为insert/update,定时产生binlog数据” 
2、虽然原来心跳sql也可以用，但是我当前环境有一个问题是mysql 设置了 autocommit=OFF，所以心跳的这条语句一直不提交，造成事物积压在那。
3、当前环境  autocommit=OFF 是应用端要求，不让改成  autocommit=ON
我该怎么办......

**Comment by linqh1** [comment]
改源码，放宽限制。不过可能得测试一下有没有什么负面影响

**Comment by linqh1** [comment]
或者你在原本的语句后面加一个commit命令？

**Comment by pengpai2016** [comment]
后面加commit，我测试过，不好用

**Comment by welyss** [comment]
判断逻辑是startwith，可以/* */select * from windtest;这么搞。。。。不过你心跳不用写的操作就没意义了啊，如果单纯为了避免事物积压不如直接关掉。。。。
如果要修改autocommit，只能改canal项目的MysqlEventParser.java里的相关代码了
