### ISSUE TITLE
奇怪的报警：pid:321 delay_time:56792 seconds, but delay 1815 seconds no update

### ISSUE THREAD

**Issue by linqh1** [alibaba/otter#816]
报警信息如题，pipline页面显示延迟15h+。

我以为执行了什么大事务导致同步延迟这么大，但是我尝试在源库更新了一个字段，立刻就同步到目标库了。延迟时间缩短为0.9s。

为什么同步无阻塞的情况下还会一直报这个错？

**Comment by linqh1** [comment]
node日志：
![image](https://user-images.githubusercontent.com/42435177/63903875-a3b8e800-ca41-11e9-9ffa-48bae1d5df30.png)

**Comment by linqh1** [comment]
一些额外的信息：
周一上午的时候通知某些节点维护，所以我把select，node涉及到的机器切换到其他机器上。
当时的切换步骤如下：
1. 暂停channel
2. 编辑pipline中select、load机器，切换到正常机器上
3. 推送channel，启用channel

切换后我还测试了一下，是可以正常进行同步的。

而且周三白天的时候也还是正常的，就今天周四上班的时候，发现油箱收到好多封delaytime告警。

然后我就重启channel，并且在源库更新了一笔数据，是能够反映到目标库的。

现在已经没有告警了，只是不清楚为什么在同步无阻塞的情况下，会有这个告警？

**Comment by welyss** [comment]
感觉像是源库一直没更新导致的，可以设置个position超时报警然后自动恢复，再配下canal的开启心跳，在源库上间隔性的做一次更新动作试试

**Comment by linqh1** [comment]
> 感觉像是源库一直没更新导致的，可以设置个position超时报警然后自动恢复，再配下canal的开启心跳，在源库上间隔性的做一次更新动作试试

这个出问题的同步，源库只是个测试环境，确实更新没那么频繁。
我试试看你说的那个方法，不过可能很难复现

**Comment by linqh1** [comment]
对于这种更新不频繁的库，开启了canal的心跳之后就没再出现过这个问题了
