### ISSUE TITLE
配置双A同步，执行了初始化sql，为何还会出现table 'retl.retl_mark' doesn't exist 

### ISSUE THREAD

**Issue by liuyong520** [alibaba/otter#822]
当我配置双A同步，我执行了初始化sql脚本。但是还是出现了Table 'retl.retl_mark' doesn't exist

wget https://raw.github.com/alibaba/otter/master/node/deployer/src/main/resources/sql/otter-system-ddl-mysql.sql

pid:5 nid:1 exception:setl:com.alibaba.otter.node.etl.load.exception.LoadException: java.util.concurrent.ExecutionException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [SELECT COUNT(*) FROM retl.retl_mark WHERE id BETWEEN 0 AND 999]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'retl.retl_mark' doesn't exist

我的otter配置：
otter.database.driver.url = jdbc:mysql://k8s-n1:3307/otter
otter.database.driver.username = root
otter.database.driver.password = 123456

## otter communication port
otter.communication.manager.port = 1099

## otter communication pool size
otter.communication.pool.size = 10

## default zookeeper address
otter.zookeeper.cluster.default = 127.0.0.1:2184,127.0.0.1:2183,127.0.0.1:2182
## default zookeeper sesstion timeout = 60s
otter.zookeeper.sessionTimeout = 60000

## otter arbitrate connect manager config
otter.manager.address = ${otter.domainName}:${otter.communication.manager.port}

## should run in product mode , true/false
otter.manager.productionMode = true

## self-monitor enable or disable
otter.manager.monitor.self.enable = true
## self-montir interval , default 120s
otter.manager.monitor.self.interval = 120
## auto-recovery paused enable or disable
otter.manager.monitor.recovery.paused = true
# manager email user config
otter.manager.monitor.email.host = smtp.gmail.com
otter.manager.monitor.email.username = 
otter.manager.monitor.email.password = 
otter.manager.monitor.email.stmp.port = 465

查看数据库
show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| TESTDB             |
| db                 |
| db1                |
| db2                |
| db3                |
| lunch              |
| mysql              |
| mytest             |
| otter              |
| performance_schema |
| retl               |
| sys                |
| test               |
| test1              |
+--------------------+
有retl数据库
 show tables;
+----------------+
| Tables_in_retl |
+----------------+
| retl_buffer    |
| retl_mark      |
| xdual          |
+----------------+
都创建了这个表，为何还会抛出 table 'retl.retl_mark' doesn't exist 异常

**Comment by linqh1** [comment]
你的canal配置发出来看一下

**Comment by linqh1** [comment]
这个是要求你在同步的源库，目标库都要创建retl库及其下的表的。

你只在otter manager数据库创建retl相关的表是不够的

**Comment by liuyong520** [comment]
> 这个是要求你在同步的源库，目标库都要创建retl库及其下的表的。
> 
> 你只在otter manager数据库创建retl相关的表是不够的
> 
> 类似问题：#180

好的，我试下在源库和目标库都执行一下这个初始化sql

**Comment by liuyong520** [comment]
已经解决了，谢谢！
