### ISSUE TITLE
./install.sh时报错，fastsql-2.0.0_preview_135.pom (No such file or directory)

### ISSUE THREAD

**Issue by CHNPeterWang** [alibaba/otter#824]
下载master压缩包后，执行install.sh是报错

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.4:install-file (default-cli) on project standalone-pom: File not found /usr/local/otter/otter-master/lib/fastsql-2.0.0_preview_135.pom: /usr/local/otter/otter-master/lib/fastsql-2.0.0_preview_135.pom (No such file or directory) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
----------------------------------------------------------------------------------------------------------
请问这个怎么解决啊？

**Comment by agapple** [comment]
可以不需要install fastsql了，跳过这个即可
