### ISSUE TITLE
node 负载均衡问题

### ISSUE THREAD

**Issue by raisemeup** [alibaba/otter#826]
配置了6个同步任务，每个任务我都选择了三个node节点，来保证node的高可用，开始测试的时候同步任务是均匀分布在各个node上的，但是后来使用过程中6个同步任务全都挤到一个node节点上了，另外两个node节点上没有同步任务，想问一下node对同步任务是怎么分配的，为什么会出现这种情况？

**Comment by agapple** [comment]
node是抢占式的，如果有节点出现不可用或者网络抖动，就会被存活的节点给抢占了任务

**Comment by linqh1** [comment]
同有这个问题, 现在只能隔一段时间重启一下CPU跑高的node
