### ISSUE TITLE
主备配置中的master和slave是否填公网IP？

### ISSUE THREAD

**Issue by zhaizhifen** [alibaba/otter#835]
跨IDC同步的，比如2个IDC间MySQL主从集群同步，每个IDC是一主2从的情况，主备配置中的master和slave是填其对应公网IP的么？
![20190925094013](https://user-images.githubusercontent.com/14256359/65562369-c2df6280-df78-11e9-93aa-d0f6c41b42c7.png)

**Comment by agapple** [comment]
node可以联通的ip地址即可
