### ISSUE TITLE
otter-manager配置问题

### ISSUE THREAD

**Issue by ccjetweat** [alibaba/otter#840]
otter-manager搭建之后，发现配置域名之后，访问爆出8080端口，域名配置没有跳转

**Comment by ccjetweat** [comment]
otter.domainName这个地方要配置成域名是吗，但是在4.18版本配置之后好像无效，登录的时候，域名后边自动加上了8080端口，导致otter-manager不能登录

**Comment by linqh1** [comment]
啥意思？
本地测试的时候，domainName配置成127.0.0.1可以登录吗

**Comment by ccjetweat** [comment]
本地是可以，但是线上环境是内网，我配置域名访问，发现每次浏览器上都会把域名替换成otter-manager的内网ip和端口，根本访问不了服务

**Comment by linqh1** [comment]
你要配置dns解析吧，把域名解析到manager的外网ip。不然你从外面是访问不了的

**Comment by ccjetweat** [comment]
我是这样的，我先配置的是解析到nginx，nginx在转发到http服务，这样有问题吗

**Comment by snecker** [comment]
配置域名的话修改 `manager/webapp/WEB-INF/common/uris.xml`

```xml
<uris:uri id="server">
            <serverURI>http(s)://www.example.com/</serverURI>
        </uris:uri>
```
我这样改是ok的

**Comment by ccjetweat** [comment]
> 配置域名的话修改 `manager/webapp/WEB-INF/common/uris.xml`
> 
> ```
> <uris:uri id="server">
>             <serverURI>http(s)://www.example.com/</serverURI>
>         </uris:uri>
> ```
> 
> 我这样改是ok的

感谢感谢感谢，十分感谢，真的解决了，大神蟹蟹！！！！！！
