### ISSUE TITLE
单向同步，延迟最低7min半，按教程来的，是什么原因呢

### ISSUE THREAD

**Issue by a121bc** [alibaba/otter#876]
![image](https://user-images.githubusercontent.com/26868411/69605791-109d4780-105c-11ea-8c1b-619089202b21.png)

**Comment by a121bc** [comment]
![image](https://user-images.githubusercontent.com/26868411/69605912-607c0e80-105c-11ea-9032-ea4c8301f03a.png)
这是监控

**Comment by atjiucheng** [comment]
检查，otter manger、node及数据库的系统时间是否一致。
不一致的话，监控延迟会存在误差。

**Comment by elefaint** [comment]
服务器时间不同步

**Comment by a121bc** [comment]
感谢，是系统时间不对，虚拟机和服务器时间不一致
