### ISSUE TITLE
配置两个manager，收到重复告警

### ISSUE THREAD

**Issue by linqh1** [alibaba/otter#884]
如题，在两个节点分别部署了1个manager实例，node通过域名和manager通信。

但是经常会出现收到两封相同的邮件，从两个节点的manager发出来的。

这个otter没控制吗？

**Comment by lebronye** [comment]
同疑问！

**Comment by zhaizhifen** [comment]
配置两个otter manager， 那么两边添加node机器时，ID都是从1开始，这个会有问题吧？

**Comment by linqh1** [comment]
> 配置两个otter manager， 那么两边添加node机器时，ID都是从1开始，这个会有问题吧？

因为单manager怕节点维护的时候用不了，所以就配了两个manager，看wiki中也提到使用了2个manager。
另外这两个manager数据库也配置了同步。所以应该没问题

**Comment by zhaizhifen** [comment]
原来是manager的meta数据库是同步的，那manager连的数据库也就是meta数据库的主库吧？

**Comment by linqh1** [comment]
> 原来是manager的meta数据库是同步的，那manager连的数据库也就是meta数据库的主库吧？
manager连接各自节点的数据库。如下：

manager A连接 Database A，manager B连接Database B。Database A <--> Database B配置双向同步

然后node 通过域名和manager通信，只会和某一个manager通信(这个从Database A<-->Database B同步中，两个pipeline的同步时间可以看出来)

**Comment by linqh1** [comment]
现在出现的问题是会受到两封相同的邮件
![image](https://user-images.githubusercontent.com/42435177/71153213-7f447e00-2273-11ea-85e4-a966eb78f0bf.png)
![image](https://user-images.githubusercontent.com/42435177/71153228-88354f80-2273-11ea-9392-97a9055fef2c.png)

然后现在的监控又配置了自动恢复，所以好像两个manager都会对channel进行重启操作。。。

现在某个channel经常出现的restart recovery successful for rid，不知道和这个有没有关系

**Comment by zhaizhifen** [comment]
你QQ多少，加个好友沟通聊下？

**Comment by theskyzero** [comment]
哈，这个问题不小心刚好又看到哈
manager默认会开启自身监控，也就是通过jvm，这样2个manager其实就会触发2次监控。
这个配置在manager的配置中大概有个monitor.self什么的配置

所以其实对于多manager就不适合用这个通过JVM自身调度的方式了，otter还提供了通过外部定时任务调用的方式，通过MonitorTrigger类暴露的一个服务，访问
http://xxxx/monitor/monitor_trigger.htm?token=otter即可触发（GlobalMonitor）

这样就依赖于外部来配置定时任务。不过我觉得只保留1个manager的jvm监控也是可以的，其他的关了就行

**Comment by linqh1** [comment]
> 哈，这个问题不小心刚好又看到哈
> manager默认会开启自身监控，也就是通过jvm，这样2个manager其实就会触发2次监控。
> 这个配置在manager的配置中大概有个monitor.self什么的配置
> 
> 所以其实对于多manager就不适合用这个通过JVM自身调度的方式了，otter还提供了通过外部定时任务调用的方式，通过MonitorTrigger类暴露的一个服务，访问
> [http://xxxx/monitor/monitor_trigger.htm?token=otter即可触发（GlobalMonitor）](http://xxxx/monitor/monitor_trigger.htm?token=otter%E5%8D%B3%E5%8F%AF%E8%A7%A6%E5%8F%91%EF%BC%88GlobalMonitor%EF%BC%89)
> 
> 这样就依赖于外部来配置定时任务。不过我觉得只保留1个manager的jvm监控也是可以的，其他的关了就行

确实有个配置控制监控开关的: otter.manager.monitor.self.enable

感谢回答

**Comment by linqh1** [comment]
打算自己加一张表: active_node之类的, 配置当前开启的jvm所在node的名称. 

然后在otter.properties添加一个配置项: current.node. 每次告警时判断jvm所在的node是否在active_node表中,在的话才告警

不然只靠jvm配置的话, dns解析到另外一台jvm的ip的话,就得重启
