### ISSUE TITLE
zookeeper linux启动不了，提示如下

### ISSUE THREAD

**Issue by Bruce2jiang** [alibaba/otter#89]
linux:/opt/zookeeper-3.4.5-cdh4.3.0/bin # ./zkServer.sh
JMX enabled by default
Using config: /opt/zookeeper-3.4.5-cdh4.3.0/bin/../conf/zoo.cfg
Usage: ./zkServer.sh {start|start-foreground|stop|restart|status|upgrade|print-cmd}

**Comment by agapple** [comment]
提示已经很明显了，翻zookeeper文档去
