### ISSUE TITLE
自定义位点信息,单独使用timestamp,position一直显示无信息

### ISSUE THREAD

**Issue by changeyoung2015** [alibaba/otter#895]

**Comment by changeyoung2015** [comment]
试了自定义位点为{"timestamp":1578448679000}; 不管怎么操作,都无法获取到位点信息

**Comment by changeyoung2015** [comment]
添加上journalName
如{"journalName":"mysql-bin.000357","timestamp":1578448679000};
同样一直显示无信息,然后修改数据无法同步

**Comment by changeyoung2015** [comment]
只有使用{"journalName":"mysql-bin.000357","position":579216722}; 这种方式,才可以正常的同步

**Comment by linqh1** [comment]
timestamp的没试过，一直用position

**Comment by changeyoung2015** [comment]
timestamp不可用的原因是binlog日志文件被删除了,但没有重启mysql服务.
只配置个timestamp,会根据binlog.index文件去扫描整个的日志文件然后找到对应的时间戳附近位点信息.可通过以下两个命令验证是否能找到起始位点信息
找endPosition `show master status`,
找startPosition `show binlog events limit 1`

**Comment by changeyoung2015** [comment]
另外,还有可能是没有权限执行 `show binlog events limit 1` 和 `show master status`语句
