### ISSUE TITLE
我建了一个双向channel，主站点的ddl可以同步到目标库

### ISSUE THREAD

**Issue by Bruce2jiang** [alibaba/otter#90]
我建了一个双向channel，主站点的ddl可以同步到目标库，这样只要在主库增加字段就可以同步到目标库了，但是官网上又说：增加字段要先在目标库增加，然后增加主库，感觉有点迷糊了

**Comment by agapple** [comment]
1. 如果不选择同步DDL，现操作目标库，后操作主库
2. 如果选择DDL同步，可以不用操心
