### ISSUE TITLE
otter文件同步,紧急！

### ISSUE THREAD

**Issue by Bruce2jiang** [alibaba/otter#91]
我现在用的是FastDFS 分布式文件系统，存储附件的，如果两地部署业务，数据库同步没有问题，但是附件没办法同步，请问对于分布式文件系统附件怎么同步！

**Comment by agapple** [comment]
基于数据驱动文件同步，需要实现扩展接口.  https://github.com/alibaba/otter/wiki/Otter%E6%89%A9%E5%B1%95%E6%80%A7
