### ISSUE TITLE
otter canal zookeeper高可用问题

### ISSUE THREAD

**Issue by diandiankou** [alibaba/otter#915]
跨机房同步数据时，otter的canal依赖的zk是否可以是独立的zk集群(也就是说两个机房的独立zk集群没关系)，还是说必须是同一个zk集群跨机房部署。

**Comment by ljq23** [comment]
> 跨机房同步数据时，otter的canal依赖的zk是否可以是独立的zk集群(也就是说两个机房的独立zk集群没关系)，还是说必须是同一个zk集群跨机房部署。
请问这个问题解决了嘛，可以跳过zookeeper嘛
