### ISSUE TITLE
主键冲突问题

### ISSUE THREAD

**Issue by Bruce2jiang** [alibaba/otter#92]
你好，我在主库创建一条记录，然后在从库 也创建了一条主键一样的记录，然后启动pipeline,发现没有同步，我知道这是因为主键冲突没有同步，但是我想知道，otter 有生成冲突列表吗？否则我不清楚哪些记录主键冲突了 。

**Comment by agapple** [comment]
先看wiki ： https://github.com/alibaba/otter/wiki/Otter%E6%95%B0%E6%8D%AE%E4%B8%80%E8%87%B4%E6%80%A7
