### ISSUE TITLE
docker manager start ...

### ISSUE THREAD

**Issue by ItisDL** [alibaba/otter#930]
你们的app.sh 脚本里面可以添加一个rm otter.pid的命令
不然会导致docker或容器重启的时候manager启动失败 不是很友好。。。

**Comment by theskyzero** [comment]
哈哈哈，其实那就是个单机封装版，不是很实用，可以自己到容器里修修改改就好了
就算用docker部署，可能也还是分开部署比较好一些

**Comment by theskyzero** [comment]
> 你们的app.sh 脚本里面可以添加一个rm otter.pid的命令
> 不然会导致docker或容器重启的时候manager启动失败 不是很友好。。。

你好，想请教下，你们使用docker进行生产部署了吗，otter上云有个麻烦的地方是需要现在manager上指定nid，ip信息，这个你们注意到了吗，是自己写了一个注册的服务还是？

**Comment by ItisDL** [comment]
> > 你们的app.sh 脚本里面可以添加一个rm otter.pid的命令
> > 不然会导致docker或容器重启的时候manager启动失败 不是很友好。。。
> 
> 你好，想请教下，你们使用docker进行生产部署了吗，otter上云有个麻烦的地方是需要现在manager上指定nid，ip信息，这个你们注意到了吗，是自己写了一个注册的服务还是？

没有 在生产中用呢
