### ISSUE TITLE
otter  zookeeper集群 在zoo.cfg还有增加什么配置吗，有这方面的文档吗

### ISSUE THREAD

**Issue by Bruce2jiang** [alibaba/otter#94]

**Comment by Bruce2jiang** [comment]
我在zoo.cfg 增加下面配置，导致zookeeper都起不来
 server.1=192.168.166.146:2888:3888
server.2=10.17.104.140:2888:3888
server.3=10.18.224.150:2888:3888

**Comment by Bruce2jiang** [comment]
myid我也设置了

**Comment by agapple** [comment]
参考zookeeper官方配置，咨询性的配置建议别走issue，可以在QQ群里交流
