### ISSUE TITLE
我在表配置正则表达式 ^(?!(?:test3|test4)$) ，不等于 test3 表和test4,  但是其他表不能同步数据

### ISSUE THREAD

**Issue by Bruce2jiang** [alibaba/otter#96]
我在表配置正则表达式 ^(?!(?:test3|test4)$) ，不等于 test3 表和test4, 但是其他表不能同步数据

**Comment by Bruce2jiang** [comment]
这个问题很重要

**Comment by Bruce2jiang** [comment]
对我很重要啊，谢谢

**Comment by agapple** [comment]
otter最新版，支持在canal里配置表过滤黑名单

**Comment by bh-sky** [comment]
> otter最新版，支持在canal里配置表过滤黑名单

在otter中如何配置？

**Comment by 9ishell** [comment]
在otter中如何配置？

**Comment by agapple** [comment]
在canal里配置正向的黑名单表达式，就可以实现过滤的效果
