### ISSUE TITLE
实例下数据库全同步，当源实例新建数据库会导致同步失败原因为目标数据库库未创建

### ISSUE THREAD

**Issue by lklkxcxc** [alibaba/otter#962]
实例下数据库全同步，当源实例新建数据库会导致同步失败原因为目标数据库库未创建，源数据库实例A下数据库与目标数据库B实例下数据库建立同步关系，当A实例新建了数据库，在目标B上面不能自动新建数据库导致同步失败，这个可以通过设置otter解决这个问题吗

**Comment by lzbjut** [comment]
可以设置“同步ddl”试试

**Comment by lklkxcxc** [comment]
@lzbjut 同步ddl功能默认是开启的

**Comment by chenweihua** [comment]
DDL不会自动创建库
