### ISSUE TITLE
非常紧急问题，求助

### ISSUE THREAD

**Issue by Bruce2jiang** [alibaba/otter#99]
群主 求助，这个问题已经困扰2周了,我有一个pipeline 的insertcount值不停增长，都已经1,142,065 多了

但实际上只是有很少数据写入数据库的，怎么会有这么多数据传输呢
是不是死循环呢
 帮分析下吧，我真搞不定了啊
 给我一个思路也行
 
是不是死循环呢

**Comment by Bruce2jiang** [comment]
补充：我想删除位点，删除多次，删除成功了，但把pipeline在启动，还是退会到原mysqlslave-bin.000017 binlog的位点,后来我在cannl指定新的位点{"journalName":"mysqlslave-bin.000019","position":286289326};   ，在启动pipeline ,发现pipeline 又退回mysqlslave-bin.000017  的某个位点了

**Comment by Bruce2jiang** [comment]
现象就是位点一直停留在mysqlslave-bin.000017 的某个位点上，而且insertcount 这个值不停增长，都都已经1,142,065 多了

**Comment by Bruce2jiang** [comment]
真诚希望您帮忙分析一下，真搞不定了，快上线了

**Comment by agapple** [comment]
之前没遇到过，要看一下现场
